### ISSUE TITLE
[1.15.2] Bit of a bug.

### ISSUE THREAD

**Issue by Quu1337** [TelepathicGrunt/Bumblezone#1]
Enderpearl in to nest, dig straight up/down, you came out 10x the coords you went in.
Repeat couple times, you are now ~5M blocks out of spawn.
Went in/out ~5 times, im at 29999977, 80, 29999968.
![image](https://user-images.githubusercontent.com/48761355/74463409-7a2e3480-4e9a-11ea-88ab-f4a69085f924.png)

**Comment by TelepathicGrunt** [comment]
fudge. I see the math error I made. That definitely getting a quick patch lmao.

**Comment by TelepathicGrunt** [comment]
Ok. v1.0.2 is now available and fixes this big bug. Thank you so much for reporting it! I have no clue how despite my testing, this buggy bug slipped under my radar.
