### ISSUE TITLE
[1.18.1] Adding bumblezone to an existing Terrablender world will not generate bumblezone dimension

### ISSUE THREAD

**Issue by TelepathicGrunt** [TelepathicGrunt/Bumblezone#109]
https://github.com/Glitchfiend/TerraBlender/issues/38

Terrablender has to fix this on their end. That mod will prevent my mod's dimension from generating if my mod is added after the world is made. Meaning, You have to start the world in single player with the dimension and then move the world to the server. or maybe temporarily remove terrablender, start world, exit world, and then readd terrablender. Be sure to make a backup first

**Comment by TelepathicGrunt** [comment]
terrablender fixed their issue in 1.18.2

**Comment by ZeMilkmann** [comment]
Do you have suggestions for a different workaround for those of us who can not upgrade to 1.18.2 yet?

The suggested workaround of not loading Terrablender (and mods which depend on it) leads to a datapack error when trying to load the world.

**Comment by TelepathicGrunt** [comment]
@ZeMilkmann the only workaround I heard is to start a fresh singleplayer world with all the mods. Then open its level.dat file and copy the Bumblezone dimension entry from WorldGenSettings part to the server’s level.dat file. There’s nothing I can do on my end since this is a terrablender issue

**Comment by ZeMilkmann** [comment]
Thanks man, that worked well and was really easy.

For anyone trying in the future: You need an NBT editor (I used Cyotek NBT Editor), open both the new and the old level.dat file and copy the mentioned part over.
