### ISSUE TITLE
Structure infestation

### ISSUE THREAD

**Issue by JaisDK** [TelepathicGrunt/Bumblezone#11]
Hello there,

Structures are generating inside the bumblezone. I believe this one is from Quark.

![2020-07-13_19 41 03](https://user-images.githubusercontent.com/15868585/87340810-46daf900-c551-11ea-95c2-a94dc777e723.png)
![2020-07-13_19 42 44](https://user-images.githubusercontent.com/15868585/87340834-4e020700-c551-11ea-872b-b1ac9c5ca6d0.png)

There' also oil from Silents Mechanisms
![2020-07-13_20 01 33](https://user-images.githubusercontent.com/15868585/87340870-58bc9c00-c551-11ea-8441-542aad969307.png)

**Comment by TelepathicGrunt** [comment]
This is mainly an issue with the other mods not being careful of which biomes they add their features to.
For example with quark, they add their structure to biomes by config it seems so try checking the config. Right now, Bumblezone's biomes are in the jungle category for some reason (I forget why i ended up picking that) but I'll set it to a None category and you can blacklist the None category biomes using quark's configs
https://github.com/Vazkii/Quark/blob/50b55e8f69b090076cdd93255075c3d9e0e0feea/src/main/java/vazkii/quark/world/module/BigDungeonModule.java#L52

Silent mechanism also loops through all biomes but they do not give a config or and only filter out end and nether biomes. They really should make a config and also filter out none type biomes.
https://github.com/SilentChaos512/Silents-Mechanisms/blob/410b153518ac66279ef8061a3943d4bfc3dd028b/src/main/java/net/silentchaos512/mechanisms/world/SMWorldFeatures.java#L22

**Comment by TelepathicGrunt** [comment]
Oh looks like Mechanism has an issue report for biome configs. I'll post your screenshot to there to help bump the issue up.
https://github.com/SilentChaos512/Silents-Mechanisms/issues/87

**Comment by JaisDK** [comment]
I don't mind the structures as I mostly play to test my mod, but it's good to know that they can be disabled. I finally got around to trying out your mod and figured I would share what I came across. It also helped me find a bug in my mod, aparently comb blocks are missing loot tables and don't drop anything when broken :(

**Comment by TelepathicGrunt** [comment]
Ah makes sense. I just release two new configs for bumblezone to try and reset the biome's feature/structures/mobs back to default after all mods finished initialization. Hopefully this works!

https://www.curseforge.com/minecraft/mc-mods/the-bumblezone-forge/files/3004579

I'll close this issue report as there's really not much more I can do on my end. It's up to the other mods to add configs for what biomes to add their stuff to. Thank you though for letting me know!

**Comment by wtchappell** [comment]
Quark's Config doesn't list the 'NONE' BiomeType: https://github.com/Vazkii/Quark/blob/master/src/main/java/vazkii/quark/base/world/config/BiomeTypeConfig.java#L17

I tried adding 'NONE' to that list then adding 'NONE' to the blacklist in Quark's config, but big dungeons continue spawning in the Bumblezone. I also tried the Bumblezone option to prevent features from other mods generating in the Bumblezone, but that doesn't seem to help either. :(

**Comment by TelepathicGrunt** [comment]
It seemed I accidentally added the config to a spot that was call before the config would actually be read... oops

1.3.9 should fix this and is available on curseforge right now. Hopefully it works this time!

**Comment by wtchappell** [comment]
Setting `clearUnwantedBiomeFeatures = false` with Bumblezone 1.3.9 makes the game crash upon attempting to enter the Bumblezone, at least on my machine: https://paste.ee/p/A40jX

**Comment by TelepathicGrunt** [comment]
Aaaaaaaaaaaaaa why are things null?! 

I'll reopen this issue and look deeper tomorrow. Sorry about that. This is why I shouldn't stay up super late coding lol

**Comment by TelepathicGrunt** [comment]
Alright did some fixed and v1.3.10 should be good to go. I tested it much more extensively so let me know if any new issue comes up! If no issue pops up in like two or three days, I'll close this report.

Thank you for helping me out by pointing out the bugs! :)

**Comment by wtchappell** [comment]
No crashes or dungeons on 1.3.10 so far!

**Comment by TelepathicGrunt** [comment]
awesome! Seems to be good im guessing. Thank you for your help!
