### ISSUE TITLE
World locks up when removing the mod, with "Error loading datapacks"

### ISSUE THREAD

**Issue by Inonedn** [TelepathicGrunt/Bumblezone#112]

**Comment by TelepathicGrunt** [comment]
I would need the full latest.log file in order to help. Without it, I do not know what the issue can even be. 

Edit: thought we were on my repurposed structures repo. My bad. Since this is Bumblezone, I 100% need to see the log file

**Comment by TelepathicGrunt** [comment]
it's been a week with no additional info. I'm going to close this issue report since without extra info, there's nothing I can do
