### ISSUE TITLE
No honey or sugar water

### ISSUE THREAD

**Issue by MrCoolz123456** [TelepathicGrunt/Bumblezone#114]
Hello i found out that when i use a glass bottle on sugar water, honey slimes or porous honeycomb blocks nothing is given to me.

**Comment by TelepathicGrunt** [comment]
What minecraft version and Bumblezone version are you using? And is this in a modpack (if so, which modpack?)

**Comment by MrCoolz123456** [comment]
I am using Minecraft 1.18.2 and i have the latest version of the mod. I am playing with Productive Bees, Beekeeper, JEI and Queen Bee

**Comment by TelepathicGrunt** [comment]
thank you for reporting this! Should be fixed in v5.0.11 now. Surprised no one else reported the issue earlier
