### ISSUE TITLE
[1.19][Server] REI Startup error

### ISSUE THREAD

**Issue by Geartwo** [TelepathicGrunt/Bumblezone#120]
The Bumblezone v6.0.0

When starting the server, REI throws an error and crashes.

Possible solution:
Change "rei_common" to "rei_client"

![image](https://user-images.githubusercontent.com/4224642/175893415-d69a9fea-1b53-41c4-98a0-692b8a1a4611.png)

**Comment by TelepathicGrunt** [comment]
can you try this please?
[the_bumblezone_fabric-6.0.1-test+1.19.jar.zip](https://github.com/TelepathicGrunt/Bumblezone/files/8991934/the_bumblezone_fabric-6.0.1-test%2B1.19.jar.zip)

**Comment by Geartwo** [comment]
Testet with REI + WTHIT + The Bumblezone (And Dependencys) and...

IT WORKS!

Thank you

**Comment by TelepathicGrunt** [comment]
Just released 6.0.1. hopefully I didnt break anything
