### ISSUE TITLE
Not compatible with forge after .64 update for 1.19

### ISSUE THREAD

**Issue by Onehanddan** [TelepathicGrunt/Bumblezone#122]
Please see title as is affecting many mods since forge .64

**Comment by TelepathicGrunt** [comment]
Ik it isn’t compatible lol. I’m still working on a large update already and the fix to work with newer forge will be included. I just need more time as the update is quite extensive

**Comment by Baggytrousers27** [comment]
Same thing with 41.0.94+

**Comment by TelepathicGrunt** [comment]
@Baggytrousers27 correct because I haven't release my update yet for the forge breaking changes. Bumblezone will not work on any forge version newer than .64. The v6.1.0 update for bumblezone will work with newest forge at the time of release.

**Comment by Baggytrousers27** [comment]
Was just commenting that 41.0.94+ add even more breaking changes.

**Comment by TelepathicGrunt** [comment]
v6.1.0. bumblezone is out now and will work on latest forge. Well, anything above forge 41.0.94 or so.
