### ISSUE TITLE
V6.1.6 of Bumblezone Fabric is marked for 1.19, but requires Minecraft 1.19.2

### ISSUE THREAD

**Issue by floral-qua-floral** [TelepathicGrunt/Bumblezone#132]
[This is the file in question.](https://modrinth.com/mod/the-bumblezone-fabric/version/6.1.6%2B1.19.2) It's only marked for 1.19, but the fabric.mod.json requires Minecraft 1.19.2, so it won't launch on 1.19.

**Comment by TelepathicGrunt** [comment]
V6.1.6 fabric Bumblezone cannot run in 1.19 because of music disc constructor changed. I’ll fix the version mark in cf as it should be just 1.19.2 only. Not 1.19 at all
