### ISSUE TITLE
Exiting the Bumblezone

### ISSUE THREAD

**Issue by Chief0609** [TelepathicGrunt/Bumblezone#142]
as the title sugests, I dont know how to exit the bumblezone, and i cant seem to figure out how to either

**Comment by TelepathicGrunt** [comment]
You exit Bumblezone by digging down and falling below y = 0 or digging up and climbing above y = 256. This is to make it seem like you’re digging out of the beehive. You will not die when falling out of the dimension as my mod will lock you to y = -3 as it teleports you out

If you have any other questions or confusion, check out my mod page here as it contains a ton of info on my mod. 
https://www.curseforge.com/minecraft/mc-mods/the-bumblezone-forge

if you have a question not answered on my mod page, feel free to ask me
