### ISSUE TITLE
Glistering Honey Crystals Dropping Honey Crystal Blocks With Silk Touch

### ISSUE THREAD

**Issue by SuperiorDonut** [TelepathicGrunt/Bumblezone#144]
I'm thus unable to acquire glistering honey crystals as a result; I'm on Quilt v6.2.11

I'm using a Paxel from the "piercing paxels" mod, but the issue is there regardless of what tool I use (including nonsense like shears and swords, lol).

You could possibly make the block craftable with 4 honey crystals as well, but that's more of an idea than a bug fix, haha.

https://user-images.githubusercontent.com/114554928/195284018-8bc0c204-5e7b-4069-a215-5bf74dce58ba.mp4

**Comment by TelepathicGrunt** [comment]
Looks like I accidentally forgot to change this line to glistering honey block
https://github.com/TelepathicGrunt/Bumblezone/blob/1f0de63dca6de0b05ccfa7362225ebb929401088/src/main/resources/data/the_bumblezone/loot_tables/blocks/glistering_honey_crystal.json#L12

Will fix next update. When I add a new block. It’ll take me a bit of time before I get the new update out but you can fix this loot table file with a datapack for now as a workaround

**Comment by TelepathicGrunt** [comment]
fixed now in v6.3.0 that is released. Thank you for the report!
