### ISSUE TITLE
Blocked Giant Candles Consume Flint and Steel Charges Despite Being Unlightable, and Have Bugged Wicks Below Top Slabs

### ISSUE THREAD

**Issue by SuperiorDonut** [TelepathicGrunt/Bumblezone#145]
When using flint and steel on a giant candle that has another block on top (including other giant candles), it consumes the durability of your flint and steel despite doing nothing to the candle itself.

https://user-images.githubusercontent.com/114554928/195287460-aac7671d-c312-4217-a083-68dedfa8d025.mp4

Additionally, when a giant candle is below a top slab, the wick is absent despite its model being low enough to fully fit. Ideally it would also be able to be lit underneath a top slab, but I don't know if that's possible/feasible, so this sentence can be ignored if it's something that would be hard/annoying to do.

![image](https://user-images.githubusercontent.com/114554928/195288258-fb56871c-0e1d-4b65-a279-ad5b436be7b7.png)

**Comment by TelepathicGrunt** [comment]
A block position cannot have two blocks simultaneously. So if you’re asking for both a wick and slab to occupy the same block position, then no that will not be possible and definitely not a rabbit hole of hell I want to get into lol.

The wick will only spawn if the block position above the candle base is an air block. 

For the damaging, looks like I need to modify this if statement check to make sure the blockstate did change state to lit first. Will fix in next update
https://github.com/TelepathicGrunt/Bumblezone/blob/1f0de63dca6de0b05ccfa7362225ebb929401088/src/main/java/com/telepathicgrunt/the_bumblezone/blocks/IncenseCandleBase.java#L166

**Comment by TelepathicGrunt** [comment]
fixed now in v6.3.0 that is released. Thank you for the report!
