### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by UrBoiTom** [TelepathicGrunt/Bumblezone#146]
https://pastebin.com/EBPuhQ9x

Game starts loading then crashes after about a minute

**Comment by TelepathicGrunt** [comment]
@Sorro123 I do not see anything in that log that points to my mod as the issue. You got a mod or datapack that is trying to change the model for vanilla’s firework item but is failing for some reason. 

Do you know of any mod or datapack that’s messing with the vanilla firework in your modpack? If so, try removing said mod or datapack and see if that helps.

If not, share the latest.log file instead from the logs folder above the mods folder. It might have more info as to who is making the model change

**Comment by UrBoiTom** [comment]
I might have found the problem will update in a minute
also srry if it isn't your mod causing the problem, the first mod name in the crash was bumblezone so I just guessed

**Comment by UrBoiTom** [comment]
nope. Thought it might be pyrotastic, but I removed that and now salmon is giving me the error instead

[crash report](https://pastebin.com/gJjYTc7H)

[latest.log](https://github.com/TelepathicGrunt/Bumblezone/files/9852962/latest.log) not on pastebin bc too big

**Comment by UrBoiTom** [comment]
Found the problem, nicephore.
