### ISSUE TITLE
Minecolonies 1.16.2 Compat Issue

### ISSUE THREAD

**Issue by nathanthefriendlybabydev** [TelepathicGrunt/Bumblezone#16]
I have tried allocating more ram etc but when I have this mod in my folder on the newest forge on 1.16.2 it causes the game to exit with error code : 0

**Comment by TelepathicGrunt** [comment]
Can you get me the latest.log file? You can find it in the logs folder below the mods folder. It'll basically tell me exactly what happened to cause the crash and I can then can investigate properly

**Comment by nathanthefriendlybabydev** [comment]
I have experimented a bit and figured it actually only crashes when I load other mods, I am not sure what mod is causing the crash when paired with BumbleZone but I will post the latest log file

**Comment by nathanthefriendlybabydev** [comment]
[latest.log](https://github.com/TelepathicGrunt/Bumblezone/files/5160036/latest.log)
If you could let me know what you find out about which mod pairing is causing the issue that would be much appreciated

**Comment by TelepathicGrunt** [comment]
Looks like it is crashing on this line of code.
https://github.com/TelepathicGrunt/Bumblezone/blob/f5755b98461c56cf3ac7cf1d2b8ef354037be91d/src/main/java/com/telepathicgrunt/the_bumblezone/entities/BeeAggression.java#L60

What I'm doing here is taking all the registered entity types and creating a temporary entity that I can use to check if it is in the Arthropod category so I can make bees be naturally aggressive towards that mob when it is spawned in the Bumblezone. However, it seems minecolonies's EntityMercenary is crashing there for some reason which is super odd. If you remove minecolonies, does the crash still happen? If so, can I see that new log? Maybe there's a pattern to the crashes...

**Comment by nathanthefriendlybabydev** [comment]
The crash no longer occurs.  Here is the link to their source code for the Mercenary Entity
https://github.com/ldtteam/minecolonies/blob/version/1.15/src/main/java/com/minecolonies/coremod/entity/mobs/EntityMercenary.java

**Comment by nathanthefriendlybabydev** [comment]
I am unable to access their source for 1.16.2 since it currently is in Beta

**Comment by TelepathicGrunt** [comment]
Ok so it seems to just be a mod compat issue. I can try something to make it not crash if it fails to make a mob and basically skip it. I'll push out a fix tomorrow!

**Comment by nathanthefriendlybabydev** [comment]
Thank you!

**Comment by TelepathicGrunt** [comment]
V2.0.1 is now out and should prevent this specific crash! Hopefully it'll work now

https://www.curseforge.com/minecraft/mc-mods/the-bumblezone-forge/files/3048125

**Comment by nathanthefriendlybabydev** [comment]
Yes it does!  Thank you
