### ISSUE TITLE
Crash Upon Breaking Block

### ISSUE THREAD

**Issue by Areorah** [TelepathicGrunt/Bumblezone#17]
Bumblezone Version: 2.0.3
https://gist.github.com/Areorah/62093f838929a7f1262c6ad93593e145

**Comment by TelepathicGrunt** [comment]
Ok so this is the line it is crashing at.
https://github.com/TelepathicGrunt/Bumblezone/blob/05afae3fbd8027da74830ec001be3ad6bc63804a/src/main/java/com/telepathicgrunt/the_bumblezone/blocks/HoneycombBrood.java#L230-L231

But what is super weird is the active hand is null when it shouldn't be. The player is mining so their mining hand should be returned... Very odd.

Will look into!

**Comment by TelepathicGrunt** [comment]
Fixed in 2.0.4!
Thank you for reporting this! :)

https://www.curseforge.com/minecraft/mc-mods/the-bumblezone-forge/files/3052021
