### ISSUE TITLE
Repository Basics

### ISSUE THREAD

**Issue by ElectronicsArchiver** [TelepathicGrunt/Bumblezone#172]
I would recommend you disabled the unused features in your repository.

- Actions

- Projects

**Comment by TelepathicGrunt** [comment]
Cleaned up now

**Comment by ElectronicsArchiver** [comment]
<br>

Weird way of ending the discussion, locking that is.
So here's my last response that I was about to sent.

<br>

---

<br>

> Please stop.

I would obviously want to discuss my PR and possibly find a compromise.

> I do not want extra images or buttons in my changelogs. It should just be the changes without any fluff or fancy stuff.

Well that's too bad.

> Also you will be surprised at how much CurseForge breaks with markdown as their markdown isn’t true markdown. I fought curseforge’s “markdown” a ton already and not looking to do so again lol.

Too bad they are the goto platform..

> You can try and offer this idea to other people who may be more receptive of this tool.

Sure, though not this version exactly, as it is customized for this project obviously.

> But generally, it’s a good idea to ask someone if they will want a tool or large change before actually making the PR so you don’t waste time if they say no.

Actually no, people are more willing to look into something if the work is already done, while yes, I may 'waste' my time sometimes, that is a price I'm willing to pay.

> Again, sorry but this is not something I want in my workflow nor changelog

Too bad ..

<br>

---

<br>

Good luck with your mod & your changelog.

<br>
