### ISSUE TITLE
[Quilt 6.6.1 1.19.3] Crash with Lithium

### ISSUE THREAD

**Issue by MoriyaShiine** [TelepathicGrunt/Bumblezone#187]
I'm not sure what causes this crash, but it only happens when The Bumblezone is installed alongside Lithium

[crash-2023-01-11_16.01.36.7279-quilt_loader.txt](https://github.com/TelepathicGrunt/Bumblezone/files/10396263/crash-2023-01-11_16.01.36.7279-quilt_loader.txt)

**Comment by TelepathicGrunt** [comment]
Fun. Only happens in 1.19.3 Quilt/Fabric with Lithium. Not 1.19.2

**Comment by TelepathicGrunt** [comment]
@MoriyaShiine try this jar. It seems to fix the issue for me
[the_bumblezone_quilt-6.6.2-beta+1.19.3.jar.zip](https://github.com/TelepathicGrunt/Bumblezone/files/10396909/the_bumblezone_quilt-6.6.2-beta%2B1.19.3.jar.zip)

**Comment by MoriyaShiine** [comment]
Yep, that works.  Thanks!

**Comment by TelepathicGrunt** [comment]
Reopening as I haven't released the fix yet. I keep my issue open until release so that other users can see the issue is reported and not out yet

**Comment by TelepathicGrunt** [comment]
v6.6.2 is now release with the fix
