### ISSUE TITLE
`bovinesandbuttercups:freesia` is not in bovinesandbuttercups compatibility json

### ISSUE THREAD

**Issue by ChrysanthCow** [TelepathicGrunt/Bumblezone#194]
I might make a PR for this in a bit, but this flower was added after you made the file.

On a side note, you've included Minecraft's flowers when they aren't a valid moobloom type in the base mod.

**Comment by TelepathicGrunt** [comment]
I kept the minecraft flowers in just in case people do make extra moobloom types as those Mc flowers are probably going to be the most likely flowers they add lol. 

I’ll add the new flower entry next update

**Comment by ChrysanthCow** [comment]
> I kept the minecraft flowers in just in case people do make extra moobloom types as those Mc flowers are probably going to be the most likely flowers they add lol.
> 
> I’ll add the new flower entry next update

this is fair.

**Comment by TelepathicGrunt** [comment]
Added in the newest 1.19.2 bumblezone update released now.
The addition for the 1.19.3 bumblezone is coming soon.

**Comment by TelepathicGrunt** [comment]
fixed now in 6.6.3 releases for 1.19.3
