### ISSUE TITLE
[1.18.2 Forge] Music Discs don't have the minecraft:music_discs tag

### ISSUE THREAD

**Issue by vizthex123** [TelepathicGrunt/Bumblezone#197]
Would be nice to have them.

**Comment by TelepathicGrunt** [comment]
1.18.2 is no longer supported. I only support 1.19.2 and latest Mc version. Then when 1.20 comes out, I’ll drop 1.19 support.

I’ll add the music discs to that tag in 1.19.2 and 1.19.3. But may I ask what the use case is? The minecraft tag doesn’t have any behavior by default so I’m curious as to what this is for

**Comment by vizthex123** [comment]
Some mods use it, and my custom recipes do too.

Plus, I just like mods to use standard tags. Always bothers me when the don't.
