### ISSUE TITLE
Dimension Chunk Loading causes Crashing Lag

### ISSUE THREAD

**Issue by dreckz** [TelepathicGrunt/Bumblezone#2]
MC: 1.15.2
Bumblezone: 1.0.2

Upon entering the dimension, everything is fine, when I was in the starting area isolated in the honeycomb.  I broke a few blocks to get out into the main area, and everything loaded fine at first.  But then, I think the chunkloading was lagging because it was REALLY hard for my client to load everything.

The problem was so bad, even standing still was super laggy and hard to move around.

I feel as if the lag was due to the height of the dimension and attempting to generate so much.

**Comment by TelepathicGrunt** [comment]
Height should not have to do anything with it as the dimension's height is the same as the overworld and End (255). Though have you tried using v1.0.4? There was an issue with mobs spawning at y = 0, suffocating, and their items gets stuck while teleporting upwards through all the blocks. I suspect that was a big reason for lag so please try 1.0.4 and let me know if things are better!

**Comment by dreckz** [comment]
Fixed in 1.0.4, you're right!  Thanks!

**Comment by TelepathicGrunt** [comment]
YAY! pesky bees! The bug has been exterminated!
