### ISSUE TITLE
Bumblezone with BoP caused worlds to not be saved properly or loaded at times

### ISSUE THREAD

**Issue by TelepathicGrunt** [TelepathicGrunt/Bumblezone#20]
very strange. Blame did not show any dynamicregistry issues

[latest (1).log](https://github.com/TelepathicGrunt/Bumblezone/files/5399179/latest.1.log)

[latest (2).log](https://github.com/TelepathicGrunt/Bumblezone/files/5399178/latest.2.log)

**Comment by TelepathicGrunt** [comment]
Did more testing and i cannot reproduce this issue alone with bumblezone in prod. Has to be a mod conflict going on i think

**Comment by TelepathicGrunt** [comment]
someone else's modlist with the issue 
![image](https://user-images.githubusercontent.com/40846040/96881626-7650aa00-144c-11eb-9c8a-b531e516027b.png)

Gonna start going through it tonight to find which mod is either feeding bumblezone the wrong registry or is removing bumblezone biomes from the biome registry

**Comment by TelepathicGrunt** [comment]
Wow I'm blind lol. Inpaladin in https://github.com/TelepathicGrunt/Bumblezone/issues/22 narrowed the issue to BoP with Bumblezone. very odd. What is BoP doing?

**Comment by TelepathicGrunt** [comment]
Old crash before my patch. BoP caused my biome source to get a biome registry that does not contain my biomes which is very odd.
<https://pastebin.com/rTy59teF>

After my patch, it now chokes within BoP itself with this error: https://pastebin.com/31j2LUhp
It seems BoP is breaking the json dimension parsing somehow. 
`[22Oct2020 10:42:01.061] [Render thread/ERROR] [net.minecraft.world.storage.SaveFormat/]: WorldGenSettings: Failed to parse the_bumblezone:dimension_type/the_bumblezone.json file: the_bumblezone:dimension_type/the_bumblezone.json missed input: {"the_bumblezone:the_bumblezone":{generator:{structures:{structures:{}},biome_source:{type:"the_bumblezone:biome_source"},type:"the_bumblezone:chunk_generator"},type:"the_bumblezone:the_bumblezone"}}`

This is related to this issue
https://github.com/Glitchfiend/BiomesOPlenty/issues/1704

**Comment by lulabyte** [comment]
I do not have Bumblezone but I still get the error. My mod list:

 Waystones_1.16.3-7.3.0.jar"
 [1.16.2][Forge]+RPG-HUD-3.8.2.jar"
 [1.16.3]+SecurityCraft+v1.8.20.jar"
 AdChimneys-1.16.3-6.0.2.0-build.0017.jar"
 AdHooks-1.16.3-6.1.1.0-build.0017.jar"
 AdLods-1.16.3-4.1.0.1-build.0024.jar"
 aiotbotania-1.16.2-1.3.2.jar"
 angelring-1.16.3-1.3.3.jar"
 Apotheosis-1.16.3-4.3.2.jar"
 appliedenergistics2-8.1.0-alpha.3.jar"
 Aquaculture-1.16.3-2.1.1.jar"
 AttributeFix-1.16.3-8.0.1.jar"
 AutoRegLib-1.6-46.jar"
 bambooeverything-1.16.3-forge-1.0.0.jar"
 BiomesOPlenty-1.16.3-12.0.0.409-universal.jar"
 Bookshelf-1.16.3-8.6.19-javadoc.jar"
 Botania-1.16.3-409.jar"
 BotanyPots-1.16.3-5.1.9.jar"
 buildinggadgets-3.7.1.jar"
 comforts-forge-1.16.3-4.0.0.1.jar"
 Controlling-7.0.0.8.jar"
 CookingForBlockheads_1.16.3-9.2.1.jar"
 CosmeticArmorReworked-1.16.3-v1.jar"
 Craftable+Saddles+[1.16.3]-1.3.jar"
 creeperconfetti-3.4.jar"
 CTM-MC1.16.1-1.1.1.5.jar"
 Cucumber-1.16.3-4.1.2.jar"
 curios-forge-1.16.3-4.0.2.0.jar"
 Cyclic-1.16.3-0.8.3.jar"
 DarkUtilities-1.16.3-6.0.1.jar"
 decorative_blocks-1.16.2-1.1.jar"
 DungeonCrawl-1.16.3-2.1.1.jar"
 elevatorid-1.16.3-1.7.6.jar"
 embellishcraft-1.16.3-3.1.0.1.jar"
 enchantedbookredesign-3.1a.jar"
 EnchantmentDescriptions-1.16.3-5.0.1.jar"
 endertanks-1.16-1.9.3.jar"
 fakeblocks-1.16.3-1.0.1.jar"
 FallingTree-Forge-1.16.3-2.5.0.jar"
 ForgeEndertech-1.16.3-7.0.6.0-build.0024.jar"
 furniture-7.0.0-pre19-1.16.3.jar"
 guardvillagers-1.16.3-1.1.5.jar"
 horsestandstill-1.16.3-1.0.1.jar"
 Inspirations-1.16.3-1.2.1.24.jar"
 ironchest-1.16.3-11.2.6.jar"
 jei-1.16.3-7.6.0.49.jar"
 JustEnoughResources-1.16.3-0.12.0.100.jar"
 Kiwi-1.16.3-3.4.0.jar"
 Lollipop-1.16.3-3.2.2.jar"
 lootbagmod-1.16.3-1.6.2.jar"
 Ma-Enchants-1.16.3-3.5.0.jar"
 mahoutsukai-1.16.3-v1.25.0.jar"
 managear-1.16.3-2.1.2.jar"
 Mantle-1.16.3-1.6.40.jar"
 mapperbase-1.16.3-2.1.0.1.jar"
 mcpaint-1.6.2.jar"
 mcw-doors-1.0.1fix-mc1.16.3-1.16.2.jar"
 mcws-roofs-1.16.3-v2.0.0.jar"
 mcw-windows-1.0.2-mc1.16.3.jar"
 mermaidtail-1.4.jar"
 multibeds-1.16-1.7.4.jar"
 MysticalAgradditions-1.16.3-4.1.0.jar"
 MysticalAgriculture-1.16.3-4.1.0.jar"
 NaturesCompass-1.16.3-1.8.5.jar"
 NetherPortalFix_1.16.3-7.2.0.jar"
 PackingTape-1.16.3-0.10.0.jar"
 pamhc2foodcore-1.16.3-1.0.0.jar"
 Patchouli-1.16.2-47.jar"
 Placebo-1.16.3-4.3.2.jar"
 potionofbees-1.16.3-1.1.0.1.jar"
 Powah-1.16.3-2.3.2.jar"
 productivebees-1.16.3-0.4.1.4.jar"
 Quark-r2.4-269.jar"
 randomloot-2.1.7.jar"
 randompatches-1.16.2-1.22.1.2.jar"
 repurposed_structures-1.16.3-2.2.9.jar"
 RingOfAttraction-1.16.3-1.2.7.jar"
 ServerTabInfo-1.16.3-1.3.3.jar"
 shetiphiancore-1.16-3.8.3.jar"
 SilentGear-1.16.3-2.3.1+166.jar"
 SilentGems-1.16.3-3.7.1+104.jar"
 SilentLib-1.16.3-4.8.1+61.jar"
 SimpleDivingGear-5.0.3+mc+1.16.3.jar"
 simplefarming-1.16.3-1.3.3.jar"
 SimplyJetpacks2-1.16.3-2.6.3.0.jar"
 sit-1.16.2-v1.3.jar"
 SnowRealMagic-1.16.3-2.2.1.jar"
 StorageDrawers-1.16.3-8.2.0.jar"
 torchmaster-2.3.4-alpha.jar"
 u_team_core-1.16.3-3.1.10.183.jar"
 Uncrafted-1.16-4.0.0pre1.jar"
 useful_backpacks-1.16.3-1.11.6.83.jar"
 valhelsia_structures-16.0.4.jar"

**Comment by TelepathicGrunt** [comment]
Are any of those a dimension mod? BoP will break dimension mods that uses json DimensionTypes. It also seems BoP has a few other triggers for the issue as well. Please show them your mod list on their issue report as that will be super helpful for them! 
 Glitchfiend/BiomesOPlenty#1704

**Comment by lulabyte** [comment]
Will do, thanks! I'll check for dimension mods and experiment with removing them.

**Comment by TelepathicGrunt** [comment]
latest bop fixed this issue
