### ISSUE TITLE
Blue bee variant

### ISSUE THREAD

**Issue by TelepathicGrunt** [TelepathicGrunt/Bumblezone#204]
See about making blue bee variant in a way that is not lost when bee goes into hive and out

**Comment by ColonelGerdauf** [comment]
While blue bees do exist in the real world, it should be noted that they are rare, as are green, white, and especially purple bees.

There is a reason why us hoomans associate bees as yellow.

**Comment by ColonelGerdauf** [comment]
Actually, on the topic of rarity, you can make it an achievement objective for the players to find the coloured bees.

**Comment by TelepathicGrunt** [comment]
amount of effort to do this is a bit too much for me to do easily on arch setup. Also seems incredibly fragile and prone to breaking stuff. Will not implement this as new bee skin for vanilla bees. Maybe as brand new entity in far future but not now

**Comment by TelepathicGrunt** [comment]
Added bee variants as new entity now. Will make it easier for datapackers and modpack makers to detect these variants and do stuff with them
https://github.com/TelepathicGrunt/Bumblezone/commit/325be4d078f705381965ae4f75d34aa7f2af81bb

**Comment by TelepathicGrunt** [comment]
done in 1.20.1
