### ISSUE TITLE
Structure Suggestions

### ISSUE THREAD

**Issue by TelepathicGrunt** [TelepathicGrunt/Bumblezone#205]
Bee Subway (plus shaped enclosed tunnel with openings at top and rest spots on side?) Need to keep away from Cell maze or else the two fused badly

**Comment by ColonelGerdauf** [comment]
They would ideally have a separate in and out path, much like an actual train network.

As another suggestion, does this mod have anything to the likes of a bee city? Something resembling a fictional supercity?
In that context, maybe a skyward city resembling something from the Jetsons.

**Comment by Shibva** [comment]
hmmm maybe also include some ways to make other things wtih it; there's not much to build with

the carving wax could be made to form stairs and stuff too and have the same carving mechanic as well

*for now though YTTR cutter thing will make work lamo*
<img width="540" alt="image" src="https://user-images.githubusercontent.com/38770780/236611705-39422ecb-f6d5-4ae2-a6d3-b6ed27db5d5f.png">

**Comment by TelepathicGrunt** [comment]
1.20.1 update added several new structures now
