### ISSUE TITLE
Unable to render "Porous Honeycomb Block"

### ISSUE THREAD

**Issue by maciejkrol18** [TelepathicGrunt/Bumblezone#208]
My game seems to be unable to render the Porous Honeycomb Block, causing most of the dimension look as if i had some sort of Xray on. 
The bug appears on both singleplayer on multiplayer. 
Turning off shaders doesn't do anything. 
Screenshots were taken on the server
Mod version: 6.6.3

<details>
<summary>Mods installed on the server</summary>

1. AxesAreWeapons-1.6.5-fabric-1.19.3.jar
2. Clumps-fabric-1.19.3-9.0.0+16.jar
3. Debugify-1.19.3+1.0.jar
4. Emojiful-Fabric-1.19.3-4.1.0.jar
5. FallingTree-1.19.3-3.11.2.jar
6. HWGMod-1.19.3-1.3.3.jar
7. LuckPerms-Fabric-5.4.60.jar
8. Structory-1.19-v1.3.jar
9. TinyCoal-fabric-1.19.3-1.1.0.jar
10. WilderWild-1.1.10-Fabric+1.19.3.jar
11. YetAnotherConfigLib-2.2.0.jar
12. ad_astra-fabric-1.19.3-1.13.4.jar
13. anti-xray-1.3.0-Fabric-1.19.3.jar
14. architectury-7.1.70-fabric.jar
15. azurelib-fabric-1.19.3-1.0.2.jar
16. botarium-fabric-1.19.3-2.0.4.jar
17. carryon-fabric-1.19.3-2.0.4.15.jar
18. cloth-config-9.0.94-fabric.jar
19. collective-1.19.3-6.43.jar
20. easyauth-mc1.19.3-3.0.0-14.jar
21. ecologics-fabric-1.19.3-2.1.12.jar
22. entityculling-forge-1.5.2-mc1.19.3.jar
23. expanded-axe-enchanting-1.0.5.jar
24. fabric-api-0.73.2+1.19.3.jar
25. fabric-language-kotlin-1.9.1+kotlin.1.8.10.jar
26. ferritecore-5.1.0-fabric.jar
27. followersteleporttoo-1.19.3-2.0.jar
28. friendsandfoes-fabric-mc1.19.3-1.7.5.jar
29. immersive_aircraft-0.3.0+1.19.3-fabric.jar
30. immersive_paintings-0.4.4+1.19.3-fabric.jar
31. krypton-0.2.1.jar
32. lazydfu-0.1.3.jar
33. lithium-fabric-mc1.19.3-0.10.4.jar
34. memoryleakfix-1.19.3-0.7.0.jar
35. moremobvariants-1.0.1-1.19.3.jar
36. nohostilesaroundcampfire-1.19.3-5.0.jar
37. nounusedchunks-1.4.jar
38. observable-4.3.1.jar
39. plasmovoice-fabric-1.19.3-1.2.19.jar
40. powershot-1.4.0-1.19.3-fabric.jar
41. resourcefulconfig-fabric-1.19.3-1.1.2.jar
42. resourcefullib-1.2.7.jar
43. servercore-1.3.4-1.19.3.jar
44. skin-restorer-1.2.2.jar
45. smoothboot-fabric-1.19-1.7.1.jar
46. starlight-1.1.1+fabric.ae22326.jar
47. styled-chat-2.1.2+1.19.3.jar
48. tabtps-fabric-mc1.19.3-1.3.16.jar
49. the_bumblezone-6.6.3+1.19.3-fabric.jar
50. toms_storage_fabric-1.19.3-1.4.6.jar
51. totw_additions-1.2.3-1.19.x-fabric.jar
52. travelers-backpack-1.19.3-8.3.2.jar
53. ultris-v5.6.7e-fabric.jar
54. villagerdeathmessages-1.19.3-3.1.jar
55. youre-in-grave-danger-1.5.1.jar

</details>

<details>
<summary>Mods installed on the client</summary>

1. ad_astra-fabric-1.19.3-1.13.4.jar
2. architectury-7.1.70-fabric.jar
3. automodpack-3.0.3-1.19.3.jar
4. azurelib-fabric-1.19.3-1.0.2.jar
5. beenfo-1.19.3-fabric0.68.1-1.3.3.jar
6. betterbeds-1.3.0-1.19.3.jar
7. BetterF3-5.1.0-Fabric-1.19.3.jar
8. botarium-fabric-1.19.3-2.0.4.jar
9. carryon-fabric-1.19.3-2.0.4.15.jar
10. cloth-config-9.0.94-fabric.jar
11. collective-1.19.3-6.43.jar
12. CullLessLeaves-1.1.0.jar
13. do-a-barrel-roll-2.6.2+1.19.3-fabric.jar
14. DripSounds-1.19-0.3.1.jar
15. dynamic-fps-2.2.0.jar
16. ecologics-fabric-1.19.3-2.1.12.jar
17. Emojiful-Fabric-1.19.3-4.1.0.jar
18. fabric-api-0.73.2+1.19.3.jar
19. fabric-language-kotlin-1.9.1+kotlin.1.8.10.jar
20. ferritecore-5.1.0-fabric.jar
21. friendsandfoes-fabric-mc1.19.3-1.7.5.jar
22. HWGMod-1.19.3-1.3.3.jar
23. immersive_aircraft-0.3.0+1.19.3-fabric.jar
24. immersive_paintings-0.4.4+1.19.3-fabric.jar
25. inventorymanagement-1.1.0+1.19.3.jar
26. iris-mc1.19.3-1.5.2.jar
27. lambdynamiclights-2.2.0+1.19.3.jar
28. lazydfu-0.1.3.jar
29. lithium-fabric-mc1.19.3-0.10.4.jar
30. memoryleakfix-1.19.3-0.7.0.jar
31. microdurability-0.3.6+1.19.jar
32. modmenu-5.0.2.jar
33. moremobvariants-1.0.1-1.19.3.jar
34. Neat-1.19.3-33-FABRIC.jar
35. notenoughanimations-fabric-1.6.2-mc1.19.3.jar
36. observable-4.3.1.jar
37. plasmovoice-fabric-1.19.3-1.2.19.jar
38. resourcefulconfig-fabric-1.19.3-1.1.2.jar
39. resourcefullib-1.2.7.jar
40. RoughlyEnoughItems-10.0.586.jar
41. smoothboot-fabric-1.19-1.7.1.jar
42. sodium-fabric-mc1.19.3-0.4.9+build.23.jar
43. Structory-1.19-v1.3.jar
44. the_bumblezone-6.6.3+1.19.3-fabric.jar
45. TinyCoal-fabric-1.19.3-1.1.0.jar
46. toms_storage_fabric-1.19.3-1.4.6.jar
47. travelers-backpack-1.19.3-8.3.2.jar
48. WilderWild-1.1.10-Fabric+1.19.3.jar
49. Xaeros_Minimap_23.1.0_Fabric_1.19.3.jar
50. YetAnotherConfigLib-2.2.0.jar
51. youre-in-grave-danger-1.5.1.jar

</details>

<br>

![Screenshot 1](https://media.discordapp.net/attachments/546804787677757503/1076970696594432020/2023-02-19_21.51.23.png?width=960&height=540)
![Screenshot 2](https://media.discordapp.net/attachments/546804787677757503/1076970717553365173/2023-02-19_21.52.43.png?width=960&height=540)

**Comment by TelepathicGrunt** [comment]
Does it go back to normal if you restart client or do F3+T? Have you tested with Bumblezone alone in a separate new world to rule out other mods?

**Comment by TelepathicGrunt** [comment]
Currently looks fine to me in 1.19.3 fabric with latest version of Bumblezone (v6.6.7) and even with sodium on.
![image](https://user-images.githubusercontent.com/40846040/219978651-7f3f5818-4558-4bcd-a4ea-998106cff961.png)

If Bumblezone alone works for you, then it is likely a mod conflict

**Comment by TelepathicGrunt** [comment]
I added all the mods you listed in the client mod list and I have no issue in single player. I guess update all the mods to latest versions like I did and see if it still persists. Otherwise, I got no lead to go on
![image](https://user-images.githubusercontent.com/40846040/219979194-e331c38d-60d2-4911-9ff5-4ab95acc18bd.png)

**Comment by TelepathicGrunt** [comment]
Any news on this? Is this issue still occurring even after updating all your mods? (I also pushed a new Bumblezone update that might help this but not sure as I don't have a reproduction case for this)

**Comment by maciejkrol18** [comment]
The issue seems to be with Sodium. After removing all of my mods and keeping only the bumblezone and required libraries, everything worked fine. But after i added Sodium, the issue came back.

I am using latest versions of both Sodium and The Bumblezone. I tried tweaking all available Sodium settings but that didn't do anything. Screenshots were taken in a newly generated world in singleplayer

![bumblezone screenshot](https://media.discordapp.net/attachments/546804787677757503/1079359999479914556/2023-02-26_12.11.10.png?width=1202&height=676)

Here's all of the files in my mods directory
![mod files screenshot](https://media.discordapp.net/attachments/546804787677757503/1079359321646841938/image.png)

**Comment by TelepathicGrunt** [comment]
Ah I found the issue, you're missing Indium. Without Indium, Sodium will break many mod's rendering that relies on Fabric API. Indium fixes that and adds a lot of the Fabric API support back into Sodium. Once you put on Indium and see the issue a resolved, I'll close this report and list Indium as an optional dependency on Curseforge/Modrinth. 

A Friend even tested Fabric API's test mod for Baked Models and that is also broken when running Sodium alone so Sodium is the main cause.
![image](https://user-images.githubusercontent.com/40846040/221410192-468c1982-40b3-4cdc-96dc-6e3d0d683a3d.png)

**Comment by maciejkrol18** [comment]
Indium fixes the problem
