### ISSUE TITLE
1.19.2 Bumblezone crashing when Biome Makeover Moth spawns

### ISSUE THREAD

**Issue by adamsbeanie** [TelepathicGrunt/Bumblezone#210]
Yeah, pretty self-explanatory in the title, basically I enter the dimension and I can wander around for a bit, then randomly it crashes, not sure why. I'm running the bumblezone on the 1.19.2 BetterMC Fabric edition modpack, I'm not sure if this is some mod compatibility issue or what, so here's a crash report and a mcpaste

[crash-2023-02-21_14.00.17-server.txt](https://github.com/TelepathicGrunt/Bumblezone/files/10794670/crash-2023-02-21_14.00.17-server.txt)

https://mcpaste.io/25ba0f6d0858d3a7

**Comment by TelepathicGrunt** [comment]
I'm guessing you're playing Better Minecraft which hasn't yet updated. 

The short summary is, this is not a Bumblezone issue. It is a Biome Makeover issue which has a PR here to fix the issue on their end: https://github.com/Lemonszz/Biome-Makeover/pull/202

The issue only started appearing more often once Better Minecraft updated/added C2ME which makes the Biome Makeover's unsafe code be more likely to break: https://github.com/RelativityMC/C2ME-fabric/issues/197

The solution here is to either update Bumblezone where I removed the Biome Makeover Moth from the tag of entities that can spawn in Bumblezone's hanging Gardens structure. 

If you cannot update, put this datapack into your world save's datapack folder and it'll disable the moth from the structure. 
[bumblezone_no_biome_makeover_moth.zip](https://github.com/TelepathicGrunt/Bumblezone/files/10795595/bumblezone_no_biome_makeover_moth.zip)

**Comment by adamsbeanie** [comment]
Awesome, thanks so much!!!

**Comment by TelepathicGrunt** [comment]
Reopening so people can see this issue report better. Will keep open until Better Minecraft/Medieval Minecraft updates finally

**Comment by TelepathicGrunt** [comment]
The lunarpixel modpacks have finally updated so people experiencing this issue should finally disappear
