### ISSUE TITLE
[1.16.3] Incompatibility with Biomes O Plenty

### ISSUE THREAD

**Issue by Inpaladin** [TelepathicGrunt/Bumblezone#22]
Saving and loading a world with the BOP world type cases it to freeze at "reading world data".  Checking the multimc log and the first thing I notice within a wall of errors is "[m[33m[21:04:51] [Render thread/WARN] [biomesoplenty/]: Failed to load save."  I hope that the log can give better information/insight on what's happening.  I went though every mod on my modlist 10 at a time, testing in between disabling mods to see if the issue was still present, and managed to find the culprit, that being this mod. 

latest.log
https://pastebin.com/Jg45GpjY

**Comment by TelepathicGrunt** [comment]
Actually, you seem to have optifine on and I am assuming you have shaders on as well. Optifine with shaders breaks biome mods including The Bumblezone and Biomes o Plenty. https://github.com/sp614x/optifine/issues/4880

My suggestion would be to remove optifine tbh.

let me know if the crash still occurs with optifine off. If it is still crash, try putting on [1.4.3 Blame](https://www.curseforge.com/minecraft/mc-mods/blame/files/3076452) and then give me the latest.log after you get the crash while Blame is on. That would help me more with what's going on and if it is related to: https://github.com/TelepathicGrunt/Bumblezone/issues/20

**Comment by Inpaladin** [comment]
> Actually, you seem to have optifine on and I am assuming you have shaders on as well. Optifine with shaders breaks biome mods including The Bumblezone and Biomes o Plenty. [sp614x/optifine#4880](https://github.com/sp614x/optifine/issues/4880)
> 
> My suggestion would be to remove optifine tbh.
> 
> let me know if the crash still occurs with optifine off. If it is still crash, try putting on [1.4.3 Blame](https://www.curseforge.com/minecraft/mc-mods/blame/files/3076452) and then give me the latest.log after you get the crash while Blame is on. That would help me more with what's going on and if it is related to: #20

I don't use shaders on and worlds load fine without bop installed.

**Comment by Inpaladin** [comment]
I'll try it with optifine disabled though

**Comment by Inpaladin** [comment]
https://pastebin.com/Vh8YgXRs
here's the log with every mod disabled except for biomes o plenty and the bumblezone, after the same error happening again.  I'm not sure about with shaders but optifine seems to absolutely be compatible with this mod and not the culprit in this situation.

**Comment by TelepathicGrunt** [comment]
Dang so it does seem to be a repeat of this issue. https://github.com/TelepathicGrunt/Bumblezone/issues/20
lets move over to there instead just so the issue reports are consolidated. Yeah, thank you for reaching out to me! Can you state all the mods you had on that issue report? I have someone else's mod list and I can compared the two to see which mod could be breaking Bumblezone by removing it's biomes from the biome registry

**Comment by Inpaladin** [comment]
I pretty much narrowed it down to just bop and this mod, I noticed the "[biomesoplenty/]: Failed to load save." in the log and basically went disabling mods in batches of 10, starting from the top and avoiding removing library mods.  Because The Bumblezone has the "The" before it's name in the jar it was one of the last mods I disabled in testing.  Like I said, I did run the pack with everything but the bumblezone and bop disabled and the issue persisted, and I'm currently working on the pack with every other mod enabled and just the bumblezone disabled and haven't encountered the issue since.  Hope that helps!

**Comment by Inpaladin** [comment]
apologies for not getting back to you sooner.

**Comment by TelepathicGrunt** [comment]
Ah no problem. I did find it is most likely related to this issue on BoP. https://github.com/Glitchfiend/BiomesOPlenty/issues/1704

Basically BoP will break any dimension mod or datapack that uses dimensiontype json files for their dimensions. Hopefully BoP will fix this soon!

**Comment by lulabyte** [comment]
Just wanted to add to the pile I'm having this same issue. I can load my world with BOP once, save and exit. But when I try to reload it gets hung up on "Reading World Data". When I remove BOP it loads again.

Thank you for all your work, on the mod and the bugs. I'm sure it's a trip!

**Comment by Inpaladin** [comment]
yeah I can 100% confirm that it's an issue on BOP's end, I tested it with other dimension mods and got the exact same issue.
