### ISSUE TITLE
Bee Queen Color Trades can Uptrade to BotanyPotTiers Pots

### ISSUE THREAD

**Issue by BluMasc** [TelepathicGrunt/Bumblezone#227]
The Queen bee can trade a normal botany pot from botany pots into a higher tiered botany pot from the Botnay Pot Tiers mod.

**Comment by TelepathicGrunt** [comment]
What’s the difference between the pots? Also, I used the basic pots tag from that mod so it should only be basic pots unless they messed up and added non-basic pots to the tag https://github.com/TelepathicGrunt/Bumblezone/blob/88db771f9d831b0c9ead83bb5fd7e96cf8a528af/common/src/main/resources/data/the_bumblezone/bz_bee_queen_trades/randomizer/modded/botanypots_basic_botany_pots.json#L5

**Comment by TelepathicGrunt** [comment]
Issue is not on Bumblezone’s end. It’s the Tier mod adding non-basic pots to the basic pot tag. They need to undo that

**Comment by BluMasc** [comment]
ok, then i'll write them. Thanks for the help!

**Comment by TelepathicGrunt** [comment]
I already made an issue report to them lol. Here’s the issue report https://github.com/starforcraft/Botany-Pots-Tiers/issues/19

**Comment by TelepathicGrunt** [comment]
Looks like they fixed the issue now!

**Comment by TelepathicGrunt** [comment]
Looks like they fixed the issue now!
