### ISSUE TITLE
Crystalline Flower shows weird enchantments

### ISSUE THREAD

**Issue by Mewriel** [TelepathicGrunt/Bumblezone#228]
Hello,
I have noticed that the crystalline flower shows none or irregular enchantments when I put them on a book. For Rank 6 flower the following enchantments do not work: Wild Rage III, Weakening III, Water Protection IV, Posture Breaker III, Curse of Vanishing I, Unbreaking III, Thundering III, Thorns III, Temptation I, Tempo Theft III, Swirling III, Swiftfooted III, Sweeping Edge III, Surprise Gift III, Sunfire III, Stunning III, Stagger III, Stable Footing I and Splitting I. 

Some of them work at flower rank 4 and lower or enchantment level lower. These were attempted and observed on a multiplayer server.

I tried them on a solo world too. The rank 6 flower showed random enchantments for the ones I have written above. For example Unreaking III gives me Sunfire V and so on. 
![image](https://user-images.githubusercontent.com/128651570/227061404-c0a095f1-f09a-41d4-87e7-33ac0ea681d5.png)
Rank 5 was a bit buggy too and Rank 4 and lower seemed fine.

**Comment by TelepathicGrunt** [comment]
@Mewriel What Minecraft version are you playing on? Are you on Forge, Fabric, or Quilt? And latest version of Bumblezone right?

And lastly, can you give me link to modpack or list of mods on?

**Comment by TelepathicGrunt** [comment]
Currently with latest Bumblezone alone on 1.19.2 Forge, I am not seeing the issue. Selected enchantment always shows up on book when hovering over book. Might be incompat with another mod but need modpack and info to even begin to troubleshoot

![image](https://user-images.githubusercontent.com/40846040/227086743-d80a1aef-0ee3-4a98-9290-e6516e8e18c1.png)

**Comment by jmadarg** [comment]
Hi!
Mewriel is playing on CDU's server, running the latest MMC1 [Fabric] version. They first reported this to me but had no time to test it my self or opening an issue.

**Comment by TelepathicGrunt** [comment]
I'm not having the issue with the modpack on and in single player. Looks like by default, MMC1 has 148 enchantments available when at max tier Crystalline Flower so this isn't a case of data size being too large for network.
![image](https://user-images.githubusercontent.com/40846040/227190499-570be629-e8de-4554-9532-423fb6478045.png)

@Mewriel Did you add any extra mod on that is not in MMC1? Or did you edit any config to try and disable some mod's enchantments?

**Comment by Mewriel** [comment]
@TelepathicGrunt No additional mods, but the modpack as is. Didn´t edit anything either.

**Comment by TelepathicGrunt** [comment]
Got issue to reproduce but only with me connecting to a dedicated server running MMC1. The server is not locking onto the correct selected enchantment that user clicked on. Will start digging into code. (Left is client. Right is server)
![image](https://user-images.githubusercontent.com/40846040/227403047-b41489a9-6327-44af-a0af-00995d66ff1a.png)

**Comment by Mewriel** [comment]
Thank you very much for your help! I hope it´s not too much of a trouble.

**Comment by TelepathicGrunt** [comment]
done in v6.7.0 which is now released
