### ISSUE TITLE
Honey Crystal creation replaces waterlogged blocks

### ISSUE THREAD

**Issue by WenXin20** [TelepathicGrunt/Bumblezone#235]
```
Forge v43.2.7
Minecraft v1.19.2
Bumblezone v6.7.5
```

I discovered that waterlogging a block next to Royal Jelly Fluid replaces the waterlogged block with Honey Crystal.

**Comment by TelepathicGrunt** [comment]
What specifically was the waterlogged block? Need to know as if it is a block without hitboxes, it can be problematic blocking

**Comment by WenXin20** [comment]
I tried it with a slab, but it happens with any block

**Comment by TelepathicGrunt** [comment]
Fixed now in v6.7.6
