### ISSUE TITLE
Water spreads infinitely on top of sugar water

### ISSUE THREAD

**Issue by Wairpre** [TelepathicGrunt/Bumblezone#238]
Placing a water source block on top of sugar water source blocks creates an infinitely spreading layer of water sources.

**Comment by TelepathicGrunt** [comment]
What Mc version? What modloader? What Bumblezone version? Do you have a pic of what happens?

**Comment by Wairpre** [comment]
It's Fabric 1.19.2.

https://user-images.githubusercontent.com/56366921/232678062-fa16b295-e304-4414-9f8a-db98ea787f1b.mp4

**Comment by TelepathicGrunt** [comment]
Fixed now in v6.7.11!
