### ISSUE TITLE
"Flooding the housing market" advancement doesn't complete

### ISSUE THREAD

**Issue by 630R63** [TelepathicGrunt/Bumblezone#243]
Playing the "Better Minecraft" modpack right now and I tried to do the Bumblezone advancements. 

The modpack is using the version 6.7.8

At first I crafted 46 beehives and that didn't count towards the advancement. 
Then I thought of placing them down and picking them up. That also didn't count.

Then I went and gathered a bunch of beehive beeswax planks from the top of the dimension and crafted 37 bee nests.
That also didn't count toward the advancement.

Am I doing something wrong? Or is the advancement not detecting them in my inventory?

![image](https://user-images.githubusercontent.com/6078866/235429545-e911ea75-3c67-48d5-bc61-e92ee6cfb50f.png)

![image](https://user-images.githubusercontent.com/6078866/235429683-94bb5489-78e9-4cab-9595-9fe1c693e584.png)

**Comment by TelepathicGrunt** [comment]
Works for me with bumblezone alone
![image](https://user-images.githubusercontent.com/40846040/235442472-8e1208ed-3077-45cf-a195-e5bd75d8938d.png)

What specifically are you using to craft the beehives? I test with Crafting Table.

**Comment by TelepathicGrunt** [comment]
Tested with Better MC [FABRIC] 1.19.2 v17.5 HF.zip and it works there for me
![image](https://user-images.githubusercontent.com/40846040/235443732-7a9405e9-e66c-4df2-8f2c-42da74e1aec0.png)

Should work for any crafting method or recipe that has a Beehive or Bee Nest as result. Only way it won't work is if you're using some sort of custom crafting system that is not using a ResultSlot or they forgot to fire checkTakeAchievements method upon taking items out of their custom system's ResultSlot.

Hence why I need to know exactly how are you crafting said blocks or what Crafting screen you're using

**Comment by 630R63** [comment]
Oh, you are right!

Using a crafting table gave me the advancement:

![image](https://user-images.githubusercontent.com/6078866/235546661-c10b7ec2-ad7b-4c8a-9d36-b79430c87754.png)

Before, I was using the crafting terminal from "Tom's Simple Storage" mod and that didn't count

**Comment by 630R63** [comment]
[Issue ](https://github.com/tom5454/Toms-Storage/issues/235)opened on the mod's repository
