### ISSUE TITLE
[1.19.2] Latest version of JEED recipe handler incompatability

### ISSUE THREAD

**Issue by DelviousCrafts** [TelepathicGrunt/Bumblezone#244]
JEED version 2.0.1 has updated the recipe handler to have the effect line be a string of the effect only rather than an object pointing to the ID and then the effect string. This causes the recipe integrations currently in the Bumblezone to stop functioning.

Versions:
- Minecraft: 1.19.2
- Forge: 43.2.10
- The Bumblezone: 6.7.16
- JEED: 2.0.1

**Comment by TelepathicGrunt** [comment]
Fixed in v6.7.17 Bumblezone.
