### ISSUE TITLE
how to get royal jelly

### ISSUE THREAD

**Issue by Pepige0n** [TelepathicGrunt/Bumblezone#247]
i can;t find anywhere on how to get royal jelly or do you get just 1 bucket per throne room?

**Comment by TelepathicGrunt** [comment]
Complete The Queen Desire advancements to get Royal Jelly Bottles for more. You start the advancements by trading with Bee Queen. When done the advancement line, you can reset it at the Queen to redo it. See my wiki page for more info https://github.com/TelepathicGrunt/Bumblezone/wiki
