### ISSUE TITLE
[Forge 1.19.2] Crash with Canary 0.2.3

### ISSUE THREAD

**Issue by Lykrast** [TelepathicGrunt/Bumblezone#250]
When joining a world, with both those mods, the game crashes (well before it just hung up and the MultiMC log said there was an exception and the game just stopped doing anything, but then I tried to reproduce to get a proper log and it actually crashed).

I have a lot of other mods in this instance, but downgrading Canary to `canary-mc1.19.2-0.2.0` (and no other mods change) fixed the issue, so I'm guessing it's the likely culprit. Log seems to imply it's a mixin error (which is why I suspected Canary in the first place since I recently updated it and it sounded like a mixin mod).

Truncated log (excluded everything before joining world because it's 5k lines of other mods not having their jsons correctly, and the mixin errors don't pop in until world join): https://gist.github.com/Lykrast/552c131e4e3204b552e60e2aa0d77a4e

* Forge 43.2.3
* `the_bumblezone_forge-6.7.19+1.19.2`
* `canary-mc1.19.2-0.2.3`

**Comment by TelepathicGrunt** [comment]
https://github.com/AbdElAziz333/Canary/blob/0a496981c68265ed02c8bd3bbacb7db95c2663d4/src/main/java/com/abdelaziz/canary/mixin/calc/if_else/ai/evaluator/FlyNodeEvaluatorMixin.java#L20

Figures. overwrite mixin goes brr on their end. My mixin is safe. 
https://github.com/TelepathicGrunt/Bumblezone/blob/1.19.2-Forge/src/main/java/com/telepathicgrunt/the_bumblezone/mixin/entities/FlyNodeEvaluatorMixin.java

They need to remove that overwrite mixin and do something safer as I cannot work around mods that completely nukes and replaces entire methods without care for other mods.

**Comment by TelepathicGrunt** [comment]
@Lykrast My suggestion to you is remove Canary. They do not appear to be a safe mod. There's also other concerning crashes on their GitHub so there's a large incompatibility problem with the mod

**Comment by AbdElAziz333** [comment]
For now, add this line `mixin.calc.if_else.ai.evaluator=false` to canary.properties in the config dir, until i release a fix.

**Comment by AbdElAziz333** [comment]
Now, should be fixed in the new updated versions.
[1.19.4](https://legacy.curseforge.com/minecraft/mc-mods/canary/files/4551267) - [1.19.3](https://legacy.curseforge.com/minecraft/mc-mods/canary/files/4551265) - [1.19.2](https://legacy.curseforge.com/minecraft/mc-mods/canary/files/4551264) - [1.18.2](https://legacy.curseforge.com/minecraft/mc-mods/canary/files/4551263)
I hope you have a good day!

**Comment by TelepathicGrunt** [comment]
Thank you, Will close this report now
