### ISSUE TITLE
Game crashing with Bumblezone installed

### ISSUE THREAD

**Issue by Strongamov** [TelepathicGrunt/Bumblezone#251]
Hey, sorry if this is not the correct place to post this, but my modded game
crashes as soon it's done loading a world. I don't know much about how to read crash logs so I sadly
can't figure the issue out on my own, but looking at it it seems like the Bumblezone mod is the one encountering an error
here. It previously worked, but apparently, Bumblezone isn't compatible with one of the mods i added.
[crash-2023-05-29_15.34.15-server.txt](https://github.com/TelepathicGrunt/Bumblezone/files/11592215/crash-2023-05-29_15.34.15-server.txt)

**Comment by TelepathicGrunt** [comment]
Does this always crash every time you try entering world?

**Comment by Strongamov** [comment]
Most of the time it does. Rarely the world finishes loading so you can actually see the environment, but then it crashes after 1-2 seconds.

**Comment by TelepathicGrunt** [comment]
Please give this jar a test (Unzip it as the jar is inside). See if this fixes the crash. I might be using the wrong event after I ported from 1.19.2 to 1.19.3 but only on the Forge side
[the_bumblezone-6.7.20-beta+1.19.4-forge.zip](https://github.com/TelepathicGrunt/Bumblezone/files/11593101/the_bumblezone-6.7.20-beta%2B1.19.4-forge.zip)

**Comment by Strongamov** [comment]
Yep it seems that was the problem, i tried generating a few worlds and flew around a bit and so
far no crashes! Thank you very much!

**Comment by TelepathicGrunt** [comment]
Fixed in now 6.7.20 which is uploaded to curseforge and modrinth
