### ISSUE TITLE
Most blocks not rendering, Prominence I modpack, Forge edition

### ISSUE THREAD

**Issue by IKEACherry** [TelepathicGrunt/Bumblezone#257]
![Java-runtime-gamma Screenshot 2023 07 04 - 11 34 41 05](https://github.com/TelepathicGrunt/Bumblezone/assets/112356527/50c4b790-12fd-42b5-aa85-609897a60155)
Can't reset texture packs because the game will crash ("Cannot convert intercardinal direction to vanilla direction")

Also can crash after some time in the dimension

>  -- Head --
> Thread: Render thread
> Stacktrace:
> 	at net.minecraft.client.particle.TerrainParticle.m_5970_(TerrainParticle.java:48) ~[client-1.19.2-20220805.130853-srg.jar%23957!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:mixins.oculus.fantastic.json:MixinTerrainParticle,pl:mixin:A,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.particle.SingleQuadParticle.m_5744_(SingleQuadParticle.java:567) ~[client-1.19.2-20220805.130853-srg.jar%23957!/:?] {re:mixin,re:classloading,pl:mixin:APP:rubidium.mixins.json:features.particle.fast_render.MixinBillboardParticle,pl:mixin:A}
> 	at net.minecraft.client.particle.TextureSheetParticle.m_5744_(TextureSheetParticle.java:538) ~[client-1.19.2-20220805.130853-srg.jar%23957!/:?] {re:mixin,re:classloading,pl:mixin:APP:rubidium.mixins.json:features.texture_tracking.MixinSpriteBillboardParticle,pl:mixin:A}
> 	at net.minecraft.client.particle.ParticleEngine.render(ParticleEngine.java:406) ~[client-1.19.2-20220805.130853-srg.jar%23957!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.particle.ParticleEngine.m_107336_(ParticleEngine.java:379) ~[client-1.19.2-20220805.130853-srg.jar%23957!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.renderer.LevelRenderer.handler$bee000$iris$renderOpaqueParticles(LevelRenderer.java:9634) ~[client-1.19.2-20220805.130853-srg.jar%23957!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:twilightforest:render,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:render,pl:mixin:A,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1173) ~[client-1.19.2-20220805.130853-srg.jar%23957!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:twilightforest:render,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:render,pl:mixin:A,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1068) ~[client-1.19.2-20220805.130853-srg.jar%23957!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
> -- Particle being rendered --
> Details:
> 	Particle: TerrainParticle, Pos (224.69999998807907,48.0,181.69999998807907), RGBA (0.6,0.6,0.6,1.0), Age 0
> 	Particle Type: TERRAIN_SHEET
> Stacktrace:
> 	at net.minecraft.client.particle.ParticleEngine.render(ParticleEngine.java:406) ~[client-1.19.2-20220805.130853-srg.jar%23957!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.particle.ParticleEngine.m_107336_(ParticleEngine.java:379) ~[client-1.19.2-20220805.130853-srg.jar%23957!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.renderer.LevelRenderer.handler$bee000$iris$renderOpaqueParticles(LevelRenderer.java:9634) ~[client-1.19.2-20220805.130853-srg.jar%23957!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:twilightforest:render,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:render,pl:mixin:A,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1173) ~[client-1.19.2-20220805.130853-srg.jar%23957!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:twilightforest:render,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:render,pl:mixin:A,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1068) ~[client-1.19.2-20220805.130853-srg.jar%23957!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:840) ~[client-1.19.2-20220805.130853-srg.jar%23957!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1115) ~[client-1.19.2-20220805.130853-srg.jar%23957!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,pl:mixin:A,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23957!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,pl:mixin:A,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23957!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23957!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
> 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
> 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
> 	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.6.jar%23101!/:?] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2388!/:?] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2388!/:?] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2388!/:?] {}
> 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2388!/:?] {}
> 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2388!/:?] {}
> 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2388!/:?] {}
> 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2388!/:?] {}
> 	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}

"The game crashed whilst rendering particle
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.client.renderer.texture.TextureAtlasSprite.m_118367_(double)" because "this.f_108321_" is null"

**Comment by TelepathicGrunt** [comment]
@IKEACherry Update bumblezone. The prominence modpack has not updated despite the block rendering issue already has been fixed for a long time now. in fact, poke the lunar pixel team to update the pack already cause I am tired of getting these reports lol

**Comment by IKEACherry** [comment]
ah, alright
thanks for the response, i don't know if they will update the pack considering they seem to have Prominence 2 up, which may be their main focus
