### ISSUE TITLE
Forge 34.1.31 - New Forge, new problems

### ISSUE THREAD

**Issue by bessiq** [TelepathicGrunt/Bumblezone#26]
Doesn't seem to care much for your zone of bumbling. Could be a Forge goof/mod-breaking update, but thought I'd let you know. 

crash report: https://gist.github.com/bessiq/00851013ddb2ddb7a8932f7caa99bb42

**Comment by TelepathicGrunt** [comment]
Yeha this is due to a breaking change caused by forge. You gotta downgrade to .25 until I can get some friends to help convert my vanilla registration to forge registration.

**Comment by TelepathicGrunt** [comment]
v2.2.1 is out and should fix this!
