### ISSUE TITLE
remove quilted fabric api dependency

### ISSUE THREAD

**Issue by akai-hana** [TelepathicGrunt/Bumblezone#260]
![image](https://github.com/TelepathicGrunt/Bumblezone/assets/55887501/1d971745-7416-4f0d-b98d-b4fc77a54295)

as you can see on the image above, packwiz asks for this quilt dependency, even though I'm trying to install the fabric version. this is inconvenient, as it breaks packwiz's mod auto-updating, and I'm forced to pin this mod to not receive updates.

possible solutions, would be to simply remove this dependency, or separate the quilt and fabric versions of this mod into two different modrinth pages.

thank you for paying so much attention to this project. it receives updates almost weekly. much kudos.

**Comment by TelepathicGrunt** [comment]
fixed modrinth page
