### ISSUE TITLE
Quest line not showing up 

### ISSUE THREAD

**Issue by molzatron** [TelepathicGrunt/Bumblezone#261]
Hi I have gone into world and bumblezone, explored etc, found the queen and did all that, got the notification that the quest line was unlocked where i can get rewards but i did not have a quest line unlocked, help?

**Comment by TelepathicGrunt** [comment]
I need more info. If you open you advancement window and go to Bumblezone tab, you should see the advancement line for Queen's Desire in there. It's not a quest like FTB Quest. it's a chain of advancements.

If you are talking about FTB Quests for a modpack, you need to talk to the modpack maker as quests are not made by mods. They are put together by modpack makers

**Comment by TelepathicGrunt** [comment]
The advancement line looks like this with the Bee Queen Spawn Egg as icon 
![image](https://github.com/TelepathicGrunt/Bumblezone/assets/40846040/a7a16741-e79b-4acb-a51a-4e2f10c5da93)

**Comment by TelepathicGrunt** [comment]
Closing as it has been a week and no additional info provided. I am assuming the confusion was between quests vs advancements
