### ISSUE TITLE
Comb Cutter Enchant Not Working

### ISSUE THREAD

**Issue by snozzzz** [TelepathicGrunt/Bumblezone#262]
Using with RAD2, though I don't think its a compatibility issue? I don't imagine anything else changes the mining speed of honeycomb.
I tried it on both my sword and my shears and neither of them cut honeycomb blocks any faster than my fist.

**Comment by TelepathicGrunt** [comment]
What Mc version and mod version are you playing on

**Comment by snozzzz** [comment]
> 

RAD2 1.5, so 1.16.5 and bumblezone 3.2.1

**Comment by TelepathicGrunt** [comment]
That probably is why. It may be broken in 1.16.5 which is no longer supported by me. Sorry. Currently I am supporting only 1.19.2 while working to get onto 1.20.1
