### ISSUE TITLE
1.20.1 - Crash with Sinytra Connector mod

### ISSUE THREAD

**Issue by TelepathicGrunt** [TelepathicGrunt/Bumblezone#265]
Log from user: https://pastebin.com/raw/hnHiSkaB

The way this code works I have is when the forge module runs, I mixin my own ItemExtension class and override getEquipmentSlot and call my own bz$getEquipmentSlot so I can hook up my bz$getEquipmentSlot differently for each modloader.
https://github.com/TelepathicGrunt/Bumblezone/blob/96089be3fb5b5595555a1d2540aac8fda0ab2f8b/forge/src/main/java/com/telepathicgrunt/the_bumblezone/mixins/forge/item/ItemExtensionMixin.java#L56

For Stinger Spear, I implement the interface but don't override  bz$getEquipmentSlot 
https://github.com/TelepathicGrunt/Bumblezone/blob/96089be3fb5b5595555a1d2540aac8fda0ab2f8b/common/src/main/java/com/telepathicgrunt/the_bumblezone/items/StingerSpearItem.java#L36

The ItemExtension interface exists in common module and does not define getEquipmentSlot itself
https://github.com/TelepathicGrunt/Bumblezone/blob/1.20-Arch/common/src/main/java/com/telepathicgrunt/the_bumblezone/platform/ItemExtension.java#L13 

The issue is Syntra Connector seems to be injecting their own getEquipmentSlot method into my classes and that causes conflict

**Comment by TelepathicGrunt** [comment]
fixed in v7.0.4

**Comment by Su5eD** [comment]
Fixed on my end in FFAPI 0.88.1+1.9.15+1.20.1
