### ISSUE TITLE
[Fabric 1.20.1] Entire server crashed when placing Fire Prot Potion Candle.

### ISSUE THREAD

**Issue by MorphlingUnderscore** [TelepathicGrunt/Bumblezone#269]
Afterwards, when the server was back online, picking the candle back up duped it and then crashed the player's game. Strangely, the initial crash did not log an error in the server, so I have no error message to link.

**Comment by TelepathicGrunt** [comment]
After the server crashes, open up the log folder above the mods folder and get me the latest.log file. Do not start up the server after the crash as it will overwrite the latest.log folder. This file will say what the crash is to me

**Comment by TelepathicGrunt** [comment]
Oh think I might see what the issue is

**Comment by TelepathicGrunt** [comment]
v7.0.6 should fix this. Thank you for reporting this! @MorphlingUnderscore 

Update is released and should be publicly downloadable in a few minutes
