### ISSUE TITLE
[Fabric 1.20.1] Game crashes when clicking an option in the briefcase without having the required item

### ISSUE THREAD

**Issue by ImpSpy2** [TelepathicGrunt/Bumblezone#273]
[crash-2023-09-29_21.02.04-client.txt](https://github.com/TelepathicGrunt/Bumblezone/files/12771805/crash-2023-09-29_21.02.04-client.txt)

**Comment by TelepathicGrunt** [comment]
Should be now fixed in v7.0.10 Bumblezone
