### ISSUE TITLE
[Fabric 1.19.2] Honey Compass - Throne Pillar bug

### ISSUE THREAD

**Issue by Dzsonzii** [TelepathicGrunt/Bumblezone#274]
We are playing on the Medieval MC - MM1 modpack ([here](https://www.curseforge.com/minecraft/modpacks/medieval-mc-fabric-mmc1)), and the compass does weird things. The video of the issue can be seen [here](https://www.youtube.com/watch?v=qaGqBzP-nuQ). Is this supposed to do this, or it's just a bug with our world?

**Comment by TelepathicGrunt** [comment]
It did not find the structure or lost the link to the async search system (which can happen if compass is picked up too fast from block loot). Right click air and it’ll retry to locate it. The tooltip for the compass should say this

**Comment by Dzsonzii** [comment]
we tried it multiple times, with more than one compass. I located the structure with the in-game locate command, and when I'm right beside it, it still just spins like a madman.

**Comment by TelepathicGrunt** [comment]
works for me with the modpack
https://github.com/TelepathicGrunt/Bumblezone/assets/40846040/ff67d46d-94c5-437b-8f98-694de78f7481

**Comment by TelepathicGrunt** [comment]
Next time you find a Throne Pillar compass in a Honey Cocoon, try leaving it alone in the cocoon and see if it finishes the search then. Otherwise, no idea what is going on in your world as the compass just runs the locate command basically under the hood asynchronously and then updates the itemstack when done

**Comment by TelepathicGrunt** [comment]
Closing as no more info over 2 weeks. 1.20.1 Bumblezone has adjusted Honey Compass code to try and keep the linkage between the structure search code and the Honey Compass itself a bit better.

**Comment by TelepathicGrunt** [comment]
The honey compass locating improvements is now backported to 1.19.2 at v6.7.39 Bumblezone
