### ISSUE TITLE
[Feature Request] Add pirate (for example illager) to the pirate ship

### ISSUE THREAD

**Issue by zeid0ne** [TelepathicGrunt/Bumblezone#277]
First of all sorry if it's not the good place to do feature request.

This mod is great !

I think it could be better if the pirate ship had some pillagers in it, maybe with some lore clues about how they find the bumblezone (the why is already perfectly handled cause we understand fast that it was to capture bee and their stinger).

Also, some of them should be protected from bee or from taking aggro from them. By doing so, the player could find a battle, and could join it before all pillager beeing killed.

Thanks

**Comment by TelepathicGrunt** [comment]
The pirate ship has pirate bees actually. The 3 bees that spawn in the pirate ship has pirate names lol. You can datapack replace the pirate ship nbt to have pillagers instead if you wanted. 

If another mod allows for pirate hats on bees that render properly, I can add mod compat to spawn the pirate ship bees with those hats

**Comment by zeid0ne** [comment]
oh ! i thought they were prisonners !

I'll take a look

thanks for the fast answer !
