### ISSUE TITLE
SentryWatcherEntity cannot be cast to Mob Minecraft forge 1.20.1

### ISSUE THREAD

**Issue by GoldenKittenPlays** [TelepathicGrunt/Bumblezone#281]
I know that this entity is a non living entity as seen in your github but for some reason it is being casted to that by something and I am not really sure. I am currently running a server using the modpack: https://www.curseforge.com/minecraft/modpacks/prominence-2-forge 

Here is the log that I get:
[crash-2023-10-13_19.32.38-server.txt](https://github.com/TelepathicGrunt/Bumblezone/files/12901435/crash-2023-10-13_19.32.38-server.txt)

This is also not a one time bug it happened twice today here is the other log:
[crash-2023-10-13_19.22.27-server.txt](https://github.com/TelepathicGrunt/Bumblezone/files/12901437/crash-2023-10-13_19.22.27-server.txt)

**Comment by TelepathicGrunt** [comment]
The issue is minecolonies. I already reported this issue to them. Please update minecolonies and see if the issue is fixed. If not, you’ll have to wait for them to update and fix their casting

**Comment by GoldenKittenPlays** [comment]
> The issue is minecolonies. I already reported this issue to them. Please update minecolonies and see if the issue is fixed. If not, you’ll have to wait for them to update and fix their casting

Thank you for letting me know. I did see mine colonies in the log but was not completely sure. MineColonies is always really buggy.
