### ISSUE TITLE
[Quilt 1.20.1] crashes whenever i open a honey cocoon with lootr installed

### ISSUE THREAD

**Issue by glittermutt** [TelepathicGrunt/Bumblezone#282]
log and crash report attached :(
[crash-2023-10-14_20.22.45-server.txt](https://github.com/TelepathicGrunt/Bumblezone/files/12906585/crash-2023-10-14_20.22.45-server.txt)
[latest.log](https://github.com/TelepathicGrunt/Bumblezone/files/12906587/latest.log)

**Comment by TelepathicGrunt** [comment]
resolved now in v7.0.17
