### ISSUE TITLE
Game Crashes at Queen Bee

### ISSUE THREAD

**Issue by DerApfl** [TelepathicGrunt/Bumblezone#285]
So i start the game and as soon as i spawn in i can see for 1 sec and then it crashes. my error : The game crashed whilst rendering entity in world
Error: java.lang.ClassCastException: class com.telepathicgrunt.the_bumblezone.client.rendering.transparentitem.TintedVertexBuilder cannot be cast to class me.jellysquid.mods.sodium.client.render.vertex.VertexBufferWriter (com.telepathicgrunt.the_bumblezone.client.rendering.transparentitem.TintedVertexBuilder and me.jellysquid.mods.sodium.client.render.vertex.VertexBufferWriter are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @52aa2946)

**Comment by TelepathicGrunt** [comment]
Please update sodium. This was fixed in 0.5.0 sodium or newer

**Comment by TelepathicGrunt** [comment]
Closing as issue is likely due to outdated sodium. Poster hasn’t replied over a few days so assuming issue was resolved by updating
