### ISSUE TITLE
[1.16.3]Incompatibility with newer versions of forge.

### ISSUE THREAD

**Issue by Inpaladin** [TelepathicGrunt/Bumblezone#29]
[crash-2020-10-29_19.42.29-fml.txt](https://github.com/TelepathicGrunt/Bumblezone/files/5462683/crash-2020-10-29_19.42.29-fml.txt)
[latest.log](https://github.com/TelepathicGrunt/Bumblezone/files/5462684/latest.log)
latest.log and crash report

**Comment by TelepathicGrunt** [comment]
v2.2.1 is out and should fix this!
