### ISSUE TITLE
[1.19.2] Latest Update 6.7.42 Crashes on Startup With Productive/Resourceful bees

### ISSUE THREAD

**Issue by PhweeDev** [TelepathicGrunt/Bumblezone#294]
Heya,

The latest update crashes on start-up, when I have Resourceful or Productive Bees on.

Here's the report: https://paste.gg/p/anonymous/ff0afadf9b1d4fb0950d7c546d133373

I think in the mods.toml  of Bumblezone the lines are needed for Productive and Resourceful Bees respectively.

    versionRange="[1.19.2-0.10.7.2,)" (<-- Productive)
and
    versionRange="[1.0.0-alpha.21,)" (<-- Resourceful)

**Comment by TelepathicGrunt** [comment]
Please wait till I get home. I can’t do anything right now

**Comment by TelepathicGrunt** [comment]
fixed in v6.7.43
