### ISSUE TITLE
[1.20.1] New Forge Version doesn't support Productive Bees

### ISSUE THREAD

**Issue by MokahTGS** [TelepathicGrunt/Bumblezone#295]
The latest version of Bumblezone doesn't support the latest version of Productive Bees.

Bumblezone 7.0.27+1.20.1 - Forge
Productive Bees 1.20.1 12.2.6

Rolling back to an older version of Bumblezone fixes the issue.

**Comment by aAndrew3030** [comment]
Mod ID: 'productivebees', Requested by: 'the_bumblezone', Expected range: '', Actual version: '1.20.1-12.2.6'

**Comment by TelepathicGrunt** [comment]
Please wait till I get home. I can’t do anything right now

**Comment by TelepathicGrunt** [comment]
Fixed in v7.0.28
