### ISSUE TITLE
shepherd problems

### ISSUE THREAD

**Issue by kaboom24** [TelepathicGrunt/Bumblezone#296]
the wiki says you can trade with the villager but since he does not have a job block you cant trade with him could you fix this he just needs a job block and some custom trades for it

**Comment by TelepathicGrunt** [comment]
There is a loom in the house already. The villager just needs to walk down and it’ll claim the block. I didn’t add custom trades because they don’t seem to persist

**Comment by kaboom24** [comment]
well he never claims the bed or the loom

**Comment by kaboom24** [comment]
could you fix that

**Comment by TelepathicGrunt** [comment]
Look above. I linked a commit that will move the villager to spawn right next to workstation. It claims profession every time I tested. This will be released next Bumblezone update

**Comment by TelepathicGrunt** [comment]
Fixed in v7.0.29
