### ISSUE TITLE
Bumble Zone entering crash(?)

### ISSUE THREAD

**Issue by Ladocterus** [TelepathicGrunt/Bumblezone#300]
I crashed while riding on a beehemoth and trying to ender pearl into the bumblezone.
then crashed every time I try to enter again (even across worlds)
[crash-2023-11-08_17.02.30-server.txt](https://github.com/TelepathicGrunt/Bumblezone/files/13302798/crash-2023-11-08_17.02.30-server.txt)
[crash-2023-11-08_16.47.22-server.txt](https://github.com/TelepathicGrunt/Bumblezone/files/13302799/crash-2023-11-08_16.47.22-server.txt)
(I suspect it's due to mod file corruption, but I currently downgraded from newest version to 7.0.24 to bee safe)
Sorry in advance in posting back to back

**Comment by Ladocterus** [comment]
I was using version 7.0.28 when it crashed

**Comment by TelepathicGrunt** [comment]
`java.lang.NoClassDefFoundError: net/minecraftforge/event/entity/ProjectileImpactEvent$ImpactResult`
Please update Forge. This is an addition to Forge. But using an older Forge version without the Impact Result class, you will get this crash. Try 47.2.0 or newer forge

**Comment by Ladocterus** [comment]
Ah I see, thanks a lot

**Comment by TelepathicGrunt** [comment]
Specifically, the result seems to be added in v47.1.4 so can update to that if you don't want to go all the way to 47.2.0+. Just don't do forge versions between 47.2.0 and 47.1.4 as there were several issues present in those intermediary forge version

**Comment by TelepathicGrunt** [comment]
Just released v7.0.29 that now allows version 47.1.3 Forge again. I reverted the usage of the new projectile hit event result that was added in Forge 47.1.4.
