### ISSUE TITLE
glitch

### ISSUE THREAD

**Issue by kaboom24** [TelepathicGrunt/Bumblezone#302]
alexs caves gloomoths spawn near hanging gardens

**Comment by TelepathicGrunt** [comment]
Not a glitch. I intended this. I define a bunch of bug and small reptile mobs to spawn in hanging gardens when it is first generated. This tag has all the mobs that can spawn
https://github.com/TelepathicGrunt/Bumblezone/blob/1.20-Arch/common/src/main/resources/data/the_bumblezone/tags/entity_types/hanging_garden/initial_spawn_entities.json

gloomoth I added cause I wanted moths and butterflies in the garden for variety too.

**Comment by kaboom24** [comment]
ahh

**Comment by kaboom24** [comment]
okay
