### ISSUE TITLE
Running away from a minigame causes music to persist through dimensions and worlds

### ISSUE THREAD

**Issue by DENOBODY2** [TelepathicGrunt/Bumblezone#307]
When leaving a minigame, the music will persist if you go far away, into another dimension, or even join a different world on the same installation. The only way to stop this is by closing the game.

**Comment by TelepathicGrunt** [comment]
What modloader? What modpack? And which Bumblezone version? And which event or is it all of them? I did some work to prevent music playing forever but if you have a music mod interfering, it could be causing issues so I need more information to try and reproduce the issue you’re seeing

**Comment by DENOBODY2** [comment]
Modloader: Forge
Version: Latest 1.20.1 version
Event: Blue Essence Challenge
I don't think I have any mods that affect music
What happened: I was in creative, I started a blue challenge, I used a command to kill the drowned in the cube which broke the challenge, causing no mobs to spawn but the timer to stay there for a few seconds before disappearing, I broke one of the walls causing it to turn gray, then the essence block in the middle turned gray and the challenge ended but the music kept playing. I went into spectator mode and deloaded the minigame box, the music kept playing, the minigame had definitely ended now. I went into another dimension and the music kept playing, and then I went into a new world and the music kept playing.

**Comment by TelepathicGrunt** [comment]
Just fyi, if you want to leave an event early in creative, just teleport out like /tp ~ ~ ~50

**Comment by TelepathicGrunt** [comment]
Testing with Bumblezone alone with the steps you provided, the kill command is killing the mobs and the essence block spawns more without issue. And finishing the event has the music fade out after a few seconds later no issue
https://github.com/TelepathicGrunt/Bumblezone/assets/40846040/324b3232-24a3-459c-af4d-e5d31d8506b6

I am going to need your modpack to rule out an issue caused by another mod. You can export the modpack and give me the link by dropbox/google drive with links haring on. Or give me download link to modpack if it is already shared online

**Comment by DENOBODY2** [comment]
I'm not at my computer right now so i cannot provide the mods list, but something I forgot to mention was I just realized that i did not attempt to break the essence block. Rather, I accidentally replaced it using setblock, and that is how the essence block turned into a gray barrier. This may be what broke the event.

**Comment by TelepathicGrunt** [comment]
Yeah that will break the entire event. The event is controlled by the Essence Block. Replacing it will cause major issues. I’ll see what I can do but generally, no player should ever be able to replace it. Luckily that shouldn’t be possible in survival

**Comment by TelepathicGrunt** [comment]
Should be resolved now
