### ISSUE TITLE
Sticky Honey Redstone bounds crash

### ISSUE THREAD

**Issue by NielsPilgaard** [TelepathicGrunt/Bumblezone#310]
https://github.com/EnigmaticaModpacks/Enigmatica9/issues/798

> Queen bee causing servers and game to crash

https://gist.github.com/Pixelingot/0ca65a70223de75afab52ca0b9cabf1a

**Comment by TelepathicGrunt** [comment]
will be fixed in v6.8.2
has nothing to do with bee queen. It's sticky honey redstone bounds crashing

**Comment by TelepathicGrunt** [comment]
fixed now
