### ISSUE TITLE
Getting teleported to extremities of the Sanctum room I'm in over and over again

### ISSUE THREAD

**Issue by OzerSkyyy** [TelepathicGrunt/Bumblezone#311]
Impossible to play the sanctums because of this, I get teleported to the very extremity of the room I'm in, I'm at the essence block here, and I can't reach it because I get teleported outwards over and over again.
I tried changing position from the center of the room, for example not being in south east but north east, it still just gets me to the extremity but to the north east, same for other positions.
Now this is the only one I've tried, I'll try to find another one to see if it does the same thing.
1.20.1

**Comment by TelepathicGrunt** [comment]
What modloader and Bumblezone version are you playing? And what modpack are you playing on? Does issue happen if you try with Bumblezone alone and no other mods?

**Comment by TelepathicGrunt** [comment]
Are you playing on Prominence II Forge modpack?

**Comment by TelepathicGrunt** [comment]
Issue is Sound Physic Remastered mod. Disable that mod for now. I have no idea what they are doing to cause this at all.

**Comment by TelepathicGrunt** [comment]
Fixed in v7.1.8 for 1.20.1 and v7.2.6 for 1.20.2
