### ISSUE TITLE
Crash on creating or joining world in versions higher than 7.1.4 (Quilt) (Probably mod compat issue)

### ISSUE THREAD

**Issue by TeslaP09** [TelepathicGrunt/Bumblezone#312]
The game crashes when creating or joining a world (tested with version 7.1.8 Quilt (also with 7.1.6 and 7.1.7, as 7.1.5 doesn't exist on CF)). From my understanding, it has something to do with parsing loot tables. I do have to say that I play a big modpack, but either downgrading this mod to 7.1.4 or lower or removing EMI Loot (Also happens with Just Enough Resources) fixes the issue. Here's the crash report and the log:

[crash-2023-12-03_16.07.23-client.txt](https://github.com/TelepathicGrunt/Bumblezone/files/13539335/crash-2023-12-03_16.07.23-client.txt)
[latest.log](https://github.com/TelepathicGrunt/Bumblezone/files/13539336/latest.log)

**Comment by TelepathicGrunt** [comment]
I think I know what the issue may be.

**Comment by TelepathicGrunt** [comment]
Wish this was reported earlier as I just released updates

**Comment by TelepathicGrunt** [comment]
Try this jar

[the_bumblezone-7.1.9-beta+1.20.1-quilt.zip](https://github.com/TelepathicGrunt/Bumblezone/files/13539384/the_bumblezone-7.1.9-beta%2B1.20.1-quilt.zip)

**Comment by TeslaP09** [comment]
Fixed, tysm <3

**Comment by sleepy-evelyn** [comment]
Well I think I have the same issue lol #313 so i'll use the new jar. Thx Telepathic.
