### ISSUE TITLE
EMI loot recursive loop crash

### ISSUE THREAD

**Issue by sleepy-evelyn** [TelepathicGrunt/Bumblezone#313]
Having an issue with the latest version of the Bumblezone 7.1.8 when creating or loading any existing worlds with the EMI Loot mod installed. It seems to get stuck in a recursive loop trying to load NBT loot data for a specific entity but the crash report is a bit vague so it's difficult to understand where it came from.

I downgraded to 7.1.4 which seemed to be when the entity loot changes where made and it works fine.

**Crash Report**: https://gist.github.com/sleepy-evelyn/67aafdc68c3d436e68c11ed3e092052f
**Log file**: https://gist.github.com/sleepy-evelyn/7c674366a4a46d73e8a32f1c0dac8d87
**Steps to reproduce**: Create a new world or try to load a new world

I couldn't find any loading issues for the loot table and obviously removing EMI loot fixed the issue but I doubt this is an issue with EMI and more a problem with the loot table for the Bumblezone. Although I could be wrong.

**Comment by sleepy-evelyn** [comment]
So my suspicions where correct. It's an issue specifically with version 7.1.5 or 7.1.6 since it crashes as soon as I updated to that version on modrinth. Obviously the issue still exists for newer versions as well :P

**Comment by sleepy-evelyn** [comment]
If I was gonna guess which commit probably this one https://github.com/TelepathicGrunt/Bumblezone/commit/08379820dbf81f8dc595b7f671add2e78c4e4193 and since it's an entity loot issue it's probably this that's the issue. https://github.com/TelepathicGrunt/Bumblezone/blob/08379820dbf81f8dc595b7f671add2e78c4e4193/fabric-base/src/main/java/com/telepathicgrunt/the_bumblezone/loot/LootTableModifier.java#L17 I don't know the mod well enough to be sure though.

**Comment by TelepathicGrunt** [comment]
Closing as duplicate. Fix is already going to be released soon
