### ISSUE TITLE
[1.20.1] Mekanism Jetpacks still work in sanctums despite being "Disabled"

### ISSUE THREAD

**Issue by f-raZ0R** [TelepathicGrunt/Bumblezone#314]
Despite explicitly being disabled within sanctums, and having the cooldown overlay, you can still fly with a jetpack (and presumably other items like it). 
This is likely due to item disabling only actively applying, and the jetpack's effect being utterly passive. A jetpack doesn't have a right click effect, but that seems to be the only thing being disabled with an eternal cooldown?

Unsure if other similar disabled passive equipment would also fail to be disabled.

Tested on 1.20.1, forge 47.1.3, in a test profile with solely bumblezone and mekanism, latest versions of both.

**Comment by TelepathicGrunt** [comment]
That’s only because mekanism did not add the check for item cooldown just yet. Please be patient for them to do the work needed. Just was delayed longer than expected is all

https://github.com/mekanism/Mekanism-Feature-Requests/issues/591

**Comment by TelepathicGrunt** [comment]
Mekanism added feature now
