### ISSUE TITLE
[1.20.1][Forge] SugarWaterLogged doesnt make sugar cane grow more than 3 block

### ISSUE THREAD

**Issue by zeid0ne** [TelepathicGrunt/Bumblezone#316]
If the sugar water is alone, the sugar cane grow more than 3 block.
But if i put for example a slab on the same bloc as the sugar water, the sugar cane dont grow more than 3 block.

**Comment by TelepathicGrunt** [comment]
Placing a slab where sugar water is turns it into normal water. This is a limitation of vanilla’s waterlogging system where waterloggable blocks can only be waterlogged with one fluid ever. Slabs hold only vanilla water. Hence why it converted the sugar water to water.
