### ISSUE TITLE
[1.16.3] Weird null errors in console? (On a server)

### ISSUE THREAD

**Issue by Gbergz** [TelepathicGrunt/Bumblezone#32]
**Minecraft**: 1.16.3
**Forge**: 34.1.42
**Productive Bees Version**: [0.4.1.4](https://www.curseforge.com/minecraft/mc-mods/productivebees/files/3086091)
**BumbleZone Version**: [2.2.2](https://www.curseforge.com/minecraft/mc-mods/the-bumblezone-forge/files/3100033)

Some of the spam in the logs: https://hatebin.com/nhudpqldaq

Any ideas?

**- Gbergz**

**Comment by Gbergz** [comment]
Wrong place to post this i noticed, moving over to Productive bees.

**Comment by TelepathicGrunt** [comment]
Reopening as it is indeed an issue on my end with generating their TEs. Gonna close https://github.com/JDKDigital/productive-bees/issues/106 now lol

 Working on a fix for it

**Comment by TelepathicGrunt** [comment]
Should be fixed in 2.2.3! Keep watch on curseforge for it's approval. I also fixed the combs that are disabled on productive bee's side from spawning as well
