### ISSUE TITLE
cannot change recipes via datapack

### ISSUE THREAD

**Issue by Aceplante** [TelepathicGrunt/Bumblezone#322]
Main>data>the_bumblezone>recipes>bee_soup.json

does not work?

1.20.1

**Comment by TelepathicGrunt** [comment]
Please share the datapack you made and explain exactly how you tried to apply the datapack to the world. 

My mod has the recipe file here which means it is 100% datapackable because datapacks can override mod’s json files since mods data folders are just technically seen as small datapacks by Mc 
https://github.com/TelepathicGrunt/Bumblezone/blob/1.20-Arch/common/src/main/resources/data/the_bumblezone/recipes/bee_soup.json

**Comment by Aceplante** [comment]
Went to the datapack folder, dropped my datapack in, just as I normally do. The datapack as a whole was working, just not certain recipes like yours, still using the default and not my edited one from the same path. I can try to test a minimal version sometime

**Comment by TelepathicGrunt** [comment]
Works for me. This is why I wanted your datapack so I can check to make sure it is setup correctly and has no errors. Also, make sure your datapack is applied as higher priority. If you applied it as lower priority than mods, then it can't replace mod's stuff.

[bee_soup_test.zip](https://github.com/TelepathicGrunt/Bumblezone/files/13773777/bee_soup_test.zip)

![image](https://github.com/TelepathicGrunt/Bumblezone/assets/40846040/76115df3-166f-46e9-be09-13d9cd377f73)
![image](https://github.com/TelepathicGrunt/Bumblezone/assets/40846040/22f8d490-2840-47e8-a430-098371d13eae)
![image](https://github.com/TelepathicGrunt/Bumblezone/assets/40846040/5d264a10-8637-4df0-b944-6f24e8a7b27a)

**Comment by TelepathicGrunt** [comment]
Also make sure datapack is enabled by doing `/datapack list enabled`. If it is not, use `/datapack enable ...` to enable the datapack and then close and re-open world for changes to take effect
![image](https://github.com/TelepathicGrunt/Bumblezone/assets/40846040/ea3b5ac4-1a46-4ac5-a3de-bd803a4f57fe)

**Comment by Aceplante** [comment]
mine is also at the bottom of that list when I do that command

anyways here you go (make sure to take it out of the zip btw)

[datapack - Copy.zip](https://github.com/TelepathicGrunt/Bumblezone/files/13781557/datapack.-.Copy.zip)

**Comment by Aceplante** [comment]
might be as issue with craft tweaker?

**Comment by Aceplante** [comment]
> might be as issue with craft tweaker?

it was not

**Comment by TelepathicGrunt** [comment]
@Aceplante2 Your issue is you misspelled recipe folder here in your datapack you linked
![image](https://github.com/TelepathicGrunt/Bumblezone/assets/40846040/81119318-2976-48d8-ba18-73469c9f3234)

Fix that and give it another try and see if it now is useable with Farmer's Delight

**Comment by Aceplante** [comment]
sure, I can give it a try, but I normally uses "recipes" and dont have any issues. Plus, your path: common/src/main/resources/data/the_bumblezone/recipes/bee_soup.json
uses "recipes"

**Comment by TelepathicGrunt** [comment]
I am pointing out that the datapack you just gave me has `recpies` as the folder name for recipes which is a misspelling and Minecraft will not read it. It needs to be `recipes`

**Comment by Aceplante** [comment]
...ah, that could do it lol can't believe I missed that. Thanks
