### ISSUE TITLE
[Feature Request] Add search bar to crystalline flower

### ISSUE THREAD

**Issue by JustTemmie** [TelepathicGrunt/Bumblezone#325]
i'm sorry if this isn't the place to make a feature request

but would it be possible to add a search bar to the crystalline flower in any way? In big modpacks the list of enchantments can easily hit 200, and finding anything within it is rather time consuming, especially when the enchantment name differs from the internal enchantment ID, causing it to not be sorted into the right spot

**Comment by TelepathicGrunt** [comment]
The UI is already heavily packed and I hate touching rendering/UI stuff… : cries :

**Comment by JustTemmie** [comment]
ah :sweat_smile: fair enough, could it be a keybind of sort?

**Comment by TelepathicGrunt** [comment]
This is the current flower UI. Keybind doesn't really change anything as the UI still doesn't have room anywhere for a search bar.

![image](https://github.com/TelepathicGrunt/Bumblezone/assets/40846040/2d4cd260-cbe1-46fa-88b2-0a2eafdbb924)

Instead it probably is better I just sort better. Give me a list of several modded enchantements whose translated names differs from their registry names

**Comment by JustTemmie** [comment]
it's all just modded enchantments, three mods that have the inconsistencies are:

spell_power:critical_chance - Spell Volatility
mcdw:jungle_poison - poisoning
soulsweapons:visceral - Posture Breaker

additionally a ton of curses are inconsistently sorted, as they typically go by "something"_curse internally, this does actually apply to the vanilla curses too

**Comment by TelepathicGrunt** [comment]
Are you playing in single player or server? If server, are you server owner?

**Comment by JustTemmie** [comment]
server, and i am the server owner

**Comment by TelepathicGrunt** [comment]
I forgot to ask, which modloader and mc version? I can give you a test jar to see if it is better. Without adding search bar which I am still reluctant to do, I instead sort the enchantments in the list based on their translated names instead of their registry names which should solve the finding issues due to translated names being different. Though it requires quite a bit of code adjusting and changing that I would like someone to test it a bit to make sure it doesn't like explode or something. My testing seemed fine

**Comment by JustTemmie** [comment]
fabric 1.20.1, i assume the mod would be entirely client side?

**Comment by TelepathicGrunt** [comment]
No, it would have to go on both client and server as it requires a change to how the data is sent between the client and server for crystalline flower to work properly. That's what I am worried about as I hope no new edge case comes up with the syncing and stuff. If you can't test it, that's ok
[the_bumblezone-7.1.15-test+1.20.1-fabric.zip](https://github.com/TelepathicGrunt/Bumblezone/files/13814304/the_bumblezone-7.1.15-test%2B1.20.1-fabric.zip)

**Comment by TelepathicGrunt** [comment]
Just released an update with the alphabetical sorting now on client side with the actual translations for the enchantments. Should make it easier to find the enchantments you want
