### ISSUE TITLE
The game crashed whilst exception ticking world 1.20.1 -the_bumblezone-7.1.14+1.20.1-forge

### ISSUE THREAD

**Issue by OBS3SS1ON** [TelepathicGrunt/Bumblezone#326]
I got an error when I opened one chest and looked at a dispenser. playing survival.

The game crashed whilst exception ticking world
Error: java.lang.IllegalAccessError: Update to non-static final field net.minecraft.world.level.block.piston.PistonStructureResolver.f_60410_ attempted from a different method (handler$bff000$modifyForcePushOrigin) than the initializer method <init> 

at net.minecraft.world.level.block.piston.PistonStructureResolver.handler$bff000$modifyForcePushOrigin(PistonStructureResolver.java:528) ~[client-1.20.1-20230612.114412-srg.jar%23624!/:?]

[latest.log](https://github.com/TelepathicGrunt/Bumblezone/files/13812577/latest.log)
[debug.log](https://github.com/TelepathicGrunt/Bumblezone/files/13812579/debug.log)

**Comment by TelepathicGrunt** [comment]
I looked closer at your stacktrace. modifyForcePushOrigin is not a mixin from my mod. It is a mixin from Botania. You will need to contact Botania devs so they can look into why their mixin is crashing

https://github.com/VazkiiMods/Botania/blob/6016936edc485e6b6c4d70e8a26172b4ace842b0/Xplat/src/main/java/vazkii/botania/mixin/PistonStructureResolverMixin.java#L27

**Comment by TelepathicGrunt** [comment]
Looks like Botania already fixed this here: https://github.com/VazkiiMods/Botania/issues/4527#issuecomment-1874386572

**Comment by OBS3SS1ON** [comment]
Oh!! Thank you very much as I read your mod name in the log.txt thinking it was from your mod, Thank you very much I will see if it is resolved
