### ISSUE TITLE
Crash When entering the Bumblezone Dimension

### ISSUE THREAD

**Issue by Thedrummonger** [TelepathicGrunt/Bumblezone#33]
My game Crashes to desktop when I load into the Bumblezone Dimension. According to the crash report it seems to be related to the Resourceful Bees compact.

Crash Report: https://pastebin.com/0JVF9fBr

Minecraft Version 1.16.4
Forge Version: 35.0.17
Bumblezone Version: 1.16.4-2.2.3
Resourceful Bees Version:  1.16.3-0.5.5b

**Comment by TelepathicGrunt** [comment]
Did you disable any of resourceful bee's honeycombs or something? 

Also, try this test jar and see if this fixes the crash. I feel like a resourceful bee comb was disabled and cause the crash as I dont get the crash myself when I test with the default configs and all
[the_bumblezone-1.16.4-2.2.4b.zip](https://github.com/TelepathicGrunt/Bumblezone/files/5577034/the_bumblezone-1.16.4-2.2.4b.zip)

**Comment by Thedrummonger** [comment]
It works as intended with the Version you linked. I did edit the default's pretty heavily and disabled the "generateDefaults" option in  the resourceful bee's config. I should have mentioned that, but with how configurable resourceful bee's is I guess I didn't assume that would be an issue. But the changes you made seem to have fixed it!

**Comment by TelepathicGrunt** [comment]
Thank you for reporting this! So my hunch was right that disabling their honeycombs could crash my mod cause I forgot to check to make sure the comb exists.

v2.2.4 is now approved on curseforge!
https://www.curseforge.com/minecraft/mc-mods/the-bumblezone-forge/files/3118645
