### ISSUE TITLE
Crushed When Entering BeeQueen's home

### ISSUE THREAD

**Issue by YocyCraft** [TelepathicGrunt/Bumblezone#330]
Crushed every time loading the world.
 
Modpack: E9E [Enigmatica 9: Expert](https://www.curseforge.com/minecraft/modpacks/enigmatica9expert)

[crash-2024-01-07_21.17.11-server.txt](https://github.com/TelepathicGrunt/Bumblezone/files/13853610/crash-2024-01-07_21.17.11-server.txt)

**Comment by TelepathicGrunt** [comment]
This was already fixed a long time ago. Update Bumblezone and the issue will go away

The crash isn't with bee queen. It's the Sticky Honey Redstone and Redstone Honey Web crashing when any entity goes inside them.
