### ISSUE TITLE
Mixin into Sodium crashing due to remapping issue

### ISSUE THREAD

**Issue by PikouGame** [TelepathicGrunt/Bumblezone#336]
[latest.log](https://github.com/TelepathicGrunt/Bumblezone/files/13933173/latest.log)
The Bumblezone version : v7.2.1
Sodium version: v0.5.3
Thank you in advance

**Comment by TelepathicGrunt** [comment]
Using Sodium 0.5.3 with Bumblezone 7.2.1 for 1.20.1 Fabric, I am not getting this crash at all. But here, try this jar and see if this works (Unzip file first to get jar)
[the_bumblezone-7.2.2-beta+1.20.1-fabric.jar.zip](https://github.com/TelepathicGrunt/Bumblezone/files/13933596/the_bumblezone-7.2.2-beta%2B1.20.1-fabric.jar.zip)

**Comment by PikouGame** [comment]
Ill try it, thank you for your time!

**Comment by PikouGame** [comment]
It worked! Thank you really much!
