### ISSUE TITLE
Crystalline Flower Consume XP buttons not working at very high player xp levels

### ISSUE THREAD

**Issue by ishmintyy** [TelepathicGrunt/Bumblezone#339]
![crystalline](https://github.com/TelepathicGrunt/Bumblezone/assets/157420014/e3959ea6-e104-4724-9e30-08c72fe32784)
exp isnt working on the flower :C

**Comment by TelepathicGrunt** [comment]
I need more info. I cannot do anything without troubleshooting steps.

What minecraft version are you playing on?
What bumblezone version?
What modloader?
And specifically, what is the actual issue? Like what exact steps are you trying to do and having issues with?

**Comment by ishmintyy** [comment]
Minecraft version 1.20.1, Bumblezone version 7.1.4, using fabric
The issue is I'm trying to use the crystalline flower by putting in exp instead of items but it isn't working. Originally it worked and suddenly it stopped so I waited for server reset and it still hasn't worked since.

**Comment by TelepathicGrunt** [comment]
You have so much XP that you overflowed the xp calculations to negative.
![image](https://github.com/TelepathicGrunt/Bumblezone/assets/40846040/fed39145-0fcd-4294-882b-020f43554fa6)

Workaround is, lower your xp for now

**Comment by TelepathicGrunt** [comment]
Will be fixed next Bumblezone version which I will be holding onto until some more bugs are found. That way the update has a bit more beef to it. But yeah, for now, you'll have to grow the flower by other means or find a way to lower your xp levels to something more sane that my mod can handle. If you can convert your xp into bottles o enchanting, you can throws those at the flower to grow it with your xp as another workaround

**Comment by TelepathicGrunt** [comment]
Fix is now released
