### ISSUE TITLE
Compatibility Question: Productive Bees & Royal Jelly

### ISSUE THREAD

**Issue by ShapiroDeluxe** [TelepathicGrunt/Bumblezone#340]
Hi! I recently reached out to the Productive Bees creator about this issue and the said there was nothing on their end, so I've found myself here. The problem relates to the overlap between this mod, Productive Bees and Extreme Reactors. I found that certain productive bees added by the Extreme Reactors mod (e.g. the cyanite bee) made royal jelly instead of regular honey when their combs were processed. However, when I opened by modpack today, these bees went back to regular honey! The change was reflected in the JEI and everything. 

 I've poked around in the code here and in the other mods but I haven't found anything. I'm not a coder, so anything is helpful. I'm having trouble finding proof that this interaction even existed! 

If you know anything, please let me know. Thank you!

**Comment by TelepathicGrunt** [comment]
Were they making Royal jelly from Bumblezone or some other mod’s Royal jelly? If it is Bumblezone’s fluid, that shouldn’t be happening. Royal jelly in Bumblezone is supposed to be extremely good and powerful so it is gated behind bee Queen advancement.  

(Also Mc version would be helpful to be stated)

**Comment by ShapiroDeluxe** [comment]
Thanks for the quick response! It's a really strange situation. It was 100% bumblezone's fluid, I was able to accumulate it into buckets and trade it to the Queen. These 7 bees produced 50mL per comb. And overnight this interaction just... disappeared! The version in question is 1.20.1.

**Comment by TelepathicGrunt** [comment]
Honestly, that sounds like a bug. The Royal jelly fluid should (edit: NOT) be obtainable from the combs of other mod’s bees. Without the pack and exact setup you were doing, I can’t dig into why Royal jelly was being given in the first place when it shouldn’t.

If this is not your modpack, have you asked the modpack maker if they were doing any sort of compat with scripts or something and that the scripts just aren’t loading properly anymore?

**Comment by TelepathicGrunt** [comment]
Sorry, I typoed before. Royal jelly should NOT be obtainable from other mod’s bees. That’s the bug. Unless pack maker was doing configs and scripts and datapacks to change the bee’s output to give my fluid. Either way, it’s outside my control as it is not my bees and not a mechanic I control

**Comment by TelepathicGrunt** [comment]
Update, talked with productive bees dev, turns out yeah the Royal jelly showing up was a bug due to randomly picking a fluid from the honey fluid tag. If you update productive bees, it seems it should fix it.

![IMG_0738](https://github.com/TelepathicGrunt/Bumblezone/assets/40846040/71dead47-b5f9-49d3-be5e-c0f8e50c2d05)
![IMG_0739](https://github.com/TelepathicGrunt/Bumblezone/assets/40846040/c19fd526-c484-4898-8a76-39bea9dc6fc8)

**Comment by ShapiroDeluxe** [comment]
Haha, I am the modpack maker here fortunately, so I know for sure there were no scripts involved (at least ones I am aware of). It totally could be a bug, but it's funny that the JEI mod recognized it as a legitimate recipe. 

I have dropped the modlist here, but only bother if you're curious and willing to read it. Since this is largely outside your modpack you can consider this case closed for now. Additionally, there was no particular setup I am aware of that could have caused this to happen. Thank you! 

[modlist.txt](https://github.com/TelepathicGrunt/Bumblezone/files/14017166/modlist.txt)

**Comment by ShapiroDeluxe** [comment]
HAHA okay that's fantastic, I just saw your reply. I love that you two are in touch. That's fascinating, thank you so much!
