### ISSUE TITLE
Quark 1.20.1 Compat error

### ISSUE THREAD

**Issue by windth001** [TelepathicGrunt/Bumblezone#341]
Bumblezone  7.2.3+1.20.1
Forge 47.2.19

23.01 19:48:59 [Server] main/ERROR [co.te.th.Bumblezone/]:   ------------------------------------------------NOTICE-------------------------------------------------------------------------
23.01 19:48:59 [Server] INFO   ERROR: Something broke when trying to add mod compatibility with quark. Please let The Bumblezone developer (TelepathicGrunt) know about this!

[crashreport.log](https://github.com/TelepathicGrunt/Bumblezone/files/14029751/crashreport.log)

**Comment by TelepathicGrunt** [comment]
Yeah Quark updated and moved all their packages around breaking almost all compat mods had with Quark. Luckily I made my compat smart so it just logs the failed compat setup instead of crashing the game.

**Comment by TelepathicGrunt** [comment]
Fix is now released
