### ISSUE TITLE
Sugar Water displays incorrectly with Distant Horizons

### ISSUE THREAD

**Issue by NolanHewitt** [TelepathicGrunt/Bumblezone#342]
Not sure if this is a distant horizons issue or something that can be fixed on the side of this mod, but wanted to report it here just in case.
![huge_2024-01-27_23 09 54_10](https://github.com/TelepathicGrunt/Bumblezone/assets/52480898/6280f60b-7283-41b6-b94c-2d7dfb3bb1f4)

**Comment by TelepathicGrunt** [comment]
I have no control over what distance horizon does. Please report the issue to them so they can investigate

**Comment by TelepathicGrunt** [comment]
Might be related to https://gitlab.com/jeseibel/distant-horizons/-/issues/606 ?

Please let me know when you make a new issue report to them so I can watch it for what they say

**Comment by NolanHewitt** [comment]
I've made an issue here: https://gitlab.com/jeseibel/distant-horizons/-/issues/620

I don't use BCLib so I don't think the issues are related

**Comment by NolanHewitt** [comment]
Coming back to this, I think distant horizons just has issues with modded liquids in general. Oil from ad astra renders as bright white instead of black in lod chunks, so its not a bumblezone issue at all. I thought the water from this mod was purple since that's commonly used as the texture error color, but seems like its just assigning modded liquids incorrect colors seemingly randomly but consistently in lod chunks

**Comment by NolanHewitt** [comment]
Found out the issue, DH inverts the colors of modded liquids. It makes the oil white instead of black, and it makes the sugar water purple because its the opposite of yellow on a color wheel.
