### ISSUE TITLE
Fluid layers can be visible with certain liquids

### ISSUE THREAD

**Issue by Lolothepro** [TelepathicGrunt/Bumblezone#360]
Minecraft 1.20.4
Fabric Loader 0.15.7
Fabric API 0.96.3

https://github.com/TelepathicGrunt/Bumblezone/assets/68275908/ce7ef4dc-2825-4081-8898-6fec189cdcb9

**Comment by TelepathicGrunt** [comment]
I don’t care about spectator mode. Only survival. And it’s fine as far as I’m concerned

**Comment by Lolothepro** [comment]
it also seems to affect Minecraft's survival mode
![2024-02-20_21 25 07](https://github.com/TelepathicGrunt/Bumblezone/assets/68275908/ab69dca7-da96-4faa-bf73-94cf5e88137b)
you can't see the layers that delimit the fluid's rendering with water, unlike Bumblezone's fluid

**Comment by Lolothepro** [comment]
Then, I don't know if you want to fix it

**Comment by TelepathicGrunt** [comment]
addressed now
