### ISSUE TITLE
Bumblezone is broken with the future translucent sorting of Sodium

### ISSUE THREAD

**Issue by Lolothepro** [TelepathicGrunt/Bumblezone#361]
This causes issues like this:

![2024-02-25_19 40 07](https://github.com/TelepathicGrunt/Bumblezone/assets/68275908/8fa10f5b-4b6c-4f77-8035-7d07db2b08d0)

IMS said:
the problem is Bumblezone is giving an value of up
which is aligned, but just completely wrong
it gives up even on the sides
even on the bottom

**Comment by douira** [comment]
The normal being given through the fluid handler api doesn't correspond to the facing (up/down/n/w/e/s). This breaks translucency sorting. I expect it to also be fixed on our end by simply distrusting the normals being passed in and recalculating them based on the actual geometry, but it's worth mentioning that the given normal is wrong.

**Comment by TelepathicGrunt** [comment]
I was copying vanilla’s bottom rendering and changing the height iirc. So I don’t know specifically which line is controlling the normals or how to fix it. It would also mean sodium isn’t supporting vanilla and many mods would be copying the same vanilla code.

Edited to word what I wanted to say better

**Comment by douira** [comment]
I was expecting as much, the fluid rendering is rather complicated. We'll just calculate normals ourselves then (or maybe somebody will PR it to you, idk).

**Comment by douira** [comment]
Sodium is going to be working around improper usage of the API by recalculating normals for all quads given through this API. Fabric's default implementation of the API doesn't enforce it (by, for example, breaking) and is less strict than the (albeit also compliant) implementation by Sodium.
