### ISSUE TITLE
block don,t load 

### ISSUE THREAD

**Issue by Xenom773** [TelepathicGrunt/Bumblezone#362]
![obraz_2024-02-26_205202427](https://github.com/TelepathicGrunt/Bumblezone/assets/161376384/b3be2a35-c146-42d1-aadd-6bb0d8c63925)

**Comment by TelepathicGrunt** [comment]
Put on Indium. I’m guessing you’re using Sodium without Indium on. 

If not, I need far more info. Such as minecraft version, modloader, and what other mods you have on

**Comment by TelepathicGrunt** [comment]
Closing as I am 99% sure you’re trying to use sodium without the indium mod on. Sodium will not work properly without this dependency that it doesn’t mention

**Comment by Zouzs** [comment]
> Closing as I am 99% sure you’re trying to use sodium without the indium mod on. Sodium will not work properly without this dependency that it doesn’t mention

Can confirm this fixed the issue for me.
