### ISSUE TITLE
[Fabric 1.20.1/1.20.4] Mob drops are no longer occurring

### ISSUE THREAD

**Issue by viktordimov** [TelepathicGrunt/Bumblezone#364]
Using The Bumlezone makes it so no mobs drop any loot or XP. I've tested mod by mod, identified this one but I have no idea what causes the issue.

**Comment by TelepathicGrunt** [comment]
Please say Mc version, modloader, and link to modpack you are using. I just recently tested smacking a bunch of zombies the other day with Bumblezone on and gotten loot drops

**Comment by TelepathicGrunt** [comment]
It's fabric with the issue. Not forge or neoforge where I tested before it seems. Only learned due to someone in discord asking me about this and providing the info I need.

**Comment by TelepathicGrunt** [comment]
Fixed now
