### ISSUE TITLE
[Forge 1.20.1] [Bug]: Sickened Spiders take place of Spider/Cave Spider Spawners in spider Dungeon in Bumblezone when CWSM is installed.

### ISSUE THREAD

**Issue by ghost** [TelepathicGrunt/Bumblezone#366]
When both CWSM and Bumblezone are both installed, there's a chance for Sickened Spiders to take place in the Spider Spawners in Spider-infested areas of the Bumblezone.

Simply the Bumblezone with CWSM also installed, and you should see this bug pop up in the Spider Dungeon.

![image](https://github.com/TelepathicGrunt/Bumblezone/assets/148708399/42692f46-9d14-4ab5-8e15-a69a68659f02)

Mod Loader: Forge 47.2.20
OS: Windows 11
Minecraft Version: 1.20.1

Mods installed:
  [✔] additional_enchantments-1.20.1-0.3.5-all
  [✔] additionaladditions-6.0.1
  [✔] AdvancementPlaques-1.20.1-forge-1.4.10
  [✔] alexsmobs-1.22.8
  [✔] alternategunpowder-1.0.0-1.20.1
  [✔] arboria-1.2.2-1.20.1
  [✔] autohud-6.3.4+1.20.1-forge
  [✔] backpacked-forge-1.20.1-2.2.5
  [✔] bulletsboats-0.0.6-1.20.1
  [✔] CalamityMusicDisc1.20.1 2.0 R
  [✔] CerbonsAPI-Forge-1.20.1-1.1.0
  [✔] CerbonsBetterBeacons-Forge-1.20.1-1.1.1
  [✔] CGM-Unofficial-1.4.11+Forge+1.20.1
  [✔] citadel-2.5.3-1.20.1
  [✔] collective-1.20.1-7.30
  [✔] curios-forge-5.6.1+1.20.1
  [✔] do_a_barrel_roll-forge-3.5.0+1.20.1
  [✔] dungeons-and-taverns-3.0.3
  [✔] dynamiccrosshair-7.4.4+1.20-forge
  [✔] EasyAnvils-v8.0.1-1.20.1-Forge
  [✔] EasyMagic-v8.0.1-1.20.1-Forge
  [✔] elytra_physics-forge-2.0
  [✔] ElytraBombing-Forge-1.20.1-1.0.0
  [✔] embeddium-0.2.18+mc1.20.1
  [✔] embeddiumplus-1.20.1-v1.2.3-build
  [✔] EnchantingInfuser-v8.0.2-1.20.1-Forge
  [✔] entity_model_features_forge_1.20.1-1.2.3
  [✔] entity_texture_features_forge_1.20.1-5.2.2
  [✔] experimentalsettingsdisabler-1.20.1-3.0
  [✔] ForgeConfigScreens-v8.0.2-1.20.1-Forge
  [✔] framework-forge-1.20.1-0.6.26
  [✔] geckolib-forge-1.20.1-4.4.2
  [✔] hearths-v1.0.0-mc1.20u1.20.1
  [✔] Iceberg-1.20.1-forge-1.1.13
  [✔] immersive_weathering-1.20.1-2.0.1-forge
  [✔] invtweaks-1.20.1-1.0.0
  [✔] jei-1.20.1-forge-15.2.0.27
  [✔] L_Enders_Cataclysm-1.90 -1.20.1
  [✔] LeavesBeGone-v8.0.0-1.20.1-Forge
  [✔] mobbattle-1.20.1-2.4.7-forge
  [✔] moonlight-1.20-2.9.7-forge
  [✔] NonConflictKeys-Forge-1.19.X-1.20-1.0.0
  [✔] oculus-mc1.20.1-1.6.13
  [✔] paddedelytras-1.20-1.0
  [✔] PureOres-v1.0.3-1.20.1-Forge
  [✔] PuzzlesLib-v8.1.14-1.20.1-Forge
  [✔] sculkhorde-1.20.1-0.9.0-Beta3
  [✔] skinlayers3d-forge-1.6.2-mc1.20.1
  [✔] smallships-forge-1.20.1-2.0.0-b1.0
  [✔] spyglass_of_curios-forge-1.20.1-1.7.2
  [✔] Terralith_1.20.4_v2.4.11
  [✔] textrues_embeddium_options-0.1.3+mc1.20.1
  [✔] the_bumblezone-7.2.16+1.20.1-forge
  [✔] treeharvester-1.20.1-8.6
  [✔] UniversalEnchants-v8.0.0-1.20.1-Forge
  [✔] vc_gliders-forge-1.1.5
  [✔] veinmining-forge-1.3.0+1.20.1
  [✔] witherstormmod-1.20.1-4.0.1.1
  [✔] YungsApi-1.20-Forge-4.0.3
  [✔] YungsBetterEndIsland-1.20-Forge-2.0.5
  [✔] YungsBetterMineshafts-1.20-Forge-4.0.4
  [✔] YungsMenuTweaks-1.20.1-Forge-1.0.2

**Comment by TelepathicGrunt** [comment]
Why do you think this a bug? Just curious as I explicitly allowed modded spiders in my Spawners if their drops aren’t crazy

**Comment by TelepathicGrunt** [comment]
These are the tags where i specify what modded spider can spawn in what structure’s mob Spawners rarely. If you wish to remove said modded mob spawner possibility, datapack override these tags, set replace to true, and then remove the entries you don’t want https://github.com/TelepathicGrunt/Bumblezone/tree/1.20.x-Arch/common/src/main/resources/data/the_bumblezone/tags/entity_types/structure_spawner_mobs

Btw, sickened spider comes from witherstormmod. Not CWSM
