### ISSUE TITLE
Suggestion for Eating Animation mod compatability

### ISSUE THREAD

**Issue by AstardGrimoire** [TelepathicGrunt/Bumblezone#367]
Add consumpition animation for bumblezone foods if Eating Animation mod is installed
(How do i add labels?)

**Comment by TelepathicGrunt** [comment]
Hmm it may be better for you to ask the Eating Animation dev to add support on their side. It seems they are handling support for several mods already so they might be able to add support for Bumblezone on their side 

https://github.com/Theoness1/EatingAnimation/tree/1.20/src/main/resources/resourcepacks/supporteatinganimation/assets

**Comment by TelepathicGrunt** [comment]
Linking the Eating Animation post to here: https://github.com/Theoness1/EatingAnimation/issues/52

**Comment by AstardGrimoire** [comment]
They actually added it.
I think I can close the issue now.
