### ISSUE TITLE
Crash when using Essence Life above build limit

### ISSUE THREAD

**Issue by FlameFire26** [TelepathicGrunt/Bumblezone#371]
**Minecraft 1.20.4 Fabric**
- When holding _Essence Life_ on offhand and turning to Y > 319 in overworld, game crash. (Y > 255 in the nether, premise using _Essence of the Bees_)

**Mods**
- fabric-api-0.96.11+1.20.4
- modmenu-9.0.0
- midnightlib-fabric-1.5.3
- the_bumblezone-7.4.1+1.20.4-fabric

**Crash Report**

> Description: Ticking player
> 
> java.lang.ArrayIndexOutOfBoundsException: Index xx out of bounds for length xx
> 	at net.minecraft.class_2791.method_38259(class_2791.java:162)
> 	at com.telepathicgrunt.the_bumblezone.items.essence.LifeEssence.growNearbyPlants(LifeEssence.java:167)
> 	at com.telepathicgrunt.the_bumblezone.items.essence.LifeEssence.applyAbilityEffects(LifeEssence.java:80)
> 	at com.telepathicgrunt.the_bumblezone.items.essence.AbilityEssenceItem.method_7888(AbilityEssenceItem.java:155)
> 	at net.minecraft.class_1799.method_7917(class_1799.java:518)
> 	at net.minecraft.class_1661.method_7381(class_1661.java:256)
> 	at net.minecraft.class_1657.method_6007(class_1657.java:579)
> 	at net.minecraft.class_1309.method_5773(class_1309.java:2446)
> 	at net.minecraft.class_1657.method_5773(class_1657.java:284)
> 	at net.minecraft.class_3222.method_14226(class_3222.java:519)
> 	at net.minecraft.class_3244.method_18784(class_3244.java:257)
> 	at net.minecraft.class_2535.method_10754(class_2535.java:379)
> 	at net.minecraft.class_3242.method_14357(class_3242.java:176)
> 	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:959)
> 	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:845)
> 	at net.minecraft.class_1132.method_3748(class_1132.java:110)
> 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:683)
> 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
> 	at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by TelepathicGrunt** [comment]
Fixed now
