### ISSUE TITLE
Stinger spear shrine spawns a regular spear instead of The undead banisher

### ISSUE THREAD

**Issue by AstardGrimoire** [TelepathicGrunt/Bumblezone#373]
All spear shrines that I found so far contained a regular stinger spear.
I remember in older versions it contained a spear called "The undead banisher" and has smite 5 and unbreaking 3. Now its just a regular stinger spear that has nothing special, not even tooltip.
I don't know, is this a bug or just a feature?
I checked wiki and it says that spear shrine should spawn a special enchanted spear.

**Comment by TelepathicGrunt** [comment]
@AstardGrimoire are you using latest version of Bumblezone as I already fixed an issue before where nbt is lost on the spear

**Comment by AstardGrimoire** [comment]
I just installed the latest version - 7.4.2 -Fabric
And nope, still spawns the regular spear

**Comment by AstardGrimoire** [comment]
Just tested without additional mods.
Its not a mod compat issue, the shrine still spawns a regular spear.

**Comment by TelepathicGrunt** [comment]
fixed
