### ISSUE TITLE
[Suggestion] Acheivements icons

### ISSUE THREAD

**Issue by AstardGrimoire** [TelepathicGrunt/Bumblezone#374]
Replace repeating acheivement icons with drawings
Look at pictures i added to actually understand what im meaning
![2024-04-07_00 03 07](https://github.com/TelepathicGrunt/Bumblezone/assets/162748058/91dabc92-2ccd-482e-a922-1edf4c28632e)
![2024-04-07_00 02 46](https://github.com/TelepathicGrunt/Bumblezone/assets/162748058/8e1d7017-42e4-42c7-b6d8-efe7a95d44d6)
![2024-04-06_23 35 31](https://github.com/TelepathicGrunt/Bumblezone/assets/162748058/7d8d2951-1efc-4063-a53c-2c59565b53c3)
![2024-04-07_00 10 30](https://github.com/TelepathicGrunt/Bumblezone/assets/162748058/8236ed10-3a71-4f41-86ab-614ed8381d23)

**Comment by TelepathicGrunt** [comment]
Advancements work by requiring an item to use for the icon.
![image](https://github.com/TelepathicGrunt/Bumblezone/assets/40846040/ad0455f2-8f63-455b-a8ba-9b4b3be71aa4)

I do not want to make a ton of dummy items just for advancement icons. When mojang make advancement icons only require a texture resourcelocation, I'll make the change. Until then, I just reuse existing real items for the icon. I also don't want to add another dependency if another mod adds that option. I rather it be in the base game itself.
