### ISSUE TITLE
Server hanging issue - Incompatability with Integrated Dungeons and Structures

### ISSUE THREAD

**Issue by TheWisme** [TelepathicGrunt/Bumblezone#375]
There exists an issue when both The Bumblezone and Integrated Dungeons and Structures and its dependencies are loaded, and when trying to load specific chunks. If you try to load a chunk where an IDAS structure would spawn, there is a chance that the server will get caught trying to process a single tick. We're not sure which of the two is causing it or why, or even what specifically causes the issue, but to recreate follow the steps below.

1. Create a 1.20.1, Neoforge 47.1.101 instance with the most up to date versions of Intergrated Dungeons and Structures, Integrated API, Create, Quark, Zeta, Supplementaries, Moonlight Library, and The Bumblezone.
2. Create a world with the seed "6643873748131111404"
3. Teleport to the coordinates 860, 100 -250
4. Attempt to travel northeast about 150 blocks

Expected behavior: The chunks load as expected, with an IDAS castle structure in the loaded chunks

Actual behavior: The server hangs, and must be killed to exit.

I hope this helps you diagnose the issue.

**Comment by TelepathicGrunt** [comment]
IDS has a horse with an owner UUID saved into their structure nbt file. When loaded during worldgen, it trigger my code to try and send that UUID to client so client knows who owns the horse. Problem is the packet sending code is not worldgen safe

**Comment by TelepathicGrunt** [comment]
Try v7.3.4 and see if issue is fixed

**Comment by TheWisme** [comment]
Yep! Things are working correctly now. Thanks!
