### ISSUE TITLE
[1.19.2] Seemingly unable to use honey buckets on any tank

### ISSUE THREAD

**Issue by MuteTiefling** [TelepathicGrunt/Bumblezone#376]
For more info: https://github.com/EnigmaticaModpacks/Enigmatica9/issues/934

I've tested now in 6.9.10+1.19.2 and am seeing the same thing. I can place honey on the ground, but cannot right click the bucket onto any sort of tank. 

Create's automatic bucket > fluid detection is failing to link BZ honey to the bucket, so draining doesn't work. I can't even insert the honey bucket into the input slot of a Mekanism tank, which should normally accept a bucket, drain the fluid into the tank, and return an empty bucket.

I'll test again in a cleaner instance in a bit to see if there's something weird in the pack that's doing this.

**Comment by TelepathicGrunt** [comment]
I need more info on repro steps because I don’t play mods so idk how create works

**Comment by MuteTiefling** [comment]
I have no idea how Create does this internally. But it automatically generates a recipe to drain buckets to fluid. I've never seen it not work. 

It's not just Create though. Honey buckets can't be drained by anything that normally drains fluids from a bucket. That includes 'input' slots on machine/tanks and right click actions on tanks. 

Example with BZ downgraded to 6.9.8. Downgraded as I seem to recall this working fine before...
https://streamable.com/i1vwnw

In this video, we see we can insert buckets of other fluids into the Mekanism tank and get their respective fluid + empty bucket.
This does not work for BZ Honey.

Now, on this older version of BZ, but we also see the Create recipe at the end. There's no bucket to fluid recipe, likely because it can't figure out a link between the bucket and the fluid. That appears exactly the same in BZ 6.9.10

Here's another one showing right click interactions on tanks not working with BZ honey vs working with water. 
https://streamable.com/xbuy7l

This also doesn't work in BZ 6.9.10.

**Comment by MuteTiefling** [comment]
I've gone back as far as 6.9.0 now and still seeing the same behavior. I'll now test in a limited instance.

**Comment by TelepathicGrunt** [comment]
If it doesn’t work in one version, it’s not going to work in any. I just needed to know how to replicate as create probably requires me to manually attach a special cap because forge in their infinite wisdom, decided modded buckets extending bucketitem doesn’t automatically get a fluid cap and does a hardcoded class check iirc

**Comment by MuteTiefling** [comment]
It's not just Create. It's everything. 

I just spun up a limited instance: 
![image](https://github.com/TelepathicGrunt/Bumblezone/assets/9543430/2b1fe934-ad0d-4e99-b174-9adad9b66eff)


Place a Mekanism tank
Right click it with honey bucket

Expectation: Honey is emptied into the tank
Reality: The GUI opens

Repeat with water, lava, or any other fluid. The fluid will be drained into the tank and you'll be left with an empty bucket in hand.

**Comment by TelepathicGrunt** [comment]
Again,

> forge in their infinite wisdom, decided modded buckets extending bucketitem doesn’t automatically get a fluid cap and does a hardcoded class check iirc

It's still the same forge issue because they explicitly check for vanilla bucket class. Not modded buckets. Which requires me to do extra messy effort to make forge read my bucket properly

**Comment by TelepathicGrunt** [comment]
fixed by: https://github.com/TelepathicGrunt/Bumblezone/commit/311875ef80a7d682351b5d1e2dfa74c0da7f5f92

**Comment by TelepathicGrunt** [comment]
v6.9.11 released
