### ISSUE TITLE
(1.20.1 Suggestion) Balancing spawn for productive bees

### ISSUE THREAD

**Issue by andres19992** [TelepathicGrunt/Bumblezone#378]
I don't know if this is intentional or not, but some really OP bees from Productive Bees can spawn naturally on the Bumblezone, which kind of ruins the progression of that mod. I was able to easily get a diamond bee that was hanging around my spawn and I don't think that's how you're supposed to get them.

**Comment by TelepathicGrunt** [comment]
Note to self, investigate config here that should be a whitelist of allowed bees but seems to list not allowed bees 
https://github.com/TelepathicGrunt/Bumblezone/blob/a75498537919c281474cf46057c149b70d4b0edb/forge/src/main/java/com/telepathicgrunt/the_bumblezone/configs/forge/BzModCompatibilityConfig.java#L252

Users will need to edit their config themselves in the config folder as me changing the default will not affect people who already generated a config file

**Comment by TelepathicGrunt** [comment]
fixed now
