### ISSUE TITLE
FTB Chunk compat issue with Bumblezone

### ISSUE THREAD

**Issue by suerion** [TelepathicGrunt/Bumblezone#380]
Hey, we had got an Issue on our 1.20.1 Fabric Server.

In an FTB Chunk no grieffing zone, we could use Buckets with Sugarwater, but only emptying, not filling.

Here an video, my friend has no bypass permission or something.
https://www.youtube.com/watch?v=SjJvV1W-W48

Versions: Link from Curseforge Launcher
https://www.curseforge.com/minecraft/mc-mods/the-bumblezone-fabric/files/5273612
https://www.curseforge.com/minecraft/mc-mods/ftb-chunks-fabric/files/5210494

**Comment by TelepathicGrunt** [comment]
fixed in v7.3.6
