### ISSUE TITLE
[1.20.1]Update zh-cn.json

### ISSUE THREAD

**Issue by ghost** [TelepathicGrunt/Bumblezone#382]
https://paste.ubuntu.com/p/FgFf7G3ZJD/
Update zh-cn.json,1.20.1's file is too old.
I'm sorry to not know how to Create PR :(

**Comment by TelepathicGrunt** [comment]
Thank you! This will be added and part of whatever future update gets released. Usually when I need to do a bugfix for something

**Comment by TskimiSeiran** [comment]
> Thank you! This will be added and part of whatever future update gets released. Usually when I need to do a bugfix for something
[zh_cn.json](https://github.com/TelepathicGrunt/Bumblezone/files/15367378/zh_cn.json)
Urrr...I found some wrong word,My fault :(
This version file fixed some wrong word,Thanks Author to update it!

**Comment by TskimiSeiran** [comment]
> Thank you! This will be added and part of whatever future update gets released. Usually when I need to do a bugfix for something

Urrr...I found some wrong word on that file,Is my fault,Sorry:(
This version file fixed these wrong word,Thanks Author to update it!
[zh_cn.json](https://github.com/TelepathicGrunt/Bumblezone/files/15369578/zh_cn.json)
