### ISSUE TITLE
Compat error with Neurina

### ISSUE THREAD

**Issue by AriaThePeryton** [TelepathicGrunt/Bumblezone#383]
Fighting The Essence of Continuity with (ANY) range weapons will delete projectiles.

**Comment by TelepathicGrunt** [comment]
The laser attack from the Cosmic Crystal Entity is supposed to destroy projectile. Do not shoot into the lasers. Shoot it from behind or when it is not shooting the laser

**Comment by TelepathicGrunt** [comment]
Otherwise, if you’re not shooting into the laser, I need more info such as a video of the issue and the exact modpack you’re using. As well as your latest.log file. And why you think neurina is involved

**Comment by AriaThePeryton** [comment]
Will do!
Did remove Neurina and now its crashing

modpack is Prominence 2 [RPG] (latest version being 2.8.3)

The added on mods that were added were CPM, simple animated guns and Mythic Metals.
Had tried getting a hold of their staff recently but seeing as I had modified their pack, I got no help from their staff.

**Comment by TelepathicGrunt** [comment]
Neurina’s goal is to swallow crashes instead of letting the game fully crash. Keep neurina off and reproduce the crash. Then give me that latest.log file. This will show me the code path leading to the crash. (You can out neurina back on after this)

**Comment by AriaThePeryton** [comment]
hope this helps!
[latest.log](https://github.com/TelepathicGrunt/Bumblezone/files/15320949/latest.log)

**Comment by TelepathicGrunt** [comment]
This is apoli error. They need to adjust their mixin code to be safer

Caused by: java.lang.NullPointerException: Cannot invoke "java.util.Optional.isPresent()" because "this.apoli$shouldApplyArmor" is null
	at net.minecraft.entity.LivingEntity.handler$bef000$apoli$modifyArmorApplicance(LivingEntity.java:13829) ~[client-intermediary.jar:?]

**Comment by TelepathicGrunt** [comment]
This was fixed already by Apoli. 
https://github.com/apace100/apoli/issues/177

you should be able to update apoli or Origins and the issue goes away

**Comment by AriaThePeryton** [comment]
thank!!!

**Comment by TelepathicGrunt** [comment]
I decided to backport Apoli's 1.20.2 fix to 1.20.1 by making a small mixin mod to specifically fix this
https://legacy.curseforge.com/minecraft/mc-mods/origins-apoli-armor-mixin-fix

This will stop the crash with Bumblezone
