### ISSUE TITLE
Bisect hosting server crashing from something in the bumblezone

### ISSUE THREAD

**Issue by Shiromajlov03** [TelepathicGrunt/Bumblezone#385]
Breakdown off what happened two players entered the bumblezone one went towards unloaded chunks and as they loaded in the server crashed and when they tried to rejoin the server kept crashing

Innitial crash report
[crash-2024-05-16_14.30.11-server.txt](https://github.com/TelepathicGrunt/Bumblezone/files/15340019/crash-2024-05-16_14.30.11-server.txt)

Rejoin crash report
[crash-2024-05-16_14.38.15-server.txt](https://github.com/TelepathicGrunt/Bumblezone/files/15339956/crash-2024-05-16_14.38.15-server.txt)

**Comment by TelepathicGrunt** [comment]
This is not a Bumblezone crash. This is a crash from Stars mod with an unsafe mixin. Stars in the fabric port of tinkers. Update tinkers or download newer stars to stop the crash

![IMG_0916](https://github.com/TelepathicGrunt/Bumblezone/assets/40846040/0c369b14-3d41-409e-a9e7-978c16aece48)
![IMG_0917](https://github.com/TelepathicGrunt/Bumblezone/assets/40846040/f8a1751f-6452-4fb1-af65-6fb99ebfe5c7)

**Comment by Shiromajlov03** [comment]
thank you for the quick response
