### ISSUE TITLE
Cant seem to find mod to add to a mod pack

### ISSUE THREAD

**Issue by Emre90901** [TelepathicGrunt/Bumblezone#386]
Im just creating a modpack for the first time and cant seem to find the bumblezone on cursed forge

The Modpack is in 
Forge - 47.2.0
and minecraft verstion 1.20.1

Is there something im missing as to why i cant add it to the folder

**Comment by TelepathicGrunt** [comment]
???
https://www.curseforge.com/minecraft/mc-mods/the-bumblezone-forge/files/all?page=1&pageSize=20&version=1.20.1

**Comment by TelepathicGrunt** [comment]
Closing as my mod is present on curseforge for 1.20.1 forge. Searching Bumblezone curseforge brings up the modpage so it exist. Curseforge app finds the mod when I do the search there too.
