### ISSUE TITLE
[1.16.4 + Mohist] Dying or teleporting to and from the Bumblezone will crash the Mohist server.

### ISSUE THREAD

**Issue by binglingyao** [TelepathicGrunt/Bumblezone#39]
Game Version: 1.16.4
Server Core: mohist(Forge+Spigot)
Forge: 35.1.13
Mod Version: the_bumblezone-1.16.4-2.2.8

Issues:
-Clicking the rebirth button after a player dies will cause a server error.
(This error will not cause the server to crash completely, but it will cause the player to be unable to access the server and search for it.)

More information:
- An error has been reported in the background of the server. This MOD is displayed.
- This problem has been tested multiple times, including but not limited to separately installing the_bumblezone

Error logs:
[Error.txt](https://github.com/TelepathicGrunt/Bumblezone/files/5728919/Error.txt)

The log:
[latest.log](https://github.com/TelepathicGrunt/Bumblezone/files/5728924/latest.log)

**Comment by TelepathicGrunt** [comment]
Rebirth? Do you mean the respawn button? Cause the game is dying at this line saying the capability attached to the player doesn't exist which shouldn't be possible. hmm
https://github.com/TelepathicGrunt/Bumblezone/blob/5a653cd2609a8d71a51472ab646ebfa1fdb894eb/src/main/java/com/telepathicgrunt/the_bumblezone/entities/PlayerTeleportation.java#L48

**Comment by binglingyao** [comment]
Yes! Respawn button.

**Comment by TelepathicGrunt** [comment]
I'm testing right now in my dev environment with a server and no matter what I do, I can't get this crash at all when I die and try to respawn. I think this may be a mod incompatibility issue with another mod doing something strange. Can you give me the zipped up mod folder or something so I can test with just forge and those mods on?

**Comment by TelepathicGrunt** [comment]
Actually, scratch that, can you test this build and see if this fixes the crash and teleporting between the dimension works ok? I tried a fix

[the_bumblezone-1.16.4-2.2.9b.zip](https://github.com/TelepathicGrunt/Bumblezone/files/5730962/the_bumblezone-1.16.4-2.2.9b.zip)

**Comment by binglingyao** [comment]
I can't give you a MOD pack for packaging because I can't upload it. but I can give you the mod list
- mcws-roofs-2.0.0-mc1.16.4
- mcw-bridges-1.0.4-mc1.16.4
- TravelersBackpack-1.16.4-5.3.1
- BetterCaves-1.16.3-1.0.6
- BetterMineshafts-Forge-1.16.3-1.1
- Aquaculture-1.16.4-2.1.7
- concreteconversion-1.16.4-6.1.0.0-forge
- pamhc2trees-1.16.3-1.0.0
- pamhc2crops-1.16.3-1.0.1
- pamhc2foodextended-1.16.3-1.0.0
- pamhc2foodcore-1.16.3-1.0.0
- CustomSkinLoader_Forge-14.13-SNAPSHOT-199
- bambooeverything-1.16.3-forge-1.0.0
- glassential-forge-1.16.4-1.1.5
- the_bumblezone-1.16.4-2.2.8
- BiomesOPlenty-1.16.4-13.0.0.425-universal

**Comment by binglingyao** [comment]
You have successfully fixed the death crash bug.
Death in [Forge server] does not crash and can enter the world, and death in the world does not crash!
After confirming this message, I changed the server core for testing
- Mohist core(forge+spigot) It will no longer crash at death, but it will crash at the end of particle effects when entering the world of this mod. I don't know if it's the core issue or what.
[Error.txt](https://github.com/TelepathicGrunt/Bumblezone/files/5731049/Error.txt)
[mods.zip](https://github.com/TelepathicGrunt/Bumblezone/files/5731056/mods.zip)

**Comment by binglingyao** [comment]
Tried uploading files, and fortunately it worked this time!It was not successful before!

**Comment by TelepathicGrunt** [comment]
Ok I ran the mods with a Forge only server and tried respawning after death and teleporting to the bumblezone. No crash. I think it's something with spigot that is removing the Forge capability from the player. A capability is basically a Forge API that allows modders to attach extra data to the player. Bumblezone uses this so it can store the player's last dimension and position they were at when the teleport to the Bumblezone so that they can got back to their original place when leaving. However, something is removing the capability from the player which means there's no more data as to what dimension the player came from or where they were. Meaning, without the capability, Bumblezone's teleportation cannot work at all.

Sorry but I can't seem to figure out exactly why it is breaking. If anything, missing capability on the player is something that Forge should fix but why it is happening is super weird. I'll ask around a bit to see if anyone has an insight into this

**Comment by binglingyao** [comment]
Thank you very much!Now I will temporarily play in The Forge server and wait for the fix solution. I guess this is a problem brought by the Mohist core. I will try to ask the development team of this core.

**Comment by TelepathicGrunt** [comment]
Yeah, I asked some friends and they say it is most likely on Mohist's end. I just made an issue report on their GitHub page so hopefully they can investigate and fix it soon!

**Comment by binglingyao** [comment]
oh!I'm getting ready to give feedback to their Github, and you're one step ahead of me!Thank you very much!I will always pay attention to the update and repair progress of Mohist core!
May your project get better and better!

**Comment by TelepathicGrunt** [comment]
I forgot to close this after modhist said they added capabilities 13 days ago lol. Bumblezone teleportation should be working on modjist now I think? Hopefully. Lmk if there’s any new issue!
