### ISSUE TITLE
Bumblezone crashes with Hephaestus 1.20.1-3.6.4.273 due to internal Star mod broken mixin

### ISSUE THREAD

**Issue by PaskaDev** [TelepathicGrunt/Bumblezone#390]
found a issue that crash the Minecraft world in 1.20.1 Minecraft after joining the bumblezone dimension with the mod version the_bumblezone-7.3.7+1.20.1-fabric.
here is my error file:

[crash-2024-05-17_22.47.19-server.txt](https://github.com/TelepathicGrunt/Bumblezone/files/15358208/crash-2024-05-17_22.47.19-server.txt)

**Comment by TelepathicGrunt** [comment]
Repeat of https://github.com/TelepathicGrunt/Bumblezone/issues/385 , https://github.com/TelepathicGrunt/Bumblezone/issues/389

Hephaestus's internal mod called Star is the problem. Hephaestus needs to update to fix the issue. Nothing I can do.

**Comment by TelepathicGrunt** [comment]
Fix was released https://www.curseforge.com/minecraft/mc-mods/hephaestus-fabric/files/5368070
