### ISSUE TITLE
Server shuts down upon entering/exploring the bumblezone 1.20.1 7.3.8

### ISSUE THREAD

**Issue by MatthewGalper** [TelepathicGrunt/Bumblezone#394]
error i see in log before shut down is this listed 3 times in a row

[net.minecraft.world.level.levelgen.heightproviders.UniformHeight/]: Empty height range: [6 above bottom--1 absolute]

**Comment by TelepathicGrunt** [comment]
Please share your full latest.log file from the server when it crashes. That entry is not from Bumblezone btw as I do not have any placedfeatures with an absolute y value set to 1. You're crashing from something else and I need the log to see what.

If you are playing AoF7, Hephaestus is crashing my mod but they are updating soon. If you are playing Prominence II, update the modpack as they updated Bosses of Mass Destruction as it's Void Lily flower was crashing and Bumblezone spawned some.

**Comment by MatthewGalper** [comment]
It is a custom mod pack. The weird part is the server isnt crashing but shutting itself off so no crash log. but i do have the latest log like you asked. On another note if you happen to know what causes nbt 128471 is null that would be awesome. Totally understand if not. 
[latest(1).log](https://github.com/TelepathicGrunt/Bumblezone/files/15419813/latest.1.log)

**Comment by TelepathicGrunt** [comment]
The latest.log file there has nothing in it. If this was a deadlock/freeze, the server's watchdog should've crashed the server after 60 seconds of a stuck tick and print out a thread dump into the lot file to show what code the server was stuck on. Are you sure this log is obtained right after the issue happened? If the server is started up again, it'll overwrite the latest.log file with the new current session when we need the past session that led to the issue.

Otherwise, I would need your modpack (either exported and linked to download from dropbox or google drive. Or just the zip dropped here if it is a CF export which doesnt have the jar files to bloat it)

Lastly, I do not know what you mean by nbt 128471.

**Comment by MatthewGalper** [comment]
Yeah that's why I'm struggling to identify the problem on my own.
Unfortunately as mentioned the server isn't crashing but rather something
is triggering the shut down process as if I type /stop or hit the stop
button.

I shut down the server. Cleared log. Started server. Jumped into BZ. Server
shut down.  That log is everything from start to finish. I'll check the lot
files.


Modpack is here

Leave out oculus, embeddium + embeddium add-ons. Those are client side
only.

https://drive.google.com/drive/folders/1sgJmMgbzHLfohqzYzHeApm8E4c4bMNrp?usp=sharing

And darn ok. Its a persistent problem for me though no one else seems to be
getting it.

**Comment by TelepathicGrunt** [comment]
Apologies. I didn't realized you had responded. I don't have a server to run the modpack atm but I ran it in single player and was able to enter bumblezone and fly around for a while with no issue.

(Note, turn off shaders when in my dimension. Shaders cannot handle dimensions with a roof and will not respect dimension mod's ambient lighting values)

Also another tip, make sure you are on latest embeddium and turn on Translucency Sorting. It fixes a lot of transparency issues with transparent blocks

**Comment by TelepathicGrunt** [comment]
Otherwise, try making a backup of your server. Then start removing mods from server till you find cause. Might be mod incompat issue. Start with removing connector in case there's an issue there as it can get quite glitchy running fabric mods on forge

**Comment by MatthewGalper** [comment]
Yeah I'm able to fly around solo fine as well. Seems exclusively a server
issue. I'll try on server without shaders on and see if that helps.

**Comment by TelepathicGrunt** [comment]
Any luck finding the problematic mod? I am still not seeing anyone else with anything similar for an issue

**Comment by MatthewGalper** [comment]
No. As far as I can tell it's a conflict in ceiling hight for world gen or
Alex's caves cave air as those 2 show up when it happens. But only in new
areas. So we've just been exploring more slowly.

**Comment by TelepathicGrunt** [comment]
I'm gonna close this for now but if you find a reproducible case for the issue with a minimal set of mods and it does require my mod on to happen, I'll take another look
