### ISSUE TITLE
Impossible to complete Slimy Mitosis advancement

### ISSUE THREAD

**Issue by olazermii** [TelepathicGrunt/Bumblezone#397]
I am trying to complete The queen’s desire questline but I can’t get the Slimy Mitosis advancement where you have to breed 6 honey slimes. I already did it many times but i disn’t receive the advancement. When I use the command /bumblezone_read_self_data for this quest it always says that I have bred 0. It’s the last advancement I have to complete and this is quite frustrating.

**Comment by TelepathicGrunt** [comment]
I need minecraft version, modloader, and the exact modpack you’re playing on in order to reproduce the issue and fix it

**Comment by olazermii** [comment]
I am currently playing in 1.20.1 with the v25 of the Fabric Better Minecraft modpack (BMC2)

**Comment by TelepathicGrunt** [comment]
v7.4.2 fixes the issue now. Modpack would need to update
