### ISSUE TITLE
[Neos 1.20.4] - Bee Variants Ignore Flower Headwear

### ISSUE THREAD

**Issue by AriaElidove** [TelepathicGrunt/Bumblezone#398]
I'm not sure if this is intended behaviour, so I feel I should report it. Vanilla Bees have no issue with being lured in by the Flower Headwear (tested with Curios and Helmet slots)

The Bumblezone - 7.5.3
NeoForge - 20.4.237

**Comment by TelepathicGrunt** [comment]
Likely bug but will only fix it in 1.20.1 and 1.21 as those are now my supported versions

**Comment by TelepathicGrunt** [comment]
Appears to be working for me
![image](https://github.com/TelepathicGrunt/Bumblezone/assets/40846040/b76d1da7-1951-486b-9b0f-d37ce1a82246)

Checking the code, I see no way that the behavior could be different between the bees either. The Bee Variant mob actually extends the vanilla Bee so they inherit the same exact AI as vanilla bees. Anything that happens to vanilla bees will impact variant bees

**Comment by TelepathicGrunt** [comment]
Closing as no new info and doesnt seem to be reproducible. Please reopen if you can recreate issue in 1.20.1 or 1.21
