### ISSUE TITLE
[1.21] Does not work on server

### ISSUE THREAD

**Issue by NielsPilgaard** [TelepathicGrunt/Bumblezone#400]
Hi 👋 

Bumblezone does not allow my server to start unfortunately 😄 

[crash report](https://gist.github.com/NielsPilgaard/1d24f9b971b24b3d6dc64b176be775e6)

- the_bumblezone-7.6.1%2b1.21-neoforge

**Comment by TelepathicGrunt** [comment]
Something changed with classloading I think

**Comment by TelepathicGrunt** [comment]
Fixed with https://github.com/TelepathicGrunt/Bumblezone/commit/7a0faa40c1c8cc9e1ef890c9027c55a1556ff47e

**Comment by NielsPilgaard** [comment]
Thanks 👍
