### ISSUE TITLE
[1.21] Players cannot join servers that has the bumblezone installed

### ISSUE THREAD

**Issue by NielsPilgaard** [TelepathicGrunt/Bumblezone#402]
👋 

I re-added the Bumblezone, the server was able to start which was nice, but I was unable to join it. I get thrown out to the main menu a few seconds after trying to join.

relevant exert: https://gist.github.com/NielsPilgaard/bf559f23e8acfad74ad2eed262dc2acc
latest.log: https://gist.github.com/NielsPilgaard/5c6dcf2f8bbfefd509195bcbdf014b52

**Comment by TelepathicGrunt** [comment]
I am able to connect to a server with bumblezone on
![image](https://github.com/TelepathicGrunt/Bumblezone/assets/40846040/d26260fa-c4fa-48c6-b14e-4bb410cc876c)

Reading your logs, I don't see how Bumblezone comes into play. I do see this
` TRANSFORMER/relics@0.7.1/it.hurts.sskirillss.relics.system.casts.handlers.CacheHandler.onPlayerTick(CacheHandler.java:26)`

Is Relics mod doing anything special? Have you reached out to them with this log?

**Comment by TelepathicGrunt** [comment]
Yep. Not a Bumblezone issue. Relics is using a clientside class directly in common code. This will always crash servers.
https://github.com/SSKirillSS/relics/blob/d0e2196ce6c7139b61acac9c799548db43b8366c/src/main/java/it/hurts/sskirillss/relics/system/casts/handlers/CacheHandler.java#L26

They need to switch to doing `!level.isClient()` check as that's safest
@SSKirillSS heads up, this is coming your way

**Comment by NielsPilgaard** [comment]
Oh I see, sorry for the wrong report, and thank you for helping regardless 😊

**Comment by TelepathicGrunt** [comment]
Closing here since I am moving this issue report to Relic: https://github.com/SSKirillSS/relics/issues/144
