### ISSUE TITLE
Version Broken for NeoForge 1.21, Game telling us we need a different version of the Modloader

### ISSUE THREAD

**Issue by ModernGamingWorld** [TelepathicGrunt/Bumblezone#404]
![Screenshot 2024-06-24 111327](https://github.com/TelepathicGrunt/Bumblezone/assets/75923060/00bb18f4-5ec4-4657-b333-5071d9e4d101)

![2024-06-24_11 13 48](https://github.com/TelepathicGrunt/Bumblezone/assets/75923060/62698171-8dc8-4ffe-a810-bff1514ec977)

**Comment by TelepathicGrunt** [comment]
No it is correct. Downgrade neoforge. 31 added breaking changes for damage events. My mod will literally crash and break on that version or have broken behavior. That’s why I added the version restriction for now until I implement the new damage events

**Comment by TelepathicGrunt** [comment]
Update v7.6.6 released to support v21.0.40-beta or newer neo
