### ISSUE TITLE
Fluid Blocks particles have no texture

### ISSUE THREAD

**Issue by FlyingFalcon33** [TelepathicGrunt/Bumblezone#405]
Fluid blocks (honey fluid, royal jelly fluid, sugar water) are missing falling particles

Steps to reproduce:
1. Place fluid under a trapdoor/carpet block
2. fall onto trapdoor from height of greater than or equal to 4 blocks
3. observe missing texture particles (see screenshot)

![2024-07-04_12 48 16](https://github.com/TelepathicGrunt/Bumblezone/assets/174735657/2bb69994-6cee-4e52-902a-4b4e8e7ea7cd)

**Comment by TelepathicGrunt** [comment]
Err shouldn’t it be no particles instead. I’ll check vanilla fluids

**Comment by TelepathicGrunt** [comment]
Also what Mc version

**Comment by FlyingFalcon33** [comment]
the most recent forge for 1.20.1 version, I don't know about the fabric/quilt/neoforge ones or the 1.21 ones

**Comment by TelepathicGrunt** [comment]
fixed with https://github.com/TelepathicGrunt/Bumblezone/commit/cf9e1031bc911bf7e9f8344ed7c35f88cd52d44d
