### ISSUE TITLE
1.21 Neoforge Harvesting Honey Crystals is messed up

### ISSUE THREAD

**Issue by Inonedn** [TelepathicGrunt/Bumblezone#406]
NeoForge: 21.0.55-beta
MC Version: 1.21

Intended Behavior: Breaking a Honey Crystal/Block without silk touch would yield the crystals, and fortune would give more crystals

Actual Result: Messed up behavior

**Comment by TelepathicGrunt** [comment]
Again, like I have said before, I need more info. 

What exactly is the issue. How are you getting the issue. What mc version and modloader

**Comment by TelepathicGrunt** [comment]
fixed now with https://github.com/TelepathicGrunt/Bumblezone/commit/4694e581943bd249057dceb29d5eb3802603894c
