### ISSUE TITLE
1.21 NeoForge Right clicking fluids with bucket gives water instead

### ISSUE THREAD

**Issue by Inonedn** [TelepathicGrunt/Bumblezone#407]
NeoForge: 21.0.55-beta
MC Version: 1.21

Intended Behavior: Using buckets on fluids gives the respective fluid bucket

Actual Result: You only get a water bucket instead

**Comment by TelepathicGrunt** [comment]
Again, like I have said before, I need more info. 

What exactly is the issue. How are you getting the issue. What mc version and modloader

**Comment by Inonedn** [comment]
Uploading Minecraft NeoForge_ 1.21 - Singleplayer 2024-07-04 15-05-36.mp4…

**Comment by Inonedn** [comment]
https://github.com/TelepathicGrunt/Bumblezone/assets/36087299/a952b915-9d5d-4b24-b657-5851f295ba94

**Comment by TelepathicGrunt** [comment]
fixed now with https://github.com/TelepathicGrunt/Bumblezone/commit/0ed6d5de49b2e255717665e8843dbdde4a7febca
