### ISSUE TITLE
[1.20.4 / Neoforge] Casting exception during NeurotoxinsEnchantment

### ISSUE THREAD

**Issue by BluSunrize** [TelepathicGrunt/Bumblezone#409]
We had a crash on our server @AriaElidove probably has more information on exactly how it was triggered.

From the stacktrace, it happens with a mixin making a wrong assumption in casting?

https://gist.github.com/BluSunrize/b396a01535af5071dc5d8f7c236dc75a

**Comment by TelepathicGrunt** [comment]
this was fixed in 1.21 and 1.20.1. I stopped supporting 1.20.2 to 1.20.6 as they are basically becoming dead versions now.

The issue was neurotoxin enchantment used on a serverplayer was trying to be casted into a Mob accessor because I messed up an instanceof check.
