### ISSUE TITLE
Not able to ender dimension

### ISSUE THREAD

**Issue by Gaiyamato** [TelepathicGrunt/Bumblezone#41]
Making a 1.16.4 modpack with Forge 35.1.28 I don't seem to be able to enter the Bumblezone at all. 
Nothing at all in logs even mentioning Bumblezone. 

I throw the ender pearl and nothing happens. I'm just teleported to the block as normal. 

This was working with the same modpack in the 15.2 version.

**Comment by Gaiyamato** [comment]
Never mind. Turns out that when using Overwolf, if you disable Productive Bees using the toggle button it also decides that Bumblezone requires it, and disables the mod due to dependencies. Manually re-enabling the mod solved it.

**Comment by TelepathicGrunt** [comment]
wack. I have productive bees listed as an optional dependency so overwolf shouldn't be disabling bumblezone when productive is off. This might be something overwolf should know about so they can fix that behavior lol.
