### ISSUE TITLE
Stinger Spear Shrine doesn't generate the Stinger Spear on it

### ISSUE THREAD

**Issue by Inonedn** [TelepathicGrunt/Bumblezone#410]
Neoforge Version: 21.0.76
Minecraft Version: 1.21

When generated through commands or encountered, the stinger spear shrine's stinger spear is not there

**Comment by TelepathicGrunt** [comment]
https://github.com/TelepathicGrunt/Bumblezone/commit/2ccca1cfa962b48888a81461eacfcce4622ffa9c
