### ISSUE TITLE
Crash in White Sempiternal Boss

### ISSUE THREAD

**Issue by Inonedn** [TelepathicGrunt/Bumblezone#411]
NeoForge version: 21.0.76
Minecraft Version: 1.21

[crash-2024-07-08_19.51.51-server.txt](https://github.com/user-attachments/files/16135402/crash-2024-07-08_19.51.51-server.txt)

**Comment by TelepathicGrunt** [comment]
issue with neoforge new damage container system and cosmic crystal

**Comment by TelepathicGrunt** [comment]
https://github.com/TelepathicGrunt/Bumblezone/commit/a7c34f183eff51067fc6c11f6c0d0722e41923f1
