### ISSUE TITLE
Chest Blocks in Hive shift inventory rows down

### ISSUE THREAD

**Issue by EligibleUsername** [TelepathicGrunt/Bumblezone#413]
So I've encountered an interesting bug: Opening the chest-blocks (forgot the name) in a hive cause all my inventory rows to shift down a row, making my hotbar-row invisible and replacing it with the lowest row from my inventory. Also the chests I opened (about 8 or 9) all only had one item in the upper left corner, which was one purple candle. When closing the chest and opening my inventory again, the rows shifted back up. While playing around with this bug I switched to Creative mode to stop the bees from attacking me which then lead to this: the rows shifted down again, but the top row of my inventory cloned itself, staying in the top row AND now occupying the middle row. This then caused the hotbar-row to be deleted. After sorting my inventory and/or pasting all inventory contents in a normal chest I could see that the items previously in my hotbar were now gone. This was reproducible by me and other players. Sidenote: another hive and many other of the same type of chest did not yield this bug beforehand. I can provide pictures later on.

**Comment by TelepathicGrunt** [comment]
Update Lootr. I’m guessing you’re using a lunar pixel modpack where they have an outdated lootr version.

**Comment by TelepathicGrunt** [comment]
Gonna close as I am 99% sure this is just outdated Lootr. This issue was fixed a while ago. Just some modpacks have not updated lootr and bumblezone since then
