### ISSUE TITLE
Attempting to enter the Bumblezone crashes the server (Quilt 1.20.1)

### ISSUE THREAD

**Issue by MrGenie151** [TelepathicGrunt/Bumblezone#414]
We keep attempting to enter it, but every time we do the server lags out and crashes. The server runs decently most of the time, and we have a lot of optimization mods to attempt to compensate for Minecraft's shortcomings.
What's going on?

**Comment by TelepathicGrunt** [comment]
I would need the latest.log file from the server after it crashes.

**Comment by MrGenie151** [comment]
It was a memory issue, I have fixed it

**Comment by dyson-m** [comment]
Apologies for necroing, but could you give me a push in the right direction on how you solved this @MrGenie151 ? My server is also crashing from entering the Bumblezone dimension. I even tried pre-generating chunks without entering the dimension and that crashed too. I'm guessing it's a memory issue for me as well.

**Comment by TelepathicGrunt** [comment]
Logs people. I need latest.log file after the crash happens to actually diagnosis the issues pls
