### ISSUE TITLE
The block image is not visible.

### ISSUE THREAD

**Issue by pil0lo** [TelepathicGrunt/Bumblezone#415]
The block is not visible.
![1](https://github.com/TelepathicGrunt/Bumblezone/assets/143984023/26156545-9541-43b8-9411-e81cc5d51360)
![1](https://github.com/TelepathicGrunt/Bumblezone/assets/143984023/53ed5eee-2d5f-4601-8f65-fc6ab14ee54b)

And how do you get out of the beehive after entering it?

**Comment by TelepathicGrunt** [comment]
@pil0lo put on Indium mod. Sodium is a janky mod that release builds that do not use Fabric API for rendering and as a result, breaks mods. Indium is a mod that forces Sodium to use Fabric API properly. You should not run Sodium without Indium.

To leave Bumblezone, go above y = 256 or y = 0. See the Bumblezone advancements for more details about the dimension. My mod page also has a wiki linked with even more info about my dimension.
