### ISSUE TITLE
1.21 NeoForge: Crystalline Flower Crash

### ISSUE THREAD

**Issue by Inonedn** [TelepathicGrunt/Bumblezone#418]
[crash-2024-07-11_21.12.56-client.txt](https://github.com/user-attachments/files/16185901/crash-2024-07-11_21.12.56-client.txt)

**Comment by TelepathicGrunt** [comment]
Im gonna need more info. Exactly what steps did you take to do the crash

**Comment by Inonedn** [comment]
I enchanted a book with the Crystalline Flower, and it suddenly crashed. It doesn't always do this though, but I did do Sharpness 5

**Comment by TelepathicGrunt** [comment]
I started up a server, connected to it, and used the flower for a ton of enchantments and I did not get any crashes
![image](https://github.com/user-attachments/assets/3312b8d0-9ae3-4951-a493-b0cda1f5e1fb)

Not seeing how the issue could happen tbh in code. I would like a link to download your entire modpack to narrow down cause.

**Comment by TelepathicGrunt** [comment]
If you do not want to share your modpack with me, you could try this jar and report if it works. I took an educated guess as to where the issue could be but I have no idea if it will actually stop the crash.
https://www.dropbox.com/scl/fi/n8v2jln82ia7bcu4bxhue/the_bumblezone-7.6.16-beta-1.21-neoforge.jar?rlkey=wuugfbzekbcu6gp6xhyqfzb1b&st=1wvhjkyr&dl=0

**Comment by TelepathicGrunt** [comment]
Closing due to no more response and feedback. new build is out that *might* fix issue but dunno.
