### ISSUE TITLE
Invisible Texture

### ISSUE THREAD

**Issue by wubluuu** [TelepathicGrunt/Bumblezone#419]
The "Porous Honeycomb Block" is invisible in certain conditions, like shown in the screenshots. It is not my texture packs as I've tried to disable all and it changed nothing.

![image](https://github.com/user-attachments/assets/724b96b1-43e2-469e-8d46-0b872ebd1e7e)

![image](https://github.com/user-attachments/assets/17e4270c-7934-41f2-b771-85c7d86b9b62)

**Comment by TelepathicGrunt** [comment]
put on Indium mod. Sodium is a janky mod that release builds that do not use Fabric API for rendering and as a result, breaks mods. Indium is a mod that forces Sodium to use Fabric API properly. You should not run Sodium without Indium.
