### ISSUE TITLE
Error msg in log

### ISSUE THREAD

**Issue by Zygus42** [TelepathicGrunt/Bumblezone#42]
I'm seeing this in my log: "[07Jan2021 21:08:55.029] [Server thread/ERROR] [Portal/]: Missing dim type id for ResourceKey[minecraft:dimension / the_bumblezone:the_bumblezone]"

Is this something you need to look into ?

the_bumblezone-1.16.4-2.2.8
forge-1.16.4-35.1.29

**Comment by TelepathicGrunt** [comment]
Is there any issue in game? Are portals working and no dimension is broken or missing? Logs sometimes say stuff that don't actually have an impact so I would like to know if something is actually wrong lol.

**Comment by Zygus42** [comment]
I'm still building the modpack, so haven't done that much indepth testing.  Just saw this msg in passing through the log and thought i'd pass it on.   I'll let you know if I find anything more concrete.

**Comment by TelepathicGrunt** [comment]
Ah understood. Just be wary of this mojang bug where removal of any dimension could cause other mod's dimension or vanilla dimensions to disappear so be sure to make a new world each time you are adding/removing dimension mods to make sure it is working.
https://bugs.mojang.com/browse/MC-197860

**Comment by TelepathicGrunt** [comment]
closing this as nothing new came up. Just open a new issue report if something comes up with bumblezone!
