### ISSUE TITLE
[1.21 Fabric] Running Minecraft programs crash when using Bee Cannon

### ISSUE THREAD

**Issue by Goo-aw233** [TelepathicGrunt/Bumblezone#420]
[crash-2024-07-16_23.35.01-server.txt](https://github.com/user-attachments/files/16253381/crash-2024-07-16_23.35.01-server.txt)

Only Bee Cannon has been found to cause this problem, Crystal Cannon or others have not been found to crash the program yet

P.S. Tested to cause this issue when adding bees in using Bee Cannon

**Comment by TelepathicGrunt** [comment]
Should be fixed now in new release
