### ISSUE TITLE
Severe Lag Issues - 1.20.1 - Latest - Forge - Modpack

### ISSUE THREAD

**Issue by TheGameAce** [TelepathicGrunt/Bumblezone#423]
So I'm not really sure what's going on here. I put together a little modpack for myself and some friends in 1.20.1. I'd used this mod in a previous pack I put together back in 1.18.2 with no real issues.

When testing this newer pack while still developing it, I noticed it was quite laggy even for moderate render (maybe 12 - 14 chunks; 6 - 8 simulation) and simulation settings. Turned down the values to about 5 and 6 respectively, had a little lag still but was otherwise doing OK at that point. Didn't touch it again until just now, deciding to finally explore it in my survival run. By this point I'd turned my render and simulation up to maximum since my computer seemed completely fine on those settings. But the second I entered the dimension, lag struck. Hard.

Lagged so badly I couldn't do a thing. Took a good minute to get out and pull up task manager to give my client the boot. Re-loaded, significantly decreased render and simulation (5 and 6, respectively). Re-entered the dimension (since it didn't save me going in), more severe lag. Better than before (could see things and see movement between freezes), but still unplayable. Tried to lower to minimum settings, still no change. Forced out, re-launched my client again, started back in with the minimal settings. Finally playable with only minor hiccups at 2 render distance.

Started a Spark profiler after I got back in without issues. Ran around a bit, had one or two freezes, but only for a moment. Turned render distance up to 4, lag significantly increased. Turned it back down to 3 after stopping the profiler, and it seems to be comfortable, though still glitchy.

Profiler results: https://spark.lucko.me/fsWlY2C8WS
Unfortunately my capacity for reading these reports is limited, though it does seem to return results similar to what I saw via my task manager. The times I had to force out, CPU use maxed out and RAM use got pretty close.

If you need any more information, just let me know.

**Comment by TelepathicGrunt** [comment]
![image](https://github.com/user-attachments/assets/d92baf4e-b15d-4ce9-9b27-e9d7047937c0)

Something is pausing the server thread to do something on another thread. It doesn't say what. if you can get spark to profile all the threads instead of server thread, it might lead to the offending mod. Or at least, what the offending mod is actually doing. If the modpack is uploaded online, link it please as I can do my own profiling too if you are unable to work out spark

**Comment by TheGameAce** [comment]
Running a new profiler on all threads. Will post at the end. If you want to take a look for yourself, the pack is just via Dropbox at the moment: https://www.dropbox.com/scl/fi/6t52kshlzsthcbbehtsby/Modpack-Mods-Configs.zip?rlkey=v4148wgha4gjjyfgilopweyuq&st=ba293juk&dl=0

A few configs will be different since I've edited some since uploading, but it shouldn't be anything that would affect the results.

Latest profiler, presuming I ran it correctly (/spark profiler start --thread*): https://spark.lucko.me/M7oxoP2DSs

**Comment by TelepathicGrunt** [comment]
It does not seem like you got all threads. Having difficulty finding the root cause. But try removing Dynamic Trees and updating all mods and see if that helps.

**Comment by TheGameAce** [comment]
I'll give it another go later or tomorrow, including mod updates. Don't think it should be dynamic trees interfering. Reports during initial testing never indicated it was causing problems as far as I could tell. Also can't imagine why it would interfere with a dimension in which it has no relation to in any capacity.

**Comment by TelepathicGrunt** [comment]
Not every mod that interferes are related. For example, BetterEnd had some and probably still has some bad code where it grants regeneration effect to any mob that returns an empty list for armor slots. Which caused my Cosmic Crystal boss in Bumblezone to get the effect and become literally unbeatable at all. 

Removing mods till the memory stabilizes may be your best bet at finding which mod is hogging up the memory. When memory gets maxed out, the garbage collector runs to clean up the memory which causes big lag spikes. When memory is fully maxed out and garbage collector cant clean anything up, then game gets stuck and needs to be forced closed

**Comment by TheGameAce** [comment]
Back with a little update. Sorry it took me so long. Ran another profiler and pretty sure I got it on all threads this time: https://spark.lucko.me/VqgroROqBA

First time I've seen the profiler give results like that, so I can't read them even slightly.

Messed around with my mods over the last few days and couldn't quite find anything definitive. Added a few extra performance mods and they seem to have helped with the lag issues at least. A little bit. Can get render up to around 5 chunks now without any increased lag. Suspecting you're right that it has something to do with memory usage and GC though. Right now my presumption is that Bumblezone has fairly high memory usage, which is in conflict with something else using up quite a bit. Would also explain why I get brief freezes from time to time similar to the more frequent ones in Bumblezone, when I'm in other dimensions or the overworld.

**Comment by TelepathicGrunt** [comment]
Few things. 

Swap Rubidium with Embeddium. Rubidium is not maintained properly anymore. (And then update all mods)

By default, I think your pack is pretty much right up against the 6GB RAM limit. But something is eating up excessive amount to put over the limit and lock up the game. When I disable Tectonic, I recover like 2GB and the Bumblezone dimension seems to generate chunks smoother and not hit RAM limit.

Also, set these two configs to true in Modernfix's config file. This will do some optimization to try and lower the RAM usage as well.
![image](https://github.com/user-attachments/assets/22371caa-4763-4542-8efd-e04d1257b3b4)

But looks like Tectonic is the main offender for your pack

**Comment by TheGameAce** [comment]
Ah thank you very much for the assistance! I'll make those adjustments and see how it does, though it looks like I might not be able to remove Tectonic without possibly bricking my world... Dang that sucks though, the terrain generation is so nice. Ah well.

Pardon for any inconvenience this may have caused.

**Comment by TelepathicGrunt** [comment]
So the issue is I was using some density functions and noises from the vanilla side. Tectonic overwrote those density functions and noise and made them more resource demanding. Here, try this Bumblezone build. I made the dimension not use the vanilla density functions and noises and instead my own that is even less demanding. You should feel the dimension generate chunks much faster, smoother, and uses less RAM now that Tectonic does not run in my dimension anymore.

https://www.dropbox.com/scl/fi/8w8eehotsubm161x7x852/the_bumblezone-7.4.15-1.20.1-forge.jar?rlkey=jnnop7nsdbtc0pjeqr31ucktu&st=r46f45i0&dl=0

**Comment by TheGameAce** [comment]
That explains why Tectonic causes such issues ordinarily and anywhere it's active. Wondering if it's something they're aware of over there, and if this knowledge could help them alleviate the issues...

Thank you so much for that update! It's a literal gamechanger from what I'm experiencing so far. Went from constant lag and stutters even at minimal render + simulation to being completely buttery smooth even at a range of 30/16! :)

Wish I could do something to help you in return, but about all I can do is build structures. So I guess on the off-chance you ever need something like that, give me a shout.

**Comment by TelepathicGrunt** [comment]
New Bumblezone update released now with the fix and some mor eoptimizations to try and make chunk loading even faster.

I don't need anything in repayment. If you still decide to build some structures for Bumblezone for fun, you can send me the nbt files and I can try and incorporate them into Bumblezone to spawn! (Might adjust the builds to balance or fit better with the dimension if needed)
