### ISSUE TITLE
(1.21 NeoForge) Stinger Spear can't receive Loyalty or Impaling Enchantments

### ISSUE THREAD

**Issue by Inonedn** [TelepathicGrunt/Bumblezone#424]
Minecraft Version: 1.21
NeoForge version: 21.0.146
Mod Version: Latest (7.6.21)

Previously, the Stinger Spear could receive these enchantments, but it no longer can.

**Comment by TelepathicGrunt** [comment]
Uh it wasn’t supposed to get channeling or riptide enchantments. What version was it able to? Because that’s a bug. 

As per wiki: 
![IMG_1053](https://github.com/user-attachments/assets/f6c8e8b0-e653-4026-a3cd-7587c93da5ed)

**Comment by Inonedn** [comment]
1.20.1, but it cannot be enchanted with Loyalty or Impaling

**Comment by TelepathicGrunt** [comment]
I just tested 1.20.1 forge. It allowed me to enchant the spear with loyalty/impaling and not channeling/riptide. Which is what I want. 1.21 is not allowing loyalty/impaling due to a bug. channeling/riptide remains disallowed

**Comment by TelepathicGrunt** [comment]
fixed now
