### ISSUE TITLE
Im looking to play on 1.18.2, but it appears resourcefull-lib isnt available on this version. 

### ISSUE THREAD

**Issue by scarywoods** [TelepathicGrunt/Bumblezone#426]
Im looking to play on 1.18.2, but it appears resourcefull-lib isnt available on this version. Why are these versions listed if they arent compatible?

**Comment by TelepathicGrunt** [comment]
You don't need Resourceful lib in 1.18.2 Bumblezone. What is making you think that it is required? The curseforge page does not list resourceful lib as a required dependency. It only lists FeatureNBT Deadlock Be Gone as required
https://legacy.curseforge.com/minecraft/mc-mods/the-bumblezone-forge/files/3810570

(Though 1.18.2 and below bumblezone is barebones with like nothing. More content was added in 1.19.2 and even more stuff was added in 1.20.1)

**Comment by scarywoods** [comment]
![Screenshot 2024-08-02 223010](https://github.com/user-attachments/assets/3783d908-6e88-4a0e-987d-fab15fa39e81)
In the dependencies, Resourceful lib is listed as a dependency, thanks for clearing this up

**Comment by TelepathicGrunt** [comment]
That relation tab is for the latest file uploaded and not individual files where past versions could have different dependencies. This is a bad curseforge display yeah

**Comment by scarywoods** [comment]
Also, is there a possibility the newer content will be ported to more versions?

**Comment by TelepathicGrunt** [comment]
No I will not be backporting features. The workload is too extreme for me and my mod and mc's codebase both changed significantly from version to version. I rely on a lot of newer features and stuff from later minecraft and modloader versions that does not exist in older versions

**Comment by scarywoods** [comment]
K
