### ISSUE TITLE
Problems with Bukkit

### ISSUE THREAD

**Issue by Jorgesan1128** [TelepathicGrunt/Bumblezone#427]
The name of the mod classes are too long and exceeds the limit of 64 characters that it has by default.

Real example (and the reason that i'm posting this issue):

The error is because the custom payload channel name exceeds the 64 character limit allowed by Bukkit. In this case, the channel the_bumblezone:networking/the_bumblezone/crystalline_flower_enchantment is 71 characters long.

**Comment by TelepathicGrunt** [comment]
Not a Bumblezone issue. This is a Bukkit issue. Fabric, forge, and basically all modloaders have allowed longer names for channels for years now. Bukkit or whatever system you’re using for plugins needs to change their hardcoded legacy limit to catch up with the rest of the ecosystem

**Comment by TelepathicGrunt** [comment]
If you’re using paper, update it. See https://github.com/PaperMC/Paper/issues/10003

closing this due to nothing on my end
