### ISSUE TITLE
[Compat Suggestion] Bosses of Mass Destruction ender pearl

### ISSUE THREAD

**Issue by Cicopath** [TelepathicGrunt/Bumblezone#429]
Hi! I'm making my own modpack on Fabric 1.20.1 and I was going through the mod's item tags to add different items to them using KubeJS. I've added some new items to the different dimension teleportation tags, such as Bosses of Mass Destruction's Earthdive Spear in `#the_bumblezone:dimension_teleportation/item_right_clicked_beehive' and Mutant Monster's Endersoul Hand in `#the_bumblezone:dimension_teleportation/item_right_clicked_beehive_crouching`.

However, there's _one_ item that I wish would work as I want it to: Bosses of Mass Destruction's Charged Ender Pearl. This item acts similarly to an ender pearl, simply with extra safety precautions, but it doesn't actually work like an ender pearl to get inside the dimension. I was hoping compatibility could be added for this; I see Twilight Forest has one with the Ender Bow?

Thank you! :D

**Comment by TelepathicGrunt** [comment]
Add the charged enderpearl projectile to this tag:
https://github.com/TelepathicGrunt/Bumblezone/blob/1.20-Arch/common/src/main/resources/data/the_bumblezone/tags/entity_types/dimension_teleportation/teleport_projectiles.json

Should work

**Comment by Cicopath** [comment]
Oh I haven't even thought about entity type tags 🤦‍♂️ I've been working on making mods compatible via item tags first lol. Gonna do entity types next. Thank you for the solution (it's working now)!

If you were curious of the entity ID in case you wanted to add compatibility to your mod as a whole, the entity ID is `bosses_of_mass_destruction:charged_ender_pearl`.
