### ISSUE TITLE
NeoForge 1.21.1 White Sempiternal Boss destroys its own arena, even after death

### ISSUE THREAD

**Issue by Inonedn** [TelepathicGrunt/Bumblezone#431]
Minecraft Version: 1.21.1
NeoForge Version: 21.1.9

Bug: During the Boss Event, the Crystals will destroy parts of their own arena, even when they die and the event ends.
![2024-08-14_20 37 13](https://github.com/user-attachments/assets/b814fc7f-68c1-42c0-97fa-eccb16e5008e)

**Comment by TelepathicGrunt** [comment]
cosmic crystal destroying blocks in arena is intended and working fine. Cosmic crystal destroying blocks outside arena is the bug.
