### ISSUE TITLE
Suggestion: Allow Farmer's Delight knives to be enchantable with Comb Cutter

### ISSUE THREAD

**Issue by Inonedn** [TelepathicGrunt/Bumblezone#432]

**Comment by TelepathicGrunt** [comment]
In 1.21+, you can do so by adding the item to this item tag to allow Comb Cutter on it
https://github.com/TelepathicGrunt/Bumblezone/blob/1.21-Arch/common/src/main/resources/data/the_bumblezone/tags/item/enchantable/comb_cutter.json

In 1.20.1, you would add it to this tag
https://github.com/TelepathicGrunt/Bumblezone/blob/1.20-Arch/common/src/main/resources/data/the_bumblezone/tags/items/enchantable/comb_cutter.json

**Comment by TelepathicGrunt** [comment]
Just doubled checked and my Wiki does mention these item tags for the enchantments so should be discoverable hopefully
https://github.com/TelepathicGrunt/Bumblezone/wiki/Enchantments-%F0%9F%93%95

**Comment by Inonedn** [comment]
could it be made into a default feature though?

**Comment by TelepathicGrunt** [comment]
I can add it to the tag by default. I just needed to ask the dev first if it is ok that i do so in case it could conflict
