### ISSUE TITLE
(1.21 NeoForge) Comb Cutter does not take Efficiency into account

### ISSUE THREAD

**Issue by Inonedn** [TelepathicGrunt/Bumblezone#433]
NeoForge Version: 21.1.13

This may or may not be intended, but Efficiency does not affect Comb Cutter in cutting the assorted blocks.

**Comment by TelepathicGrunt** [comment]
Closing as vanilla behavior. Efficiency does not apply in vanilla if the tool is used on a block that the tool isn't for. Basically, only for blocks where the item's default destroy speed is greater than 1 does efficiency take effect.
![image](https://github.com/user-attachments/assets/e4dad4c7-b6ab-43d2-bf2b-34229d736741)

 And honeycombs are not shear's correct blocks by default. Comb Cutter doesn't not change that. Comb Cutter uses the NeoForge event long after to apply its own mining speed boost which is already very fast that making it faster with Efficiency is kinda pointless
