### ISSUE TITLE
nothing holding up the honey in goliath honey fountain

### ISSUE THREAD

**Issue by kaboom24** [TelepathicGrunt/Bumblezone#444]
please add something to hold up the honey in the secret room of the goliath honey fountain structure

**Comment by TelepathicGrunt** [comment]
What? Show picture please of what you are talking about please

**Comment by TelepathicGrunt** [comment]
This is why I wanted pictures
![image](https://github.com/user-attachments/assets/ea1d0994-11b8-48e2-b2f6-158dd9d4f2b7)

That floating honey is not suppose to be there at all. No support will be added because it snuck in while saving pieces and needs to be removed. Irritating jnfdjsnsdf

**Comment by TelepathicGrunt** [comment]
Fixed in 1.21 v7.7.1 and 1.20.1 v7.5.1
