### ISSUE TITLE
Mod messing up my game and splashes never change when I exit to menu

### ISSUE THREAD

**Issue by vinnyg0621** [TelepathicGrunt/Bumblezone#446]
so when I installed this mod, things in my game were super messed up. it started with entering the bumblezone, and then when I left, the sky was super messed up because of the astrocraft mod, and the season was reset to early spring from the serene seasons mod. and, one of the worst and most annoying of all, _only_ the modded paintings moved up vertically and one of them moved up diagonally!! it does not stop moving until I reset it back to its position where it's supposed to be, but even after I reset the position, the paintings _still_ move up, and never ever stop! 😠
also, when I left the bumblezone from the bottom of the dimension, I fell out of the hive and the clouds just disappeared! ugh, someone please fix this!

**Comment by TelepathicGrunt** [comment]
What is this troll post. If you’re gonna make up fake scenerios, at least make them believable 

Otherwise, if serious, please provide a link to the modpack and a video of the issue

**Comment by TelepathicGrunt** [comment]
Ok so if not trolling, let’s break down this post.

1. splash text not changing
2. Sky messed up outside of Bumblezone dimension
3. Season changed outside Bumblezone
4. Paintings moving
5. Clouds disappearing when falling out of Bumblezone dimension

Here’s my responses
1. Bumblezone does not touch splash text. This is physically not possible to be a Bumblezone issue. 
2. Bumblezone does not control anything about the sky outside the Bumblezone dimension. You said the sky was messed up by Astrocraft mod so not sure why you’re reporting that here when it has nothing to do with my mod.
3. Bumblezone does nothing with seasons. So extremely unlikely Bumblezone even affected this at all. Talk to the seasons mod about this. Maybe you simply spent enough time in Bumblezone that the season changed. 
4. Bumblezone does not touch paintings at all so I have no idea why this is being reported to me. Talk to the mods that modify paintings to see if they can figure it out. Remove mods or try and make a minimal reproducible example to try and find the problematic mod. 
5. Falling out of Bumblezone is an intended way to leave the dimension as I hold player at -3 y level while teleporting out. Bumblezone dimension itself has no clouds and is never supposed to have clouds. Shaders however do not care and may render clouds in my dimension against my wishes and there is nothing I can do on my end. Shader mods needs to respect my dimension special effects settings regarding clouds and stuff https://github.com/TelepathicGrunt/Bumblezone/blob/80fa8fc382cf20aa8f15bdea15aaca593684c45c/common/src/main/java/com/telepathicgrunt/the_bumblezone/client/dimension/BzDimensionSpecialEffects.java#L21

**Comment by vinnyg0621** [comment]
actually when I exit any dimension the season resets to early spring

**Comment by TelepathicGrunt** [comment]
so basically, nothing to do with my mod. Or well, nothing I can do. Please report your issues to the actual mods affected so they can help you troubleshoot
