### ISSUE TITLE
My game crashed when I entered Bumblezone

### ISSUE THREAD

**Issue by FutureLight31** [TelepathicGrunt/Bumblezone#447]
My problem is as I mentioned in the title, my game crashed when I entered the new dimension. I'm leaving the error file below. I play 1.21 fabric in Turkish language.
[disconnect-2024-10-01_02.04.22-client.txt](https://github.com/user-attachments/files/17197339/disconnect-2024-10-01_02.04.22-client.txt)

**Comment by TelepathicGrunt** [comment]
Does disabling Particle Interactions fix the issue? Looks like they may have code that is doing unsafe casting

**Comment by TelepathicGrunt** [comment]
Update Particle Interactions. It seems they fixed the crash 
https://github.com/Enchanted-Games/block-place-particles/issues/5

try and keep mods updated when you can as people release bug fixes often

**Comment by FutureLight31** [comment]
Thanks
