### ISSUE TITLE
Bee essence effect wont work

### ISSUE THREAD

**Issue by Glitchy546** [TelepathicGrunt/Bumblezone#448]
Whenever I die it removes the effect of the Essence of The Bees despite it being stated that it is supposed to be permanent. Is there a config or something?

**Comment by TelepathicGrunt** [comment]
Update to 1.21.1. This was fixed a while ago. Some modpacks are on 1.21 so you’ll have to ask them to put out a 1.21.1 version

**Comment by Glitchy546** [comment]
Oo, Thanks
