### ISSUE TITLE
Bumblezone and Texturized-Particles can cause the game to collapse

### ISSUE THREAD

**Issue by SanQianQVQ** [TelepathicGrunt/Bumblezone#451]
Log: https://mclo.gs/rDzismL

**Comment by SanQianQVQ** [comment]
In addition, I really like this mod, which makes MC more vivid

**Comment by LopyMine** [comment]
What you did to cause the game to crash? This will help me recreate it and find the crash reason

**Comment by TelepathicGrunt** [comment]
That other mod is injecting a mixin into the particle system and seems to have made an assumption that turned out false and crashed. Doubt there’s anything I can do from my end

**Comment by SanQianQVQ** [comment]
> That other mod is injecting a mixin into the particle system and seems to have made an assumption that turned out false and crashed. Doubt there’s anything I can do from my end

A question that is not related to this is after -have you considered sponsoring through Patreon? Because when I use PayPal on KO-Fi, I always have problems with problems (PayPal displaying a system errors)

**Comment by TelepathicGrunt** [comment]
I hate patreon’s monthly paying system and larger slice they take of donations. So I prefer offering kofi so people can do one time payments easier. I do have a patreon if you wish to use it.
https://www.patreon.com/telepathicgrunt

**Comment by SanQianQVQ** [comment]
> I hate patreon’s monthly paying system and larger slice they take of donations. So I prefer offering kofi so people can do one time payments easier. I do have a patreon if you wish to use it. https://www.patreon.com/telepathicgrunt

I don't know much about these, then I still try KO-Fi again

**Comment by TelepathicGrunt** [comment]
Thank you for the donation!
