### ISSUE TITLE
[1.21.1 NeoForge] Cannot join servers, NBT `queen_main_trades_sync_packet` packet too big

### ISSUE THREAD

**Issue by NielsPilgaard** [TelepathicGrunt/Bumblezone#452]
Heya,

After updating Bumblezone I can no longer enter my local server instance.

bumblezone v `7.7.3`
The good stuff is near the bottom 😄
https://gist.github.com/NielsPilgaard/f1cabe49ef55fb80074dfae0ae17486a

**Comment by TelepathicGrunt** [comment]
Please give me your modpack that you were using exactly as is. It is possible you out on too many specific mods that intersected multiple bee queen trades in specific ways that required unwrapping the tags to get the correct chances for each item. This could cause the packet to become too large in theory.

**Comment by TelepathicGrunt** [comment]
Please update bumblezone to v7.7.4. Should fix issue

**Comment by NielsPilgaard** [comment]
Lovely, thank you!

Just in case you're still interested, it happened in Enigmatica 10 v1.11.1, but with Bumblezone on v7.7.3
