### ISSUE TITLE
Fog compat with Bumblezone

### ISSUE THREAD

**Issue by SanQianQVQ** [TelepathicGrunt/Bumblezone#453]
https://github.com/IMB11/Fog

When Bumblezone and Fog are used, the fog color is written by FOG. Can you provide the fog color code of Bumblezone in order to write compatible packets

![_S})03 E2MIU)A8JAZ3V4NG](https://github.com/user-attachments/assets/6c8ce0d6-1e75-427f-bd61-bae8d07a0d6b)

**Comment by TelepathicGrunt** [comment]
What exactly do you mean by compatibility packets? This would not need networking packet code. This is all clientside code. 

I think you should ask the FOG dev to add a config (if one does not exist yet) to allow users to specify biomes or dimensions to not modify the fog of. I suspect FOG is being invasive with its changes and will break any mod that tries to handle fog for their own use cases. Such as Vampirism and my mod here. 

In fact, my mod’s fog color is simply using the vanilla dimension fog color method here. So it seems this FOG mod also possibly breaks datapack dimensions too that specify fog color (or at least breaks any mods overriding this method) 
https://github.com/TelepathicGrunt/Bumblezone/blob/4639879203ba97a829c2d1e5bfdf419e8cc936bb/common/src/main/java/com/telepathicgrunt/the_bumblezone/client/dimension/BzDimensionSpecialEffects.java#L25

**Comment by SanQianQVQ** [comment]
> 兼容性数据包到底是什么意思？这不需要网络数据包代码。这都是客户端代码。
> 
> 我认为您应该要求 FOG 开发人员添加一个配置（如果尚不存在）以允许用户指定不修改雾的生物群落或维度。我怀疑 FOG 的更改具有侵入性，并且会破坏任何试图为自己的用例处理雾的 Mod。比如 Vampirism 和我在这里的 Mod。
> 
> 事实上，我的 Mod 的雾颜色在这里只是使用了原版维度雾的颜色方法。所以看起来这个 FOG mod 也可能破坏指定雾颜色的数据包维度（或者至少破坏了覆盖此方法的任何 mod）
> 
> https://github.com/TelepathicGrunt/Bumblezone/blob/4639879203ba97a829c2d1e5bfdf419e8cc936bb/common/src/main/java/com/telepathicgrunt/the_bumblezone/client/dimension/BzDimensionSpecialEffects.java#L25

https://docs.imb11.dev/fog/fog-definitions here
I checked the wiki of fog, it seems to be realized through the form of a resource package

**Comment by TelepathicGrunt** [comment]
Closing as FOG v1.6.0 is going to fix this issue
