### ISSUE TITLE
server hangs on load version 7.5.3 forge

### ISSUE THREAD

**Issue by icha-senpai** [TelepathicGrunt/Bumblezone#454]
![image](https://github.com/user-attachments/assets/b17047cd-fe1f-498a-8883-fb89457450ac)
this is all the console shows
i down graded to 7.5.2 and the server loads

**Comment by TelepathicGrunt** [comment]
Please give me your entire latest log file. A picture of a snippet is wildly unhelpful tbh.

And if you can give modpack, I can try and see if I can replicate it. But tbh, all 7.5.3 did was just add a small hook to apotheosis for crystalline flower so seem incredibly unlikely that the bumblezone version is event he cause

**Comment by icha-senpai** [comment]
here's the pack https://pixeldrain.com/u/dEC8rUpW use the import feature on curseforge or prism/launcher of choice

here's the server and world https://drive.google.com/file/d/1Lk2KIAO39k2tGHqzBocEQzrHh4H-G32y/view?usp=sharing   might have to adjust java args in the bat/sh file and user jvm file...(i use a custom application manager called AMP by cuber coders to launch the server instead of the bat/sh file)

here's the full lastest log file https://pixeldrain.com/u/9tDBwxPF i think line number 7319 is interesting im not sure what to make of it

**Comment by icha-senpai** [comment]
the pack loads up, its just the server that doesn't load

**Comment by TelepathicGrunt** [comment]
Your latest.log file looks truncated as it stops before any actual crash shows up. Posting the whole log files from server may be more helpful. Can drag and drop the file into github or use pastebin instead of that site.

Also, this is just TNP Limitless 7 unless you modified it heavily. Massive modpack. Make sure you allocated 16 GB of RAM that the pack dev says to allocate. Just to rule out your server running out of memory. Testing your modpack, I am able to launch and run single player. Don't have a server setup for this.

**Comment by icha-senpai** [comment]
Yea i added a lot of extra mods i use 16gb of ram for client and 24 gbs of ram for the server


i sent the whole server setup in the previous message, if you wanted to run it or check it out maybe you see something in it that i don't

heres all the logs from the log folder
[logs.zip](https://github.com/user-attachments/files/17532603/logs.zip)

**Comment by icha-senpai** [comment]
i should note it doesn't actually crash it just hangs indefinitely

**Comment by TelepathicGrunt** [comment]
You may want to try and run a profiler if you can and do a thread dump to see what the game is stuck on. If you got jei on server, try disabling it and see if the recipe collecting is hanging

**Comment by icha-senpai** [comment]
yea it was getting hung up on recipe stuff for kubejs, there was a kubejs update i installed today and it resolved it self after a couple of reboots.

sry for wasting any of your time i appreciate the help
