### ISSUE TITLE
Too Many Entity causes crash when looking around in the dimension

### ISSUE THREAD

**Issue by SaviorD22** [TelepathicGrunt/Bumblezone#455]
When I enter the new biome I have to look straight down to not crash, but the moment I look up the game freezes for 1 second and crashes, throwing the following crash report.

[crash-2024-11-04_22.43.33-client.txt](https://github.com/user-attachments/files/17627099/crash-2024-11-04_22.43.33-client.txt)

**Comment by TelepathicGrunt** [comment]
The first line of that crash already tells you the problematic mod

knot//net.minecraft.class_761.handler$hmm000$too-many-entities$beforeEntityRender(class_761.java:20155)

You’ll want to show this crash to Too Many Entities mod so they can fix their mixin. For now, you can disable that mod

**Comment by TelepathicGrunt** [comment]
Just read closer on Too Many Entity’s mod page. That is a horrible approach to limiting entity rendering. Making entities invisible within field of view is a great way to cause people to die by invisible piglin brutes or other monsters. I would recommend not using that mod.

Please use Entity Culling plus rendering optimization mods such as Sodium/Embeddium.
https://www.curseforge.com/minecraft/mc-mods/entityculling

Entity Culling will skip rendering work for entities that are outside your field of view so you can still see all entities and still get a slight performance boost

**Comment by SaviorD22** [comment]
noted

**Comment by TelepathicGrunt** [comment]
The dev responded that they fixed the issue already and updating the mod would also fix it

https://github.com/Discusser/TooManyEntities/issues/5#issuecomment-2460743582
