### ISSUE TITLE
Possible conflict with RCT (Radical Cobbleman Traders)

### ISSUE THREAD

**Issue by Gamerbolts** [TelepathicGrunt/Bumblezone#456]
Hello, I built a modpack called PXC Cobblemon, and I am running a server. I got a server crash recently. From what I see it is something with Radical Cobbleman Trainers and Bumblezone. I asked the user and they were running away from the boss and crashed. Here is the crash report and log for the server. Any help is appreciated. Also sending this to RCT to see if it is on their end.

[crash-2024-11-06_23.37.29-server.txt](https://github.com/user-attachments/files/17656550/crash-2024-11-06_23.37.29-server.txt)
[2024-11-06-2.log](https://github.com/user-attachments/files/17656567/2024-11-06-2.log)

Minecraft Fabric 1.20.1
Bumblezone v7.5.3

**Comment by TelepathicGrunt** [comment]
Please report to the other mod that their mob is crashing when teleported to another dimension.

**Comment by Gamerbolts** [comment]
Will do. thanks!

**Comment by Gamerbolts** [comment]
Does your mod have a blacklist option so I can blacklist the RCT mod entities from spawning in The Bumblezone?

**Comment by TelepathicGrunt** [comment]
How would I even do the blacklist? There’s nothing for me to blacklist. That mod is injecting their mobs into my biomes and that’s entirely under their control. Spawning behavior would be configs in that mod, not Bumblezone. In this case, it seems that mod is spawning entities at top or bottom of my dimension which triggers the code to teleport the entity out of my dimension. So it’s their spawning code that is also problematic

**Comment by Gamerbolts** [comment]
Apologies. I don't know much about mod coding I thought you could tell your mod to not allow certain entities to spawn. But I am talking with the dev from RCT and let them know the information you told me. So they are getting this fixed. I'll close this now. Thanks for the help 😀

**Comment by Gamerbolts** [comment]
Sorry me again. RCT has a biome blacklist option in their config. What is the bumblezones biome tag?

**Comment by TelepathicGrunt** [comment]
the_bumblezone:the_bumblezone biome tag can be used 
https://github.com/TelepathicGrunt/Bumblezone/blob/1.21-Arch/common/src/main/resources/data/the_bumblezone/tags/worldgen/biome/the_bumblezone.json

**Comment by Gamerbolts** [comment]
Awesome! Thank you!
