### ISSUE TITLE
Essence of Continuity - Tick Damage Bricking Server

### ISSUE THREAD

**Issue by IreneAquaBlue** [TelepathicGrunt/Bumblezone#457]
Hello! I play on a small multiplayer server with a mod pack that includes multiple new weapons and armor. Some attacks (in particular attacks that deal tick damage) will cause the server to completely crash. I have included relevant crash logs.

[crash-2024-11-09_02.16.10-server.txt](https://github.com/user-attachments/files/17685490/crash-2024-11-09_02.16.10-server.txt)
[crash-2024-11-09_01.42.19-server.txt](https://github.com/user-attachments/files/17685491/crash-2024-11-09_01.42.19-server.txt)

**Comment by TelepathicGrunt** [comment]
The bug is not in Bumblezone. It is in apoli library which is in the origins mod

use this mod to fix the apoli bug since the dev does not Backport fixes 
https://legacy.curseforge.com/minecraft/mc-mods/origins-apoli-armor-mixin-fix
