### ISSUE TITLE
stinger_spear has no durability

### ISSUE THREAD

**Issue by SanQianQVQ** [TelepathicGrunt/Bumblezone#458]
Bumblezone - 7.5.2
Fabric 1.20.1
![image](https://github.com/user-attachments/assets/3740cd73-29e8-4022-817a-27fd75271011)

**Comment by TelepathicGrunt** [comment]
Yes it does
![image](https://github.com/user-attachments/assets/d89c987a-5302-4503-9070-6917b77c51a3)

You have to damage the tool first for durability to show up. This is vanilla behavior. I threw the spear and durability showed

**Comment by SanQianQVQ** [comment]
> Yes it does ![image](https://private-user-images.githubusercontent.com/40846040/384700071-d89c987a-5302-4503-9070-6917b77c51a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyNTI4MTgsIm5iZiI6MTczMTI1MjUxOCwicGF0aCI6Ii80MDg0NjA0MC8zODQ3MDAwNzEtZDg5Yzk4N2EtNTMwMi00NTAzLTkwNzAtNjkxN2I3N2M1MWEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEwVDE1MjgzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzYTI5MmJiYWVjMDI4ZjRlZjRiYzNlNTIyZWFlZDhkZDJlZWUyZDFkNjM3NTE4NDAwNWFiNzYwZmUyMzMyMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.clbIhK-nDXS34Mq4pk7cP_qwK3zjEJ0NmCBwdgiSf3A)
> 
> You have to damage the tool first for durability to show up. This is vanilla behavior. I threw the spear and durability showed

Sorry, I have determined that this is a problem caused by the repair spell of another module
Thank you for your timely work
