### ISSUE TITLE
[Lang] Missing Music Disc Translation

### ISSUE THREAD

**Issue by AriaElidove** [TelepathicGrunt/Bumblezone#461]
"Bee-laxing with the Hom-bees" music disc is missing it's download link translation. That is all.
![image](https://github.com/user-attachments/assets/3cd372b7-5ff8-4209-89f0-baf9c1f39380)

**Comment by TelepathicGrunt** [comment]
Fixed with https://github.com/TelepathicGrunt/Bumblezone/commit/65575abc3964ad85fa71e7f202c338e93f2b2f52
And now released
