### ISSUE TITLE
(NeoForge-21.1.80 on MC 1.21.1) Queen trades disregarding "count" value in possible_rewards

### ISSUE THREAD

**Issue by miles-mcd** [TelepathicGrunt/Bumblezone#462]
I first noticed this in All The Mods 10, so then went and tested it on a fresh install of NeoForge with no other mods installed, where I encountered the same issue.

Minecraft (Java) 1.21.1
NeoForge 21.1.80
Bumblezone versions:
  7.6.23+121.1-neoforge
  7.7.8+1.21.1-neoforge

I verified this issue on both the earliest and latest versions available on CurseForge for 1.21.1, and so presume it is an issue for the versions between.

When trading with the Queen, I tried combining four Royal Jelly bottles together into a block, since JEI indicated that doing so would, in some cases, effectively get more items per bottle.  (24 end crystals for 4, instead of 1:1.  10 dragon's breath for four, rather than 2:1, 32 XP bottles, rather than 6:1.  And so forth.)

I noticed that I was only getting one of each item for each trade, regardless of the number listed in JEI.  I verified that this was happening for both Royal Jelly Blocks and Royal Jelly Buckets.  I then checked inside the .jar, to see what I could see there.  I found that the Bottle was supposed to be getting 4 Turtle Egg at a time, but was only getting one.  Then looked for something that would eliminate any randomness in the testing.  I found that Amethyst Block and Quartz Block both had only a single possible reward, and should be providing four items per trade.  For each one, it was the right reward, but only a single per trade, rather than the four.

I hope this is sufficiently detailed information to be able to locate the source of the issue.

Thanks!

**Comment by TelepathicGrunt** [comment]
Fixed in v7.7.9
