### ISSUE TITLE
Queen Bee won't advence from Raw Chicken, can't clear

### ISSUE THREAD

**Issue by BuddhaBuddy1** [TelepathicGrunt/Bumblezone#463]
I'm trying to get Royal Jelly. Everything I read says to give her whatever is on her chest, but that is Raw Chicken. I've given her probably 20 stacks of raw chicken, and I just get food items back and a Happy Thanksgiving emote. I also read that I should be able to reset by right-clicking on her with an empty hand, but that doesn't do anything.

Was this broken on purpose for the days around Thanksgiving? It is the day after, and it is still just asking for raw chicken, and not completing the advancement.

I'm playing Project Architect 2.

**Comment by TelepathicGrunt** [comment]
The trade shown in hand is just the bonus trades that’s available. Which is 3x the normal result. On holidays, the bonus trade is replaced with holiday trades. You can still do other trades even then on holidays or off holidays. Bonus trade is just limited time extra trades and is _not_ a required item for trading

royal Jelly is not available from trades either. It is a reward of completing the bee queen’s advancement line unless the modpack made changes

**Comment by BuddhaBuddy1** [comment]
I guess I misunderstood. Once I made some nests (quest said Beehives worked, but I had to make Bee Nests), I got a jelly.

**Comment by TelepathicGrunt** [comment]
Beehives also work. Specifically any block that extends BeeHiveBlock or so. If it was a modded beehive, lmk which so I can investigate that hive. Also, MI crafting terminal doesn’t trigger recipe crafted stuff in 1.20.1 so using a normal crafting table is ideal to rule out modded crafting screens not working 

Will close since you got a jelly
