### ISSUE TITLE
Compatibility with EMI Ores

### ISSUE THREAD

**Issue by MuteTiefling** [TelepathicGrunt/Bumblezone#464]
[EMI Ores](https://www.curseforge.com/minecraft/mc-mods/emi-ores) is an addon mod for EMI which attempts to show where ores spawn by biome. 

As a result, it displays mini 16x16 depictions of the biome in EMI

![image](https://github.com/user-attachments/assets/1cd22ae7-d642-46b9-b61c-191d6bab38fe)

It would be nice if you could create some for your biomes and ship them in the mod. You could include them in your own assets folder as shown here: https://github.com/Abbie5/emi-ores/tree/1.21/xplat/src/main/resources/assets/minecraft/textures/emi_ores/biome_icon

**Comment by TelepathicGrunt** [comment]
Bumblezone doesn’t have ores

**Comment by MuteTiefling** [comment]
I know, but the biomes get pulled in anyway and currently show as purple/black broken textures

**Comment by TelepathicGrunt** [comment]
Or do you mean just images of the biomes. They would probably look like shit if I were to draw them

**Comment by MuteTiefling** [comment]
yeah, just images. Can't possibly be worse than my hack at it 
![image](https://github.com/user-attachments/assets/e0d58f27-96f1-4be7-b599-8ac1120f8244)

**Comment by MuteTiefling** [comment]
Thanks!
