### ISSUE TITLE
Nether Portal Broken

### ISSUE THREAD

**Issue by DinosaurZabsy19** [TelepathicGrunt/Bumblezone#465]
Whenever i try to light a nether portal it breaks and displays the message 'a dimensional lock breaks the portal. Maybe the queen bee can help'. I have searched and searched for answers and was wondering if there's an item or something that I need to fix this plz help

**Comment by TelepathicGrunt** [comment]
The modpack you’re playing on has added dimension locking. Ask the pack maker for what is required to unlock the dimensions or check the quests in the modpack

**Comment by TelepathicGrunt** [comment]
What modpack were you playing on? I would like to know what pack is confusing people

**Comment by DinosaurZabsy19** [comment]
Hi,

Sorry it was my mistake.

 It was the bumble zone mod pack and I couldn’t work out why there was a
dimensional lock on the nether portal but I now know that I needed to
complete all of the quests to get the item to unlock the portal

**Comment by TelepathicGrunt** [comment]
Bumblezone modpack? Bumblezone is a mod. Not a modpack itself. Modpacks come in different names such as Enigmatica 9 Expert or All the Mods. Though I think the modpack you were playing was Dimensional Ascension

**Comment by DinosaurZabsy19** [comment]
Yes it was the bumblezone mod within the dimensional ascension modpack
