### ISSUE TITLE
Consuming the Essence of the Bees

### ISSUE THREAD

**Issue by danmvision** [TelepathicGrunt/Bumblezone#468]
Hi,
I'm a little puzzled, I did the Bee Queen questline to get the Essence of the Bees.
So I got the item but when I try to consume it with right clicking, nothing happen.
Am I missing something or did I need to consume it before resetting the questline ??

**Comment by TelepathicGrunt** [comment]
You eat the essence of the bees item to consume it. Hold the eat button until done. Once eaten, it will disable bee aggression from most sources and allow you to do Sempiternal sanctum structures. See the wiki for more info

**Comment by danmvision** [comment]
Thanks... I wasn't holding the eat button long enough because there's no eating animation.

Cheers !!

**Comment by TelepathicGrunt** [comment]
Just tested, it does have an eating animation. Unless you have a mod on that is messing with eating animations on but that would not be something I can address on my end

https://github.com/user-attachments/assets/cb85be92-2067-4ff5-b2ac-c1f78745765a
