### ISSUE TITLE
[1.16.5-Forge] Disabling Comb Block generation not working.

### ISSUE THREAD

**Issue by Gbergz** [TelepathicGrunt/Bumblezone#47]
Title^

In the file ``the_bumblezone-mod_compatibility``, I've tried to disable this config line for productive bees comb block spawns:

``		# Spawn Productive Bees's various honeycomb variants in The Bumblezone
		# at all kinds of heights and height bands. Start exploring to find 
		# where they spawn! 
		# NOTE: Will require a restart of the world to take effect. 
		#
		spawnProductiveBeesHoneycombVariants = false``
		
Even with it disabled (false), they still spawn in there. Is this config option bugged or is it something I'm missing here?

And if this config option is not what I expected, is it possible to add a config option to disable all of these combs spawning:
![image](https://user-images.githubusercontent.com/26634554/106812349-d40da880-666f-11eb-9922-11d689b5e338.png)

**Minecraft:** 1.16.5
**Forge:** 36.0.13
**Productive Bees Version:** 0.6.2
**Bumblezone version:** 2.2.11

Thanks,
**-** Gbergz

**Comment by TelepathicGrunt** [comment]
It seems i made it disable only the combs in the bee dungeons by mistake. You can disable them with a datapack however by overriding this file and list all the productive comb blocks you dont want to spawn
https://github.com/TelepathicGrunt/Bumblezone/blob/1.16/src/main/resources/data/the_bumblezone/tags/blocks/blacklisted_productive_bees_combs.json

**Comment by TelepathicGrunt** [comment]
fixed in 2.2.12! hopefully. lmk if you have any issues and check out the changelog as well. Some modcompat configs were adjusted too
