### ISSUE TITLE
Disabling shaders with dimension ID not working 

### ISSUE THREAD

**Issue by charmesal** [TelepathicGrunt/Bumblezone#54]
I'm trying to exclude the Bumblezone from shaderpacks because they make it way too dark.
The only way to do this, as far as I was able to find, is to create an empty folder in the shaders folder with the name 
"worldN" where 'N' is the dimension ID (https://github.com/sp614x/optifine/issues/2729). Now I tried several variants like:
worldthe_bumblezone.the_bumblezone
worldthe_bumblezone
the_bumblezone.the_bumblezone
the_bumblezone
worldminecraft_dimension (Dynmap uses this name for the dimension)
minecraft_dimension

worldthe_bumblezone:the_bumblezone is impossible as Windows does not let you have a ':' in a file/folder name

Other dimensions have a number as their ID. Is there one for The Bumblezone perhaps?
Is there any other way to exclude your dimension from shaderpacks?

**Comment by TelepathicGrunt** [comment]
the_bumblezone:the_bumblezone is the id of the dimension. I do not know how optifine works so I cannot help you here with it. Sorry. You'll have to find people who know more about shaders and optifine on how to help you.

Also, if optifine is still using numeric ids for dimensions, someone should slap sp614x lol. Numeric ids has been dead since 1.13 and should never be used for targeting dimensions as there's no guarantee that the ID would always remain the same. Instead, he should be using the resourcelocation properly. You'll have to somehow find the numeric id of bumblezone in-game somehow but i do not know how.

**Comment by charmesal** [comment]
Thanks for the quick reply.
If "the_bumblezone:the_bumblezone"is the ID then there is no way to exclude it from shaders as Windows does not allow me to have a ':' in a foldername. It's a shame but it can't be helped. People who wanna build a base will just have to do without fancy shaders.

I don't think optifine uses integers anymore but when checking shaderpacks they do use world<int> so my guess is that the mod authors of mods that add dimensions might just name them after their original ID.

**Comment by TelepathicGrunt** [comment]
well, the thing is, all dimensions are resource location ids. For example, vanilla dimensions are minecraft:overworld, minecraft:the_nether, minecraft:the_end so it sounds like it is still using int ids. Again, you'll have to ask them how optifine works as I have no clue lol

**Comment by charmesal** [comment]
I just so happened to notice [this](https://imgur.com/a/8Aro6r5) during startup. So perhaps you're right and they are still using int ids.
Creating a folder called world14 in the shaders folder worked like a charm.
The value changes when you add or remove other mods that add dimensions.
I'm not sure if this will ever be of use to you but it might be for others with the same issue I had so I wanted to make this last reply to answer my own question just in case anyone finds it.

**Comment by Parloienx** [comment]
> I just so happened to notice [this](https://imgur.com/a/8Aro6r5) during startup. So perhaps you're right and they are still using int ids. Creating a folder called world14 in the shaders folder worked like a charm. The value changes when you add or remove other mods that add dimensions. I'm not sure if this will ever be of use to you but it might be for others with the same issue I had so I wanted to make this last reply to answer my own question just in case anyone finds it.

How did you get "this". Where would I find mine. Aka what is it?

**Comment by TelepathicGrunt** [comment]
@Parloienx i believe that’s the latest.log file from the logs folder above the mods folder

**Comment by charmesal** [comment]
> > I just so happened to notice [this](https://imgur.com/a/8Aro6r5) during startup. So perhaps you're right and they are still using int ids. Creating a folder called world14 in the shaders folder worked like a charm. The value changes when you add or remove other mods that add dimensions. I'm not sure if this will ever be of use to you but it might be for others with the same issue I had so I wanted to make this last reply to answer my own question just in case anyone finds it.
> 
> How did you get "this". Where would I find mine. Aka what is it?

@TelepathicGrunt is correct. You can find it in the latest.log file( and in the console if you use one of those).

**Comment by Parloienx** [comment]
hmmm, sadly I don't have that portion in my latest log for some reason

**Comment by charmesal** [comment]
> hmmm, sadly I don't have that portion in my latest log for some reason

I'm not sure how it works these days. The mods could have changed how they load and/or log the relevant data.
If you want you can add me on Discord and I'll see what I can do for you but I can't promise a solution.

**Comment by Parloienx** [comment]
> > hmmm, sadly I don't have that portion in my latest log for some reason
> 
> I'm not sure how it works these days. The mods could have changed how they load and/or log the relevant data. If you want you can add me on Discord and I'll see what I can do for you but I can't promise a solution.

It's ok. I am just doing the same thing as you. I am just trying to add it to the Vault Hunters Modpack and shaders kind of destroys the dimension they created making everything dark.

**Comment by Parloienx** [comment]
It's 1.16.5 but I don't know if that was out then so you might be right that it changed.

**Comment by charmesal** [comment]
> It's 1.16.5 but I don't know if that was out then so you might be right that it changed.

I honestly don't remember what version I was on back then. Could be 1.16.5.
Can you load up your game and start/load a single player world and the attach your latest.log file in a comment?

**Comment by Parloienx** [comment]
sure

**Comment by Parloienx** [comment]
[latest.log](https://github.com/TelepathicGrunt/Bumblezone/files/8453290/latest.log)

**Comment by charmesal** [comment]
> [latest.log](https://github.com/TelepathicGrunt/Bumblezone/files/8453290/latest.log)

I'm unable to find any useful information for you. However I do remember now that I used the mod [Immersive Portal](https://www.curseforge.com/minecraft/mc-mods/immersive-portals-for-forge). I _think_ that gives the dimensions their numbers again but I'm not 100% sure.
But you  can try and add it to see if it gives you the output in the log.
Be aware that the assigned number changes if you add or remove dimensions so if this does work it will also add some dimensions from the mod itself meaning that if you play on an official Vault Hunters server they won't have Immersive Portals and thus have different dimension ID's and then the shaders might still be broken in the Bumblezone.

For now this is the only remaining thing I can do to help. If it still won't work then I'll check if I have time tomorrow, but I won't be spending hours on this, sorry.

**Comment by TelepathicGrunt** [comment]
Check if TellMe mod allows you to dump the dimension registry with the int ids. If so, that may be the solution. https://www.curseforge.com/minecraft/mc-mods/tellme

**Comment by charmesal** [comment]
> Check if TellMe mod allows you to dump the dimension registry with the int ids. If so, that may be the solution. https://www.curseforge.com/minecraft/mc-mods/tellme

That seems very promising. Let us know how it turns out.

**Comment by Parloienx** [comment]
> Check if TellMe mod allows you to dump the dimension registry with the int ids. If so, that may be the solution. https://www.curseforge.com/minecraft/mc-mods/tellme

I already tried that

**Comment by Parloienx** [comment]
Thanks for all the help :)

**Comment by Parloienx** [comment]
> > Check if TellMe mod allows you to dump the dimension registry with the int ids. If so, that may be the solution. https://www.curseforge.com/minecraft/mc-mods/tellme
> 
> That seems very promising. Let us know how it turns out.

You might have done it with the immersive portals mod. Loading in...

**Comment by Parloienx** [comment]
That seemed to work. Thank you

**Comment by charmesal** [comment]
> That seemed to work. Thank you

Glad to hear it works. Just keep in mind that servers won't have the Immersive Portals mod and therefore can have different dimension IDs.
