### ISSUE TITLE
Crash upon joining server

### ISSUE THREAD

**Issue by KajesLorian** [TelepathicGrunt/Bumblezone#61]
Both Server and Client loaded fine, but Client crashed when attempting to join server.

Forge 1.16.5
Modloader Ver. 36.1.0

https://pastebin.com/ZDiN6CMK

**Comment by TelepathicGrunt** [comment]
thank you for the report but v2.4.1 hotfix was already released that should fix this issue. Try updating and see if the issue is resolved!
