### ISSUE TITLE
Add Enchantment Descriptions compat for Comb Cutter

### ISSUE THREAD

**Issue by pm065** [TelepathicGrunt/Bumblezone#69]
Just a line in en_us.json. 
`"enchantment.the_bumblegarden.comb_cutter.desc": "add description here"`
I'd do it myself but I don't actually know what the enchantment does.

**Comment by TelepathicGrunt** [comment]
How do you see enchantment descriptions? Is it something only this mod does? https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions

anyway, I'll add it next update but you can always find out what everything does in my mod by looking at my mod page https://www.curseforge.com/minecraft/mc-mods/the-bumblezone-forge

From the page:

# Enchantments - 1 new enchantment
## Comb Cutter
-Can be applied to Swords and Shears

-Only 1 level but will make the tool mine all comb based blocks super fast! It will also mine wax, hive, and nest blocks slightly faster.

-Can be used to double the Honeycomb output from Beehives and Bee Nests.
 
-Newer versions of Resourceful Bees will allow Comb Cutter tools to be used to double their Beehive/Beenest outputs too.

**Comment by pm065** [comment]
Oh, thank you! Yes, it is only that mod, though it's supported by many others. Searching through the enchantments in my modpack this was one of the few that had no description :)
