### ISSUE TITLE
Bumblezone not respecting blacklisted Resourceful Bees

### ISSUE THREAD

**Issue by Lucky-Red** [TelepathicGrunt/Bumblezone#72]
In the attached config, I've blacklisted the Dragon, Wither, and Netherite bees from the default spawns in the Bumblezone, yet the bees and their comb blocks both continue to spawn in the dimension.
https://pastebin.com/8ikmuLnN
This is in the 1.16.5 version of the mod for Forge

**Comment by TelepathicGrunt** [comment]
hmm I am still using config entry for that blacklist. I'll see what's up with it but I may just turn it into an entitytype tag since resourceful bees has a separate entitytype for every bee. Would that be more ideal for you?

**Comment by TelepathicGrunt** [comment]
Oh your blacklist is off. it's not resourcefulbees:wither, it's resourcefulbees:wither_bee. Add _bee to the end of all your entries and see if that works

**Comment by Lucky-Red** [comment]
Making those changes results in breaking the compatibility with Resourceful Bees, preventing any blocks or entities from the mod from spawning in the Bumblezone. 
Here's the error from the debug.log
https://pastebin.com/L2UpvZAi

**Comment by TelepathicGrunt** [comment]
oh no. I think i see my issue. I did a dumb in my code. Sorry hang on

**Comment by TelepathicGrunt** [comment]
v2.4.10 bumblezone is now released and should fix this issue. Try that version and let me know if it no longer crashes and blacklists the bees properly

**Comment by Lucky-Red** [comment]
The update appears to have fixed the issue. Everything seems to be working fine now!

**Comment by TelepathicGrunt** [comment]
Nice! I'll close this now
