### ISSUE TITLE
Newest update causes error on startup

### ISSUE THREAD

**Issue by Pepelespooder** [TelepathicGrunt/Bumblezone#78]
Newest version Seems to cause a honey liquid error for me. 

[crash-2021-10-03_20.22.25-client.txt](https://github.com/TelepathicGrunt/Bumblezone/files/7274786/crash-2021-10-03_20.22.25-client.txt)

**Comment by TelepathicGrunt** [comment]
May I ask what you were doing at the time to cause the crash? Something is trying to set the honey fluid properly to level 9 when it cannot go higher than 8. And the part that is crashing is here so it seems like a possible mod conflict. But the logs doesnt say anything and I do not get the crash myself. Though I will try and see if I can restrict the value here 
https://github.com/TelepathicGrunt/Bumblezone/blob/c119d03919371b66ad2508d51fae175122949b19/src/main/java/com/telepathicgrunt/the_bumblezone/blocks/HoneyFluidBlock.java#L100

**Comment by TelepathicGrunt** [comment]
Can you unzip and try this jar? It should fix the crash by preventing the fluidLevel field from being lower than 0 or higher than 8. Though it may make whatever thing was trying to get a level 9 fluid to break somewhere. Interestingly enough, vanilla does restrict the value itself but then, why do i not crash if I use only bumblezone.... hmm
[the_bumblezone_forge-2.5.1-b+1.16.5.zip](https://github.com/TelepathicGrunt/Bumblezone/files/7274820/the_bumblezone_forge-2.5.1-b%2B1.16.5.zip)

**Comment by Pepelespooder** [comment]
I was Starting up minecraft and it crashed on start up Something must've been setting the Value on start up? In the previous version i do not get this error so im currently just using that at the moment

**Comment by TelepathicGrunt** [comment]
the previous version of bumblezone does not have the honey fluid. I went ahead and released the restriction version onto curseforge so the crash shouldn't happen now. but yeah, thank you for letting me know lol. Still strange tho

**Comment by Pepelespooder** [comment]
@TelepathicGrunt  Grunt the only thing I can think of after looking back into that log is , productive bees, Buzzier bees , or Resourceful bees. specifically the one that adds a honey fluid it self ? which is think is productive bees? Only thing I can think of that could possibly be trying to change the fluid for something relating to honey

**Comment by TelepathicGrunt** [comment]
Whatever it was, it shouldn't cause an issue. Since vanilla limits their vanilla fluid property at the same spot, there must had been an edge case I have missed and thus, blew up. Dunno what it was but I don't think i need to investigate further unless my fix also blows up lol
