### ISSUE TITLE
Sugar water can be placed in the nether

### ISSUE THREAD

**Issue by WenXin20** [TelepathicGrunt/Bumblezone#79]
`Minecraft v1.16.5`
`Forge v36.2.4`
`Bumblezone v2.5.1`

If a honey crystal is waterlogged, sugar water will be placed in the nether. 
Also noticed that honey crystals will become waterlogged when placed in flowing sugar water, which spreads the water in the nether even more. (Not sure if that is intended or not.) 
Also noticed that no empty bucket is returned when waterlogging the honey crystal in survival.

**Comment by TelepathicGrunt** [comment]
thank you for reporting this! New update is released to fix this. attempting to waterlog the honey crystal in nether will now fail. It wont clear out the crystals you already waterlogged so remove those from your world and it should be good now

**Comment by WenXin20** [comment]
Thanks! And no worries, it was just a test creative world. :D
