### ISSUE TITLE
[1.16.5 Forge] Better End Forge crashes Bumblezone at world load

### ISSUE THREAD

**Issue by HockeyZman2000** [TelepathicGrunt/Bumblezone#87]
I'm posting this here in hopes someone can tell me why my server keeps crashing. Not even sure if its this mod or another structure, but the server keeps crashing after a couple minutes due to this error. If there's a certain mod causing it that I haven't seen please lmk!

Crash Report: https://pastebin.com/khJRLWDa

Server Log: 
[latest.log](https://github.com/TelepathicGrunt/RepurposedStructures/files/7430261/latest.log)

**Comment by TelepathicGrunt** [comment]
Looks like a mod's structure spacing/separation was null and that crashed the game. Try putting on Blame and then recreate the crash and give me the latest.log https://www.curseforge.com/minecraft/mc-mods/blame

Although the crash here is occuring in a very strange spot that blame may not be able to detect at. If you can send me your modpack profile (curseforge launcher can export a modpack profile) or zip up your folder with all the mods and configs, I can try and reproduce the issue and poke around faster

**Comment by HockeyZman2000** [comment]
[latest.log](https://github.com/TelepathicGrunt/RepurposedStructures/files/7430349/latest.log)

This is the latest log after installing Blame.
Crash occurs a few minutes after server startup is finished, regardless on if a player is on the server or not.

**Comment by HockeyZman2000** [comment]
Let me get that modpack for you

**Comment by HockeyZman2000** [comment]
Github wasn't letting me directly upload the zip file so I had to do a workaround. Here is the modpack for both client and server.

https://drive.google.com/file/d/1gToUSF5Ayv9X57hlJFMfu9WrzlHDWnT-/view?usp=sharing

**Comment by TelepathicGrunt** [comment]
Sorry for delay. Something weird is going on where the crash only seems to occur with certain combinations of mods on. Can you try removing bumblezone or advancedrocketry and remove both and see if that makes the crash go away? It takes me so long to load the modpack so I was only able to launch a few time and for some reason, this mixin i made to try and find what spacing is null for what structure but the logs did not print anything out. https://paste.ee/p/jjRCk

It makes me wonder if a codec somewhere is broken, a dimension is corrupted, or another mod is interfering with how dimension save to disk.

**Comment by HockeyZman2000** [comment]
Not a problem. It does take a considerable amount of time for it to load, sorry about that. I noticed that someone on The Bumblezone GitHub mentioned having a similar issue with structure spacing a few days ago, specifically issue TelepathicGrunt/RepurposedStructures#83. Maybe they're related somehow? Removing The Bumblezone seems to have stopped the server from crashing.

**Comment by TelepathicGrunt** [comment]
The link you gave is about the random I changed and not anyone having a structure crash. 

Though I am not sure why the crash is occurring thinking that there’s no spacing configs for structures in Bumblezone and why I cannot reproduce it with Bumblezone alone. 

I’ll double check it’s codec later and check if the level.dat is corrupted for bumblezone dimension or not

**Comment by TelepathicGrunt** [comment]
Interesting, I disabled Better End Forge and kept on all the other mods and the crash went away. As far as I can tell my mod's codec in bumblezone looks to be fine and the dimension json has the two structures with their spacing so it should not be null ever. 
https://github.com/TelepathicGrunt/Bumblezone/blob/60d0d1209ebe3b08d1a3ff14beeb32626101344a/src/main/java/com/telepathicgrunt/the_bumblezone/world/dimension/BzChunkGenerator.java#L65-L69
https://github.com/TelepathicGrunt/Bumblezone/blob/60d0d1209ebe3b08d1a3ff14beeb32626101344a/src/main/resources/data/the_bumblezone/dimension/the_bumblezone.json#L8-L21

Testing with better end and bumblezone only alone causes the crash. I am not sure why or how better end is causing this crash with bumblezone on: https://paste.ee/p/6383v

**Comment by TelepathicGrunt** [comment]
Ok so the BetterEndForge-Reforked mod had a cave structure that is not registered and its spacing not setup in its  betterendforge-1.16.5-2.2.jar. They did fix the issue in their codebase so you just need to wait for their next update and then this crash should go away

**Comment by HockeyZman2000** [comment]
Thank you so much for all your help! That makes sense because I had just updated to that version along with updating a ton of other mods. I'll wait for the update and hopefully the crash will be fixed.

**Comment by TelepathicGrunt** [comment]
The dev was quick and released betterendforge-1.16.5-2.3 update now. I tested and the crash no longer happens now. Looks like the issue is resolved. Thank you for reporting!
