### ISSUE TITLE
Vanilla recipe for honey blocks is overridden, making honey blocks uncraftable without adding another recipe

### ISSUE THREAD

**Issue by Commoble** [TelepathicGrunt/Bumblezone#9]
Normally, Honey Blocks are craftable with four bottles of honey. This recipe is defined under the `minecraft:honey_block` identifier.

The Bumblezone adds a recipe that takes a honey block as an ingredient and is used to smelt honey blocks into sticky honey residue. This recipe is also defined under the `minecraft:honey_block` identifier.

This overrides the vanilla recipe, as two recipes can't have the same identifier; this makes the vanilla recipe mysteriously absent, as well as making it difficult and confusing for modpack and datapack makers to put the original recipe back or adjust it.

By convention, this recipe should be named `the_bumblezone:sticky_honey_residue` or `the_bumblezone:sticky_honey_residue_from_smelting`.

**Comment by TelepathicGrunt** [comment]
Resolved and the patch is out. Thank you!
