### ISSUE TITLE
v4.0.0 (1.18.1 MC) Forge crashing when hive hit with ender pearl

### ISSUE THREAD

**Issue by nanonestor** [TelepathicGrunt/Bumblezone#94]
Forge version - 39.0.5
Bumblezone (Forge) version - v4.0.0 (1.18.1 MC)

-- Game crashes when ender pearls thrown at hive in-game.  Tested 3 time with same results.
-- Other mods are present, mod list can be found in crash report.

Crash Report
[(https://paste.gg/p/anonymous/d82259af97fc42ca865462dc4a5ececa)](https://paste.gg/p/anonymous/d82259af97fc42ca865462dc4a5ececa)

latest.log

[(https://paste.gg/p/anonymous/ffcc5f1783c444bc9e50768b63632bba)]
(https://paste.gg/p/anonymous/ffcc5f1783c444bc9e50768b63632bba)

**Comment by TelepathicGrunt** [comment]
`appeng.worldgen.meteorite.MeteoriteStructure.checkLocation(MeteoriteStructure.java:68) ~[appliedenergistics2-10.0.0-alpha.6.jar%2351!:10.0.0-alpha.6] `

Try blacklisting Applied Endergistics 2's meteors from Bumblezone's dimension. I'll look into why their stuff is blowing up my chunk generator.

**Comment by TelepathicGrunt** [comment]
Seems the crash is caused when a mod tries to call getBaseHeight on my chunk generator. v4.0.1 update is out and should fix that.

**Comment by nanonestor** [comment]
Thank you!  Love the mod and bumblezone. :)
