### ISSUE TITLE
v4.0.1 for 1.18.1 Forge crashes with specific mod

### ISSUE THREAD

**Issue by nanonestor** [TelepathicGrunt/Bumblezone#96]
Bumblezone version - v4.0.1 for 1.18.1
Forge version - 39.0.7

Game crashes when trying to enter bumblezone by throwing ender pearl at hive - when the mod [Thuts Elevators](https://www.curseforge.com/minecraft/mc-mods/thuts-elevators) is also loaded.  It took a bunch of reloading to figure out which in my pack was causing the conflict or something.  As it's showing bumblzone in the report that's why i'm posting the logs here, if you think this is caused by an error in Thuts apologies I'll take logs to their github.

With the Forge and mods listed in the crash report it will crash entering the BZ.  With thuttech-1.18.1-9.1.4.jar removed it will load into the BZ and not crash.

Crash Report
[crash report](https://paste.gg/p/anonymous/ace7210676954aa7aacc9e38ffd754ed)
latest.log
[latest.log](https://paste.gg/p/anonymous/028a3b762db34803af85b9e14797eaf0)

**Comment by TelepathicGrunt** [comment]
Can you test with v4.1.0 bumblezone and see if the issue still persist?

**Comment by TelepathicGrunt** [comment]
No response in over 17 days so I am guessing the issue resolved itself. Lmk if it is still happening with latest update of Bumblezone and I will reopen report
